### ISSUE TITLE
TypeError: this.notebook.onDidChangeCellLanguage is not a function

### ISSUE THREAD

**Issue by jerryc05** [microsoft/pylance-release#1036]
## Environment data

-   Language Server version: `v2021.3.2-pre.1`
-   OS and version: `Win10 | WSL Ubuntu - groovy`
-   Python version (& distribution if applicable, e.g. Anaconda): `Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210220] on linux`

## Expected behaviour

After VSCode started for a while, the python/pylance language server starts successfully.

## Actual behaviour

The python/pylance language server failed to start, leaving the python file with no syntax highlighting.

I have never encountered this strange behavior until last night (May 11th, 2021).

## Logs

```
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
Error 2021-03-12 01:17:41: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:175816)
	at new u (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:174085)
	at Object.t.resolveInstance (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:268557)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267523
	at Object.t.resolve (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267786)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258362
	at e._get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258128)
	at e.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:256840)
	at a.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:444806)
	at new b (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:9:418400)
	at r.startLanguageServer (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:59:245270)]
Error 2021-03-12 01:17:41: Failed to start language server, Class name = r, completed in 3ms, has a falsy return value, Arg 1: <Uri:/mnt/d/Programming/MyTemplate/ParallelPy.py>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.2-final","major":3,"minor":9,"patch":2,"prerelease":["final"],"build":[],"version":"3.9.2-final"},"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210220]","sysPrefix":"/usr","fileHash":"d55197ab955e9c41b31e976ff783ec3056f592ddbf64573c18c4778c4211e0187df27757390c9669241afb1c42367cd4c519ea4ad5280ddc11f88489677129ec","envType":"Unknown","displayName":"Python 3.9.2 64-bit"}, Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:175816)
	at new u (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:174085)
	at Object.t.resolveInstance (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:268557)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267523
	at Object.t.resolve (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267786)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258362
	at e._get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258128)
	at e.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:256840)
	at a.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:444806)
	at new b (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:9:418400)
	at r.startLanguageServer (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:59:245270)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
Error 2021-03-12 01:17:41: [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:175816)
	at new u (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:174085)
	at Object.t.resolveInstance (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:268557)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267523
	at Object.t.resolve (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267786)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258362
	at e._get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258128)
	at e.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:256840)
	at a.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:444806)
	at new b (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:9:418400)
	at r.startLanguageServer (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:59:245270)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-03-12 01:17:41: Failed to activate language server, Class name = a, completed in 6ms, has a falsy return value, Arg 1: <Uri:/mnt/d/Programming/MyTemplate/ParallelPy.py>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.2-final","major":3,"minor":9,"patch":2,"prerelease":["final"],"build":[],"version":"3.9.2-final"},"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210220]","sysPrefix":"/usr","fileHash":"d55197ab955e9c41b31e976ff783ec3056f592ddbf64573c18c4778c4211e0187df27757390c9669241afb1c42367cd4c519ea4ad5280ddc11f88489677129ec","envType":"Unknown","displayName":"Python 3.9.2 64-bit"}, Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:175816)
	at new u (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:174085)
	at Object.t.resolveInstance (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:268557)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267523
	at Object.t.resolve (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:267786)
	at /home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258362
	at e._get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:258128)
	at e.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:44:256840)
	at a.get (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:78:444806)
	at new b (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:9:418400)
	at r.startLanguageServer (/home/?/.vscode-server-insiders/extensions/ms-python.python-2021.2.636928669/out/client/extension.js:59:245270)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
The `TypeError: this.notebook.onDidChangeCellLanguage is not a function` is caused by some recent churn with the Python and Jupyter extensions when it comes to notebook support (Pylance is only involved because Jupyter hooks in to give cells to Pylance).

VS Code insiders keeps changing faster than the extensions that depend on it can release, and I think that only the insiders builds of the Jupyter extension work properly (if at all sometimes). See:

https://github.com/microsoft/vscode-python/issues/15637
https://github.com/microsoft/vscode-python/issues/15638

Which covers the underlying problem.

**Comment by jerryc05** [comment]
ty!
