### ISSUE TITLE
Pylance fails to start

### ISSUE THREAD

**Issue by GuillaumeDesforges** [microsoft/pylance-release#1058]
EDIT: see comments below, the Pylance server just does not start and vscode-python falls back to Jedi.

## Environment data

-   Language Server version: v2021.3.1
-   OS and version: Windows 10 over SSH to NixOS 20.03 server
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.7

## Expected behaviour

When pressing "quick action" shortcut (`Ctrl+;` for me, azerty keyboard) on a symbol which is not imported, it should display the list of available imports.

e.g.

```
# datetime not imported, has squiggle below it
foo = datetime()
```

press "quick action" shortcut, get a quick action "import 'datetime' from 'datetime'", click on it:

```
from datetime import datetime

# no more errors, datetime is imported
foo = datetime()
```

## Actual behaviour

No quick action available.

## Logs

<details>

<summary>Logs</summary>

```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonDiscoveryModule'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonFindInterpreter'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
Error 2021-03-17 10:32:15: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+poseideep.local/home/arsleust/.config/Code - Insiders/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+poseideep.local/home/arsleust/.config/Code - Insiders/User/settings.json')
	at _handleError (/home/arsleust/.vscode-server-insiders/bin/892a1083cb2b9b3987ff7edc85376b5d9764433d/out/vs/server/remoteExtensionHostProcess.js:86:151930)
	at async y.readText (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:577456)
	at async /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:576583
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:576529)
	at async p.updateTestSettings (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:576156)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Error 2021-03-17 10:32:16: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)]
Error 2021-03-17 10:32:16: Failed to start language server, Class name = r, completed in 123ms, has a falsy return value, Arg 1: <Uri:/home/arsleust/polaranalytics/etl/.vscode/settings.json>, Arg 2: {"sysPrefix":"","envType":"Venv","envName":".venv","envPath":"/home/arsleust/polaranalytics/etl/.venv","path":"/home/arsleust/polaranalytics/etl/.venv/bin/python","architecture":1,"sysVersion":"","version":{"raw":"3.8.7","major":3,"minor":8,"patch":7,"build":[],"prerelease":[]},"displayName":"Python 3.8.7  ('.venv': venv)"}, Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)]
Error 2021-03-17 10:32:16: [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-03-17 10:32:16: Failed to activate language server, Class name = a, completed in 528ms, has a falsy return value, Arg 1: <Uri:/home/arsleust/polaranalytics/etl/.vscode/settings.json>, Arg 2: {"sysPrefix":"","envType":"Venv","envName":".venv","envPath":"/home/arsleust/polaranalytics/etl/.venv","path":"/home/arsleust/polaranalytics/etl/.venv/bin/python","architecture":1,"sysVersion":"","version":{"raw":"3.8.7","major":3,"minor":8,"patch":7,"build":[],"prerelease":[]},"displayName":"Python 3.8.7  ('.venv': venv)"}, Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)]
Python interpreter path: ./.venv/bin/python
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/polaranalytics/etl
> conda --version
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/completion.py
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/completion.py
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/polaranalytics/etl/dags/daily.py
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/polaranalytics/etl/dags/daily.py
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/polaranalytics/etl/dags/daily.py
cwd: ~/polaranalytics/etl
> ~/polaranalytics/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/polaranalytics/etl/dags/daily.py
cwd: ~/polaranalytics/etl
Error 2021-03-17 10:32:17: stderr jediProxy Error (stderr) /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(
```

</details>

## Code Snippet / Additional information

![importissue](https://user-images.githubusercontent.com/1882000/111448570-d7845d00-870e-11eb-9b72-99ace9d79c4e.gif)

**Comment by GuillaumeDesforges** [comment]
Could it be that the server just fails starting ?

```
Error 2021-03-17 11:00:45: Failed to restart language server, Class name = r, completed in 7ms, has a falsy return value, , Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
```

**Comment by GuillaumeDesforges** [comment]
Ok, Pylance does not even start

```
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-03-17 11:21:24: Failed to activate language server, Class name = a, completed in 636ms, has a falsy return value, Arg 1: <Uri:/home/arsleust/polaranalytics/polar.code-workspace>, Arg 2: {"sysPrefix":"","envType":"Venv","envName":".venv","envPath":"/home/arsleust/polaranalytics/thegrowthteam-audit/.venv","path":"/home/arsleust/polaranalytics/thegrowthteam-audit/.venv/bin/python","architecture":1,"sysVersion":"","version":{"raw":"3.7.9","major":3,"minor":7,"patch":9,"build":[],"prerelease":[]},"displayName":"Python 3.7.9  ('.venv': venv)"}, Return Value: undefined [TypeError: this.notebook.onDidChangeCellLanguage is not a function
	at u.addEventHandlers (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:175335)
	at new u (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:173604)
	at Object.t.resolveInstance (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:268557)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267523
	at Object.t.resolve (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:267786)
	at /home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258362
	at e._get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:258128)
	at e.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:44:256840)
	at a.get (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:80:440953)
	at new y (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:9:428432)
	at r.startLanguageServer (/home/arsleust/.vscode-server-insiders/extensions/ms-python.python-2021.4.640901529-dev/out/client/extension.js:61:246177)]
```

**Comment by GuillaumeDesforges** [comment]
Seems related to https://github.com/microsoft/vscode-python/issues/15638

**Comment by GuillaumeDesforges** [comment]
Updating to 1.55.0 using `"python.insidersChannel": "daily"` fixed it for me.
