### ISSUE TITLE
pylance

### ISSUE THREAD

**Issue by fudadong** [microsoft/pylance-release#1072]
An internal error occurred while type checking file "d:\_bp\gameserver\server\monitor\views.py": Error: Debug Failure. False expression.
    at getAliasedSymbolTypeForName (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:14259:9)
    at evaluateTypesForImportAs (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:13283:26)
    at Object.evaluateTypesForStatement (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:14577:21)
    at callback (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluatorWithTracker.ts:66:66)
    at i.timeOperation (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\common\timing.ts:40:20)
    at run (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluatorWithTracker.ts:42:46)
    at Object.evaluateTypesForStatement (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\typeEvaluatorWithTracker.ts:66:13)
    at C.visitImportAs (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\checker.ts:946:25)
    at C.visitNode (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:250:26)
    at C.walk (c:\Users\FDD\.vscode\extensions\ms-python.vscode-pylance-2021.3.2\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:96:37)

**Comment by fudadong** [comment]
python script is run ok, but output this error

**Comment by erictraut** [comment]
Thanks for the bug report.

Is your project checked in to a public github repo perhaps? Having access to the code would help reproduce the problem. If you can't share the code, perhaps you can narrow down the problem and share a self-contained piece of code that exhibits the problem?

**Comment by jakebailey** [comment]
I believe this should be fixed in the next release via https://github.com/microsoft/pyright/commit/706a5a4b9a20cd36a86ee31fbae1f1f800e65a63.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.4.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202142-21-april-2021
