### ISSUE TITLE
CentOS 7 code completions and suggestions become very slow

### ISSUE THREAD

**Issue by parasurama** [microsoft/pylance-release#1143]
ms-python.python extension fails loading on remote

## Environment data

-   VS Code version: 1.55.0
-   Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS and version: CentOS 7
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: NA
-   Relevant/affected Python-related VS Code extensions and their versions: ms-python.python
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

XXX

## Actual behaviour

python extension fails loading. 
Intellisense becomes slow when this happens. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. N/A

## Steps taken to solve
So far I've tried
- Reinstalling python and pylance extensions
- Reinstalling vscode 
- Disabling all other extensions

None of these worked
## Logs

Logs from remote extension host
<details>

<summary>Output for <code>Remote Extension Code</code> in the <code>Output</code> panel </summary>

<p>

```
[2021-04-08 13:37:01.727] [exthost] [info] extension host started
[2021-04-08 13:37:01.792] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter {"startup":false,"extensionId":{"value":"ms-toolsai.jupyter","_lower":"ms-toolsai.jupyter"},"activationEvent":"onLanguage:python"}
[2021-04-08 13:37:01.792] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension
[2021-04-08 13:37:01.992] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2021-04-08 13:37:01.992] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/configuration-editing/dist/configurationEditingMain
[2021-04-08 13:37:01.997] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-04-08 13:37:01.997] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-04-08 13:37:02.030] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-04-08 13:37:02.030] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/typescript-language-features/dist/extension
[2021-04-08 13:37:02.054] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-04-08 13:37:02.054] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/debug-auto-launch/dist/extension
[2021-04-08 13:37:02.056] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-04-08 13:37:02.056] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/git/dist/main
[2021-04-08 13:37:02.210] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-04-08 13:37:02.210] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/github/dist/extension.js
[2021-04-08 13:37:02.488] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-04-08 13:37:02.488] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/emmet/dist/node/emmetNodeMain
[2021-04-08 13:37:02.500] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-04-08 13:37:02.500] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/merge-conflict/dist/mergeConflictMain
[2021-04-08 13:37:02.503] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-04-08 13:37:02.503] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/testing-editor-contributions/dist/extension.js
[2021-04-08 13:37:02.504] [exthost] [info] eager extensions activated
[2021-04-08 13:37:02.524] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-04-08 13:37:02.524] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/extensions/ms-vscode.js-debug/src/extension.js
[2021-04-08 13:37:02.740] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.vscode-pylance","_lower":"ms-python.vscode-pylance"},"activationEvent":"onLanguage:python"}
[2021-04-08 13:37:02.740] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension
[2021-04-08 13:37:03.226] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance {"startup":false,"extensionId":{"value":"ms-python.vscode-pylance","_lower":"ms-python.vscode-pylance"},"activationEvent":"onLanguage:python"}
[2021-04-08 13:37:03.227] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/prasanna/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.0/dist/extension.bundle.js
[2021-04-08 13:37:21.769] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:21.769] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:135392
	at async M.provideCompletionItems (/home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/remoteExtensionHostProcess.js:86:170847)
[2021-04-08 13:37:22.062] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:22.062] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:135788
	at async M.resolveCompletionItem (/home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/remoteExtensionHostProcess.js:86:171572)
[2021-04-08 13:37:33.391] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:33.391] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:56.640] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:56.640] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:56.648] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:56.648] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:56.653] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:56.653] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:56.658] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:56.658] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:56.663] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:56.663] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:37:57.828] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:57.828] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:140172
[2021-04-08 13:37:57.832] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:37:57.832] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:38:00.129] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:38:00.129] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:136580
[2021-04-08 13:38:03.316] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:38:03.316] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
[2021-04-08 13:38:08.879] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:38:08.879] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:144099
	at runMicrotasks (<anonymous>)
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)
[2021-04-08 13:40:32.575] [exthost] [error] [ms-python.python] provider FAILED
[2021-04-08 13:40:32.575] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176221)
	at E.handleFailedRequest (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:176072)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:136580
```

</p>
</details>

Logs from python 
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'CollectLSRequestTiming - control'
Error 2021-04-08 13:48:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat '/rnddata/Python2.6.1/bin/python2.6'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/rnddata/Python2.6.1/bin/python2.6'
}
Error 2021-04-08 13:48:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat '/gridapps/Python-3.4.3/bin/python3.4'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/gridapps/Python-3.4.3/bin/python3.4'
}
Error 2021-04-08 13:48:34: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-08 13:48:34: Failed to parse version from path: /usr/bin/python [Error: invalid version python
	at u (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-08 13:48:34: Failed to parse version from path: /home/prasanna/anaconda3/bin/python [Error: invalid version python
	at u (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-08 13:48:35: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+prasannac7/home/prasanna/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+prasannac7/home/prasanna/.config/Code/User/settings.json')
	at _handleError (/home/prasanna/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:578263)
	at async /home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577390
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577336)
	at async p.updateTestSettings (/home/prasanna/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:576963)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Python interpreter path: ~/anaconda3/envs/lang_env/bin/python

```

</p>
</details>

**Comment by jakebailey** [comment]
Can you please enable trace logging and provide Pylance's logs? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
