### ISSUE TITLE
Pylance doesn't index new file automatically

### ISSUE THREAD

**Issue by paulzhn** [microsoft/pylance-release#1169]
## Environment data

-   Language Server version: v2021.4.1
-   OS and version: Ubuntu 20.04 (remote)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Behavior

When create a new file, Pylance would not index it automatically, and if import it, it would say missing import; after  a manual restart of vscode, it could index the file normally.

## Logs

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonDiscoveryModule'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
Error 2021-04-18 22:38:10: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-18 22:38:11: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+tencent/home/paul/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+tencent/home/paul/.config/Code/User/settings.json')
	at _handleError (/home/paul/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:578263)
	at async /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577390
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577336)
	at async p.updateTestSettings (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:576963)] {
  code: 'FileNotFound'
}
Error 2021-04-18 22:38:11: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+tencent/home/paul/communist_backend/.vscode/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+tencent/home/paul/communist_backend/.vscode/settings.json')
	at _handleError (/home/paul/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:578263)
	at async /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577390
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577336)
	at async p.updateTestSettings (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:576963)] {
  code: 'FileNotFound'
}
Error 2021-04-18 22:38:11: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-18 22:38:11: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-18 22:38:11: Failed to parse version from path: /usr/bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at p.resolveEnv (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29309)
	at E.resolveEnv (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:29:4121)
	at t.PythonEnvsReducer.resolveEnv (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:762313)
	at async t.PythonEnvsResolver.resolveEnv (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:763669)
	at async u.doResolveEnv (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:757654)
	at async q.getInterpreterDetails (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:38813)
	at async C.getInterpreterDetails (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:741545)
	at async f.updateDisplay (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:729765)
	at async f.refresh (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:729292)]
Python interpreter path: /usr/bin/python
Error 2021-04-18 22:38:11: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Error 2021-04-18 22:38:11: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Starting Pylance language server.
Error 2021-04-18 22:38:12: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
> conda --version
Error 2021-04-18 22:38:26: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Python interpreter path: /usr/bin/python3
Error 2021-04-18 22:38:27: Failed to parse version from path: /bin/python [Error: invalid version python
	at u (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/paul/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53829)]
Python interpreter path: /usr/bin/python
```

## Code Snippet / Additional information

The behavior before the window reload: the filename is in white color and the Pylance informs missing import

![image](https://user-images.githubusercontent.com/8180364/115149435-b0ff6c00-a096-11eb-86e1-d9ba4ebec478.png)

![image](https://user-images.githubusercontent.com/8180364/115149438-b78de380-a096-11eb-8d1e-8662c5eb0456.png)

After the reload:

![image](https://user-images.githubusercontent.com/8180364/115149451-c70d2c80-a096-11eb-907d-4f5502a0b5a3.png)

**Comment by bschnurr** [comment]
Is this in a nested folder? for more information on how to grab the logs see this link https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

thank you

**Comment by jakebailey** [comment]
It's been a month since we asked the above and added the "waiting for info" label; if you can answer the above questions and fill out the info, we can reopen this.
