### ISSUE TITLE
Python Intellisense does not work in ssh environment

### ISSUE THREAD

**Issue by jason-jk-kang** [microsoft/pylance-release#1225]
## Environment data

-   VS Code version: 1.55.2
-   Extension version (available under the Extensions sidebar): Python: v2021.4.765268190 and Pylance: v2021.4.3
-   OS and version: MacOS Catalina 10.15.7 and Ubuntu 14.04 (ssh)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.4 and 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): SSH'd into linux machine
-   Relevant/affected Python packages and their versions: na
-   Relevant/affected Python-related VS Code extensions and their versions: na
-   Value of the `python.languageServer` setting: pyLance

## Expected behaviour

In my python files, I expect there to be more syntax highlighting and the ability to move between variables by ctrl - clicking them. I am able to have this normal expected behavior if I open a new folder in my ssh environment. It might be the case that my working directory is too large?

## Actual behaviour

Very little is highlighted. I suspect that IntelliSense is not picking up on my python code.

## Steps to reproduce:

1. Open VSCode
2. Open ssh portal to workstation
3. Open .py file

## Logs

</summary>

<summary><code>Settings.json</code></summary>

```
{
    "python.languageServer": "Pylance",
    "python.pythonPath": "~/usr/bin/python3.6",
    "python.analysis.logLevel": "Trace",
    "remote.autoForwardPortsSource": "output",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.associations": {
        "*.bazel": "starlark",
        "*.bazelrc": "shellscript",
        "requirements3.txt": "pip-requirements",
        "*.idl":"cpp",
    },
    "files.exclude": {
        "experimental/" : true, // <----- may want to toggle on/off depending on development
        "**/bazel-*/": true,
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "**/bazel-*": true,
    },

    "search.exclude": {
        "experimental/": true // <----- may want to toggle on/off depending on development
    },

    "bazel.buildifierExecutable": "/usr/local/bin/buildifier",

    "C_Cpp.clang_format_path": "/usr/bin/clang-format-3.6",
    "C_Cpp.clang_format_fallbackStyle": "file",
}
```

<summary>Output for <code>Python Language Server</code> in the <code>Output</code> panel 
</summary>

```
0: ExitFrame [pc: 0x13cf019]
Security context: 0x1ff2f50808d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x1b23e0a3e309] [/home/jkang/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright.bundle.js:~1] [pc=0x2cb1cbee1d5a](this=0x3fcd5eb004b1 <undefined>,0x35c5706184c9 <Object map = 0x31ac5ecf9c39>)
    2: forEach [0x1ff2f5096769](this=0x38d1ee8ebb31 <JSArray[1489231]>,0x1b23e0a3e309 <JSFunction (sfi = 0...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa093f0 node::Abort() [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 2: 0xa097fc node::OnFatalError(char const*, char const*) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 3: 0xb842ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 4: 0xb84629 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 5: 0xd30fe5  [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 6: 0xd31676 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 7: 0xd3def5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 8: 0xd3eda5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
 9: 0xd4185c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
10: 0xd0830b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
11: 0x1049f4e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
12: 0x13cf019  [/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node]
[Info  - 11:12:38 AM] Connection to server got closed. Server will restart.
[Error - 11:12:38 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:68124)
	at Object.dispose (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:178962)
	at E.handleConnectionClosed (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:179174)
	at E.handleConnectionClosed (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:21817)
	at t (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:177267)
	at invoke (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:318776)
	at o.fire (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:319537)
	at X (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:57486)
	at invoke (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:318776)
	at o.fire (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:319537)
	at d.fireClose (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:47555)
	at ChildProcess.<anonymous> (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:314506)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[Error - 11:12:38 AM] Request textDocument/codeAction failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/full failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
...
[Error - 11:12:38 AM] Request textDocument/hover failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
...
[Error - 11:12:38 AM] Request textDocument/semanticTokens/range failed.
```

<summary>Output for <code>Python</code> in the <code>Output</code> panel </summary>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'DeprecatePythonPath - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
> conda --version
```

<p>

I am encountering this error where intellisense does not work for my python files in my ssh window (accessed with the remote development kit). I have uninstalled and reinstalled. My `settings.json` file on my remote workstation match my `settings.json` file on my laptop (where intellisense does work). I have tested to make sure that the correct python interpreter is selected on my ssh machine, and that this python interpreter launches and will run code. 

My output window previously showed this error:

```
Error 2021-04-30 13:53:16: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+172.16.214.73/home/jkang/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+172.16.214.73/home/jkang/.config/Code/User/settings.json')
	at _handleError (/home/jkang/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/server/remoteExtensionHostProcess.js:86:154942)
	at async y.readText (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:339523)
	at async p.doesFileNeedToBeFixed (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:577126)
	at async /home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:576253
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:576199)
	at async p.updateTestSettings (/home/jkang/.vscode-server/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:575826)] {
  code: 'FileNotFound'
}
```

I created this file `home/jkang/.config/Code/User/settings.json` with content `{}` in order to satisfy this error. It no longer shows.

Additionally, when I googled this problem some suggested that I run `python: build workplace symbols`. However, I am not able to and I get the error 

```
Command 'Python: Build Workspace Symbols' resulted in an error (command 'python.buildWorkspaceSymbols' not found)
```
Can anyone help me? This is very frustrating.

</p>
</details>

**Comment by jakebailey** [comment]
The error above appears to be an out of memory error; we had a couple of fixes to things like that for tomorrow.

There's no need for that "build workspace symbols" call; that's not used when Pylance is enabled (we do our own symbol indexing).

**Comment by jakebailey** [comment]
@jason-jk-kang it's been a while since I posted the above message; I'm thinking that this out of memory is fixed by now, but if you're still having trouble and can provide some trace logs, that'd be very helpful.
