### ISSUE TITLE
Pylance tried to read a non-exist setting file but not the actual setting location

### ISSUE THREAD

**Issue by ruifengma** [microsoft/pylance-release#1336]
I've got an error as following, I check the path which pylance tried to locate the file but it actually doesn't exist, the actual setting file for remote which is under the /.vscode-server/data/......
```
Python interpreter path: /home/administrator/anaconda3/bin/python
> conda --version
> pyenv root
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /home/zhangtao/anaconda3/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> conda env list
Starting Pylance language server.
Error 2021-05-24 11:36:14: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+bd1/home/ma/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+bd1/home/ma/.config/Code/User/settings.json')
	at _handleError (/home/ma/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:87:156171)
	at async y.readText (/home/ma/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/ma/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:581560)
	at async /home/ma/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580687
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/ma/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/ma/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
> conda info --json
> conda info --json
```

**Comment by jakebailey** [comment]
These are the Python extension's logs, not Pylance's logs. Transferring to their repo.
