### ISSUE TITLE
Pylance fails to load, errors while reading extensions.js

### ISSUE THREAD

**Issue by rohitsathish** [microsoft/pylance-release#1395]
Pylance seems to be throwing some errors while loading and since it doesn't start, VSCode is switching to a different language server under the hood. 

I'm using VSCode Insiders with Jupyter. Pylance was working perfectly yesterday but I played with a couple of settings and installed some new extensions which caused it to break. Uninstalling all extensions doesn't solve the problem.

Would be grateful for any help. Thanks.

## Environment data

Pylance 2021.6.0
Python 3.8.5, Anaconda

Version: 1.57.0-insider (user setup)
Commit: 387e2f39ebbbf50d4b488f900b2a745972764015
Date: 2021-06-04T05:14:06.974Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

## Expected behaviour

Pylance loads with all features

## Actual behaviour

Pylance throwing errors while loading

## Logs
```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
Python interpreter path: ~\anaconda3\python.exe
Starting Pylance language server.
Error 2021-06-04 17:48:38: Starting language server, Class name = r, completed in 5ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-04 17:48:38: Failed to start language server, Class name = r, completed in 12ms, has a falsy return value, Arg 1: <Uri:c:\Users\user\Documents\Coding\My_Files>, Arg 2: {"sysPrefix":"C:\\Users\\user\\anaconda3","envType":"Conda","envName":"base","envPath":"C:\\Users\\user\\anaconda3","path":"C:\\Users\\user\\anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.5","major":3,"minor":8,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.5 64-bit ('base': conda)"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-04 17:48:38: [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-04 17:48:38: Failed to activate language server, Class name = a, completed in 24ms, has a falsy return value, Arg 1: <Uri:c:\Users\user\Documents\Coding\My_Files>, Arg 2: {"sysPrefix":"C:\\Users\\user\\anaconda3","envType":"Conda","envName":"base","envPath":"C:\\Users\\user\\anaconda3","path":"C:\\Users\\user\\anaconda3\\python.exe","architecture":3,"sysVersion":"3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.8.5","major":3,"minor":8,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.8.5 64-bit ('base': conda)"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-04 17:49:34: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:49:34: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:49:34: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:49:45: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:49:57: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:50:32: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:50:46: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:50:55: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:51:01: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:00: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:07: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:11: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:17: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:17: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
Error 2021-06-04 17:52:17: getActivatedEnvironmentVariables [Error: Command failed: C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: "C:/Users/user/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2021.5.842923320\\pythonFiles\\pyvsc-run-isolated.py c:/Users/user/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/printEnvVariables.py"
}
```

**Comment by espenfjo** [comment]
This is fixed in the current daily/insiders build of the python module.

**Comment by jakebailey** [comment]
Yes, this should be fixed already: https://github.com/microsoft/vscode-jupyter/issues/6095

If you continue to see this, you should report an issue on the Jupyter tracker.
