### ISSUE TITLE
Pylance not working in VS Code 1.57.0+

### ISSUE THREAD

**Issue by CircuitSacul** [microsoft/pylance-release#1428]
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda):  Anaconda, python 3.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Semantic highlighting works. For example, I expect valid modules and imports to be green.

<h3> Actual behaviour </h3>

Installing/uninstalling pylance does not affect the colors of the editor

<h3> Logs </h3>

<h3> Code Snippet / Additional information </h3>
<h4> Before vscode update <h2>
<img width="242" alt="Screen Shot 2021-06-10 at 2 47 26 PM" src="https://user-images.githubusercontent.com/55721663/121580460-c8096d00-c9fa-11eb-98b3-bd5e5220328e.png">
<h4> After the vscode update <h2>
<img width="363" alt="Screen Shot 2021-06-10 at 2 48 24 PM" src="https://user-images.githubusercontent.com/55721663/121580603-ebccb300-c9fa-11eb-8fce-90c8a0d6ecbf.png">

**Comment by jakebailey** [comment]
Our template asks for trace logs; can you provide them?

The bug reporting instructions from the template are mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by CircuitSacul** [comment]
@jakebailey I tried, but I couldn't find where logs were printed to. Where would I get those from?

**Comment by jakebailey** [comment]
No worries, I can reproduce this. This appears to be an issue with the Python extension and the Jupyter extension, which is preventing the language server from starting.

```
Python interpreter path: .\.venv\Scripts\python.exe
Starting Pylance language server.
Error 2021-06-10 11:51:37: Starting language server, Class name = r, completed in 0ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-10 11:51:37: Failed to start language server, Class name = r, completed in 5ms, has a falsy return value, Arg 1: <Uri:e:\work\demo-apps\ds-1\ds-1.py>, Arg 2: {"sysPrefix":"","envType":"Venv","envName":".venv","envPath":"e:\\work\\demo-apps\\ds-1\\.venv","path":"e:\\work\\demo-apps\\ds-1\\.venv\\Scripts\\python.exe","architecture":1,"sysVersion":"","version":{"raw":"3.8.6","major":3,"minor":8,"patch":6,"build":[],"prerelease":[]},"displayName":"Python 3.8.10 64-bit ('.venv': venv)"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-10 11:51:37: [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-10 11:51:37: Failed to activate language server, Class name = a, completed in 9ms, has a falsy return value, Arg 1: <Uri:e:\work\demo-apps\ds-1\ds-1.py>, Arg 2: {"sysPrefix":"","envType":"Venv","envName":".venv","envPath":"e:\\work\\demo-apps\\ds-1\\.venv","path":"e:\\work\\demo-apps\\ds-1\\.venv\\Scripts\\python.exe","architecture":1,"sysVersion":"","version":{"raw":"3.8.6","major":3,"minor":8,"patch":6,"build":[],"prerelease":[]},"displayName":"Python 3.8.10 64-bit ('.venv': venv)"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\jabaile\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
```

**Comment by jakebailey** [comment]
VS Code 1.57 was released just recently, and it appears as though the constant notebook API churn has come to stable and broken the last version of the Python extension.

As a workaround, can you enable Python's insiders channel?

```
"python.insidersChannel": "daily",
```

**Comment by CircuitSacul** [comment]
@jakebailey That solves it, thanks. @trag1c

**Comment by jakebailey** [comment]
A fix is in progress in the Python extension; I'll close this once the fix is available and the workaround is no longer needed.

**Comment by mohamed3nan** [comment]
"python.insidersChannel": "daily",
    "pylance.insidersChannel": "daily",

> VS Code 1.57 was released just recently, and it appears as though the constant notebook API churn has come to stable and broken the last version of the Python extension.
> 
> As a workaround, can you enable Python's insiders channel?
> 
> ```
> "python.insidersChannel": "daily",
> ```

Thanks
`    "python.insidersChannel": "daily",
    "pylance.insidersChannel": "daily",`

**Comment by cread** [comment]
> VS Code 1.57 was released just recently, and it appears as though the constant notebook API churn has come to stable and broken the last version of the Python extension.
> 
> As a workaround, can you enable Python's insiders channel?
> 
> ```
> "python.insidersChannel": "daily",
> ```

This workaround does **not** work when using a Remote Connection.

**Comment by jakebailey** [comment]
Version 2021.5.926500501 of the Python extension has just been released; if you update, this issue should go away.

**Comment by theGASK** [comment]
I confirm that the issue has been resolved with the update.  Fantastic work.

**Comment by cread** [comment]
Confirmed for remote too. Thanks for the quick turnaround.

**Comment by lazyoracle** [comment]
I know I am polluting the comments section and probably sending redundant notifications, but I just came here to say that I am genuinely delighted by how quick you guys pushed a fix for this. Thanks for all the great work!

**Comment by mohamed3nan** [comment]
the bug is still active in VS code insiders!

**Comment by erkin98** [comment]
the bug is still active in VS code insiders!

**Comment by Midhilesh4890** [comment]
I see the bug is still active in VS Code. 
When I uninstall C/C++ themes(ms-vscode.cpptools-themes) I can see python imports in color

**Comment by rchiodo** [comment]
> I see the bug is still active in VS Code. When I uninstall C/C++ themes(ms-vscode.cpptools-themes) I can see python imports in color

@Midhilesh4890 can you open a new issue and provide the information in the troubleshooting guide:

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
