### ISSUE TITLE
Python Tools server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by fuad47** [microsoft/pylance-release#1438]
## Environment data

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 17, in <module>
    from functools import cached_property  # type: ignore
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\fuad47\appdata\local\programs\python\python37\lib\functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\runJediLanguageServer.py", line 89, in <module>
    from jedi_language_server.cli import cli
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\cli.py", line 5, in <module>
    from .server import SERVER
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\server.py", line 55, in <module>
    from . import jedi_utils, pygls_utils, text_edit_utils
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\jedi_utils.py", line 34, in <module>
    from .initialize_params_parser import InitializeParamsParser
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 19, in <module>
    from cached_property import cached_property  # type: ignore
ModuleNotFoundError: No module named 'cached_property'
[Info  - 6:49:48 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 17, in <module>
    from functools import cached_property  # type: ignore
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\fuad47\appdata\local\programs\python\python37\lib\functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\runJediLanguageServer.py", line 89, in <module>
    from jedi_language_server.cli import cli
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\cli.py", line 5, in <module>
    from .server import SERVER
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\server.py", line 55, in <module>
    from . import jedi_utils, pygls_utils, text_edit_utils
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\jedi_utils.py", line 34, in <module>
    from .initialize_params_parser import InitializeParamsParser
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 19, in <module>
    from cached_property import cached_property  # type: ignore
ModuleNotFoundError: No module named 'cached_property'
[Info  - 6:49:49 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 17, in <module>
    from functools import cached_property  # type: ignore
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\fuad47\appdata\local\programs\python\python37\lib\functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\runJediLanguageServer.py", line 89, in <module>
    from jedi_language_server.cli import cli
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\cli.py", line 5, in <module>
    from .server import SERVER
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\server.py", line 55, in <module>
    from . import jedi_utils, pygls_utils, text_edit_utils
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\jedi_utils.py", line 34, in <module>
    from .initialize_params_parser import InitializeParamsParser
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 19, in <module>
    from cached_property import cached_property  # type: ignore
ModuleNotFoundError: No module named 'cached_property'
[Info  - 6:49:50 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 17, in <module>
    from functools import cached_property  # type: ignore
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\fuad47\appdata\local\programs\python\python37\lib\functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\runJediLanguageServer.py", line 89, in <module>
    from jedi_language_server.cli import cli
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\cli.py", line 5, in <module>
    from .server import SERVER
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\server.py", line 55, in <module>
    from . import jedi_utils, pygls_utils, text_edit_utils
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\jedi_utils.py", line 34, in <module>
    from .initialize_params_parser import InitializeParamsParser
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 19, in <module>
    from cached_property import cached_property  # type: ignore
ModuleNotFoundError: No module named 'cached_property'
[Info  - 6:49:50 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 17, in <module>
    from functools import cached_property  # type: ignore
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\fuad47\appdata\local\programs\python\python37\lib\functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\runJediLanguageServer.py", line 89, in <module>
    from jedi_language_server.cli import cli
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\cli.py", line 5, in <module>
    from .server import SERVER
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\server.py", line 55, in <module>
    from . import jedi_utils, pygls_utils, text_edit_utils
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\jedi_utils.py", line 34, in <module>
    from .initialize_params_parser import InitializeParamsParser
  File "c:\Users\Fuad47\.vscode\extensions\ms-python.python-2021.2.633441544\pythonFiles\lib\python\jedi_language_server\initialize_params_parser.py", line 19, in <module>
    from cached_property import cached_property  # type: ignore
ModuleNotFoundError: No module named 'cached_property'
[Error - 6:49:51 PM] Connection to server got closed. Server will not be restarted.

**Comment by jakebailey** [comment]
These logs are from the Jedi language server, not Pylance.
