### ISSUE TITLE
Python tool server crash

### ISSUE THREAD

**Issue by j-sodhi** [microsoft/pylance-release#1450]
## Environment data

-   Language Server version: 2021.6.01 or 2021.6.0
-   OS and version: CentOS Linux release 7.8.2003
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
RangeError: WebAssembly.Memory(): could not allocate memory
    at Object.78848 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/vendor.bundle.js:2:316369)
    at _0x3fe772 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/server.bundle.js:1:346819)
    at Object.r [as getLibzipSync] (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/vendor.bundle.js:2:604763)
    at new C (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/pyright.bundle.js:1:707774)
    at Object.6021 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/pyright.bundle.js:1:707968)
    at _0x3fe772 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/server.bundle.js:1:346819)
    at Object.44314 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/pyright.bundle.js:1:253232)
    at _0x3fe772 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/server.bundle.js:1:346819)
    at Object.52599 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/pyright.bundle.js:1:733139)
    at _0x3fe772 (/home/jsodhi/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist/server.bundle.js:1:346819)
[Error - 5:00:22 PM] Connection to server got closed. Server will not be restarted.
```

## Code Snippet / Additional information

Language Server version: 2021.5.4 and previous works.

**Comment by j-sodhi** [comment]
I am not using Docker.
I am directly using Remote - SSH extension to login into the remote server.
I do not know about the memory limit.

**Comment by jakebailey** [comment]
On the remote machine, can you run `free -m` and give the output?

**Comment by j-sodhi** [comment]
total          used           free      hared  buff/cache   available
Mem:         128539        6606       14625         869       107308     106052
Swap:         10239                 0       10239

**Comment by jakebailey** [comment]
Yeah, that should be more than enough free space...

**Comment by j-sodhi** [comment]
I only started having this issue from 2021.6.0. 
When I revert to Pylance version 2021.5.4 the language server works fine.

**Comment by jakebailey** [comment]
Yes, as `2021.6.0` is the first version to support egg/zip files, which makes use of a WASM module to operate.

**Comment by j-sodhi** [comment]
I hope the next version fixes this issue. Thanks!

**Comment by judej** [comment]
@j-sodhi, are you still seeing this issue?
