### ISSUE TITLE
An internal error occurred while type checking file showing on all files

### ISSUE THREAD

**Issue by MurtazaSKH** [microsoft/pylance-release#1472]
Issue Type: <b>Bug</b>

After randomly restarting system..
Now this errors shows up on all files, on the first line.
everything is working, however the error is highlighted red in multiple places.

the error given below=> 
An internal error occurred while type checking file "e:\Projects\PythonML\CV-Subject\Analysis.py": RangeError: Maximum call stack size exceeded
    at makeTopLevelTypeVarsConcrete (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3285:14)
    at expandSubtype (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3368:19)
    at mapSubtypesExpandTypeVars (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3393:13)
    at validateCallArguments (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7210:28)
    at callback (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7566:44)
    at callback (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3377:41)
    at Object.doForEachSubtype (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeUtils.ts:206:9)
    at expandSubtype (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3370:13)
    at mapSubtypesExpandTypeVars (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3393:13)
    at _t (c:\Users\Murtaza\.vscode\extensions\ms-python.vscode-pylance-2021.6.2\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7210:2

Extension version: 2021.6.2
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

**Comment by erictraut** [comment]
By chance, is your project checked in to a public github repo? If so, please send a link so we can repro and diagnose.

If your project isn't checked in to a public github repo, it would be helpful if you could narrow the problem to a specific repro case. One thing that can help with this is to enable the following two settings:

```
  "python.analysis.logLevel": "Trace",
  "python.analysis.logTypeEvaluationTime": true,
```

This will cause pylance to output a bunch of extra details within the Output panel (choose the "Python Language Server" option from the combo box).

**Comment by MurtazaSKH** [comment]
Hi, Sorry for the delay.

I'm afraid its not public, also I enabled the settings, but there was nothing in the console.

The error was displayed in the code view, and the program was running fine.
![image](https://user-images.githubusercontent.com/16999455/122728098-34a12900-d291-11eb-896f-87d085daf8e9.png)

And the error disappears, once I removed a path from python.analysis.extraPaths, I added for autocomplete.
![image](https://user-images.githubusercontent.com/16999455/122729463-a332b680-d292-11eb-8a24-cce9607aa0c4.png)
Not sure why it caused problems all of a sudden, its been there for a while.

The issue is resolved, however, if you need more info, i'm happy to help.

**Comment by MurtazaSKH** [comment]
Unfortunately that was not it, it showed up again.. it disappears if i remove this path as well..
![image](https://user-images.githubusercontent.com/16999455/122734779-cf9d0180-d297-11eb-807b-79500b5f01fe.png)
however i need it for autocomplete of that module.

so instead I googled and disabled that error instead, using
`"python.analysis.errors":[ "RangeError"],`
since it seems harmless.

**Comment by jakebailey** [comment]
That extraPath is a file, so shouldn't be affecting anything; we should recognize it as a file and then not do anything with it as a path, so that would be a red herring.

`python.analysis.errors` is not a setting Pylance uses (it was for the old language server), so that won't hide the error either.

I think you may need to leave those trace options enabled until you hit the crash again.

**Comment by MurtazaSKH** [comment]
thanks for your response..
yes, suppressing it by python.analysis.errors didn't work..

the error does disappear instantly and never comes back, if I remove the file from extra path though..

and there's not been any issue (program stopped or crash etc.). The error is just sitting there on first line of code - constantly. 
I'll keep the trace options enabled.

**Comment by jakebailey** [comment]
@MurtazaSKH Have you had any change to catch this in with those trace logging options at the latest version?

I'm going to close this for now (as it's been inactive for a month), but if you catch this again or it's still happening, we can reopen.
