### ISSUE TITLE
pylance reports incorrect arguments passed to a dataclass constructor  

### ISSUE THREAD

**Issue by norbertnogacki-tomtom** [microsoft/pylance-release#1478]
<h3> Environment data </h3>

-   Language Server version: 2021.6.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.6
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

When using @dataclass backport for python3.6 I get a Pylance reportGeneralTypeIssues
![image](https://user-images.githubusercontent.com/78408447/122825320-10216d00-d2e2-11eb-87a9-3fdbf6a966a6.png)

<h3> Actual behaviour </h3>

I'd expect Pylance to recognize dataclasses and not report a problem

<h3> Logs </h3>

python log
```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
Python interpreter path: ./venv/bin/python
Starting Pylance language server.
Error 2021-06-21 23:04:47: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+dev-angrybirds.nds.tt3.com/home/local/nogacki/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+dev-angrybirds.nds.tt3.com/home/local/nogacki/.config/Code/User/settings.json')
	at _handleError (/home/local/nogacki/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:84:155538)
	at async y.readText (/home/local/nogacki/.vscode-server/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/home/local/nogacki/.vscode-server/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /home/local/nogacki/.vscode-server/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/local/nogacki/.vscode-server/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/home/local/nogacki/.vscode-server/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
> ~/projects/ndsweb3-PR/web/venv/bin/python -c "
import unittest
loader = unittest.TestLoader()
suites = loader.discover("./unit_tests", pattern="*est*.py")
print("start") #Don't remove this line
for suite in suites._tests:
    for cls in suite._tests:
        try:
            for m in cls._tests:
                print(m.id())
        except:
            pass"
cwd: ~/projects/ndsweb3-PR/web
> conda --version
> ~/projects/ndsweb3-PR/web/venv/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/ndsweb3-PR/web/scratch-none.py
cwd: ~/projects/ndsweb3-PR/web
> ~/projects/ndsweb3-PR/web/venv/bin/python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/ndsweb3-PR/web/scratch-none.py
cwd: ~/projects/ndsweb3-PR/web
> ~/projects/ndsweb3-PR/web/venv/bin/python -m mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/projects/ndsweb3-PR/web/scratch-none.py
cwd: ~/projects/ndsweb3-PR/web
> ~/projects/ndsweb3-PR/web/venv/bin/python -m mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/projects/ndsweb3-PR/web/scratch-none.py
cwd: ~/projects/ndsweb3-PR/web
##########Linting Output - flake8##########
##########Linting Output - mypy##########
Success: no issues found in 1 source file

```

Python Language Server Log
```
[Info  - 11:04:48 PM] Pylance language server 2021.6.2 (pyright dafa497d) starting
[Info  - 11:04:48 PM] Server root directory: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist
[Info  - 11:04:48 PM] No configuration file found.
[Info  - 11:04:48 PM] No pyproject.toml file found.
[Info  - 11:04:48 PM] Setting pythonPath for service "web": "/home/local/nogacki/projects/ndsweb3-PR/web/venv/bin/python"
[Warn  - 11:04:48 PM] stubPath /home/local/nogacki/projects/ndsweb3-PR/web/typings is not a valid directory.
[Info  - 11:04:48 PM] Assuming Python version 3.6
[Info  - 11:04:48 PM] Assuming Python platform Linux
Search paths for /home/local/nogacki/projects/ndsweb3-PR/web
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib
  /home/local/nogacki/projects/ndsweb3-PR/web
  /home/local/nogacki/projects/ndsweb3-PR/web/typings
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stubs/...
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/bundled/stubs
  /usr/lib64/python3.6
  /usr/lib64/python3.6/lib-dynload
  /home/local/nogacki/projects/ndsweb3-PR/web/venv/lib64/python3.6/site-packages
  /home/local/nogacki/projects/ndsweb3-PR/web/venv/lib/python3.6/site-packages
[Warn  - 11:04:48 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:04:48 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 11:04:48 PM] Searching for source files
[Info  - 11:04:49 PM] Auto-excluding /home/local/nogacki/projects/ndsweb3-PR/web/venv
[Info  - 11:04:49 PM] Found 457 source files
[Info  - 11:04:49 PM] Background analysis(1) root directory: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist
[Info  - 11:04:49 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
[FG] parsing: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (47ms)
[FG] parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 4ms] (236ms)
[FG] binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/builtins.pyi (101ms)
[FG] binding: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (1ms)
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: analyze
[BG(1)] analyzing: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py ...
[BG(1)]   parsing: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (36ms)
[BG(1)]   parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (208ms)
[BG(1)]   binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/builtins.pyi (115ms)
[BG(1)]   binding: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (1ms)
[BG(1)]   checking: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py ...
[BG(1)]     parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 3ms] (84ms)
[BG(1)]     binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing.pyi (26ms)
[BG(1)]     parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (16ms)
[BG(1)]     binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (8ms)
[BG(1)]     parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (12ms)
[BG(1)]     binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing_extensions.pyi (3ms)
[BG(1)]     parsing: /home/local/nogacki/projects/ndsweb3-PR/web/venv/lib/python3.6/site-packages/dataclasses-stubs/__init__.pyi [fs read 0ms] (6ms)
[BG(1)]     binding: /home/local/nogacki/projects/ndsweb3-PR/web/venv/lib/python3.6/site-packages/dataclasses-stubs/__init__.pyi (2ms)
[BG(1)]   checking: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (264ms)
[BG(1)] analyzing: /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (628ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (9ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 10:0 at /home/local/nogacki/projects/ndsweb3-PR/web/scratch-none.py (2ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 4ms] (74ms)
[FG] binding: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.2/dist/typeshed-fallback/stdlib/typing.pyi (15ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

<h3> Code Snippet / Additional information </h3>

```python
from dataclasses import dataclass

@dataclass
class MyStuff:
  hello: str
  world: str


print(MyStuff('h', 'w'))
# prints MyStuff(hello='hello', world='world')

```
requirements.txt
```
amqp==1.4.9
aniso8601==1.1.0
anyjson==0.3.3
astroid==1.3.6
autopep8==1.5.5
azure-core==1.7.0
azure-identity==1.3.1
azure-nspkg==3.0.2
azure-storage-blob==12.3.2
azure-storage-nspkg==3.1.0
Babel==2.3.4
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.7
beautifulsoup4==4.6.0
billiard==3.3.0.23
bleach==2.1.2
blinker==1.4
boto==2.34.0
boto3==1.9.251
botocore==1.12.251
celery==3.1.24
certifi==2017.4.17
cffi==1.13.2
chardet==3.0.4
click==8.0.1
colorama==0.4.1
coverage==5.5
crypto==1.4.1
cryptography==3.4.7
dataclasses==0.8
debugpy==1.3.0
decorator==5.0.9
defusedxml==0.5.0
django-htmlmin==0.10.0
docutils==0.12
docxtpl==0.3.9
ecdsa==0.11
enum34==1.1.6
et-xmlfile==1.0.1
extras==1.0.0
fixtures==3.0.0
flake8==3.9.2
flake8-polyfill==1.0.2
Flask==0.10.1
Flask-Mail==0.9.1
Flask-Markdown==0.3
Flask-RESTful==0.3.3
flask-restplus==0.9.0
Flask-Script==2.0.5
Flask-WTF==0.10.2
flower==0.9.1
funcsigs==0.4
future==0.18.2
futures==3.0.5
ghdiff==0.4
gitdb==0.6.4
GitPython==1.0.1
gunicorn==19.9.0
html5lib==1.0.1
humanize==0.5.1
idna==2.5
importlib-metadata==4.5.0
influxdb==4.0.0
iniherit==0.3.9
ipaddress==1.0.17
isodate==0.6.0
itsdangerous==0.24
jdcal==1.4
Jinja2==2.8
jira==1.0.10
jmespath==0.9.0
jsonschema==2.5.1
kombu==3.0.37
linecache2==1.0.0
logilab-common==1.0.1
lxml==3.8.0
lxml-stubs==0.1.1
mando==0.6.4
Markdown==2.6.5
MarkupSafe==0.23
mccabe==0.6.1
meld3==1.0.2
mock==1.3.0
mox3==0.20.0
msal==1.4.3
msal-extensions==0.1.3
msrest==0.6.18
multi-key-dict==2.0.3
mypy==0.902
mypy-extensions==0.4.3
Naked==0.1.31
numpy==1.16.5
oauthlib==2.0.2
onedrivesdk==1.1.8
openpyxl==2.5.2
ordereddict==1.1
paramiko==1.15.1
pbr==1.8.1
pep8==1.7.0
pika==1.2.0
pipdeptree==2.0.0
portalocker==1.7.1
psycopg2==2.7.3.2
py==1.10.0
pyasn1==0.4.6
pyasn1-modules==0.2.8
pycodestyle==2.7.0
pycparser==2.10
pycrypto==2.6.1
pyfakefs==3.1
pyflakes==2.3.1
pyinstrument==3.3.0
pyinstrument-cext==0.2.4
PyJWT==1.7.1
PyPDF2==1.26.0
pyral==1.3.1
python-dateutil==2.5.3
python-docx==0.8.6
python-jenkins==1.4.0
python-ldap==3.3.1
python-memcached==1.54
python-mimeparse==1.6.0
python-simplexml==0.1.5
pytz==2017.3
pyopenssl==20.0.1
PyYAML==3.12
radon==3.0.3
redis==2.10.5
requests==2.18.4
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
retry==0.9.2
s3transfer==0.2.1
shellescape==3.4.1
six==1.10.0
smmap==0.9.0
suds-py3==1.4.1.0
testtools==2.2.0
text-unidecode==1.3
toml==0.10.2
tornado==4.2
traceback2==1.4.0
typed-ast==1.4.3
types-dataclasses==0.1.5
typing==3.7.4.3
typing-extensions==3.10.0.0
unittest2==1.1.0
unittest-xml-reporting==3.0.4
urllib3==1.21.1
webencodings==0.5.1
Werkzeug==0.11.4
WTForms==2.0.1
XlsxWriter==0.9.3
yoyo-migrations==6.1.0
zipp==3.4.1
zipstream==1.1.0

```

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202163-23-june-2021
