### ISSUE TITLE
 Failed to load ONNX runtime

### ISSUE THREAD

**Issue by dzanaga** [microsoft/pylance-release#17]
## Environment data

- Language Server version: ms-python.vscode-pylance-2020.6.1   
- OS and version: Linux CentOS 7 (remote server using the Remote SSH extension)
- Python version: Anaconda Python 3.7.6

## Issue
When server is starting I observe the following error in the logs:

>[Info  - 4:57:12 PM] Pylance language server 2020.6.1 starting
[Info  - 4:57:12 PM] Server root directory: /home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 4:57:12 PM] No configuration file found.
[Info  - 4:57:12 PM] Setting pythonPath for service "ewoco": "/home/dzanaga/miniconda3/envs/eo205/bin/python"
[Info  - 4:57:12 PM] stubPath /home/dzanaga/Private/repos/ewoco/typings is not a valid directory.
[Info  - 4:57:12 PM] Assuming Python version 3.7
[Info  - 4:57:12 PM] Assuming Python platform Linux
[Info  - 4:57:12 PM] Searching for source files
[Info  - 4:57:12 PM] Found 83 source files
[Info  - 4:57:12 PM] Background analysis root directory: /home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 4:57:12 PM] Background analysis started
IntelliCode model /home/dzanaga/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.2.9/cache/15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9
[BG] analyzing: /home/dzanaga/Private/repos/ewoco/ewoco/features.py ...
[BG]   parsing: /home/dzanaga/Private/repos/ewoco/ewoco/features.py (362ms)
Loading ONNX runtime...
[Error - 4:57:13 PM] Failed to load ONNX runtime. Exception Error: Cannot open /home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/onnxruntime_binding.node: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/onnxruntime_binding.node)
    at Object.<anonymous> (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1628839)
    at Object.<anonymous> (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1628920)
    at _0x533a93 (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:141450)
    at _0x27e22c (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1627833)
    at Object.<anonymous> (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1627484)
    at _0x533a93 (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:141450)
    at Object.<anonymous> (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1622293)
    at _0x533a93 (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:141450)
    at Object.<anonymous> (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:1621603)
    at _0x533a93 (/home/dzanaga/.vscode-server/extensions/ms-python.vscode-pylance-2020.6.1/server/server.bundle.js:1:141450)

**Comment by MikhailArkhipov** [comment]
This is a known issue, specific to IntelliCode. It will be fixed soon. Basically `openmp` dependency is missing. You may try installing one though.

**Comment by dzanaga** [comment]
thanks @MikhailArkhipov, sorry, what should I try installing? `openmp`?

**Comment by MikhailArkhipov** [comment]
I believe so, yes.

**Comment by MikhailArkhipov** [comment]
See also https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found

**Comment by dzanaga** [comment]
I tried to install openmpi but didn't seem to solve the issue for me.

**Comment by MikhailArkhipov** [comment]
I'd suggest opening issue at https://github.com/MicrosoftDocs/intellicode/issues directly.
