### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1746]
## Environment data

-   Language Server version: 2021.8.3
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): Pyhton 3.9.6

## Expected behaviour

No errors

## Actual behaviour

A lot of code was marked unreachable, and an internal error occured

## Logs

```
An internal error occurred while binding file "c:\Users\Admin\ywt\2.py": TypeError: Cannot read property 'lookUpSymbol' of undefined
    at b._bindNameToScope (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:2928:32)
    at b.visitAssignmentExpression (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:842:18)
    at b.visitNode (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:136:26)
    at b.walk (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:96:37)
    at callback (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:1805:22)
    at b._setTrueFalseTargets (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:2432:9)
    at b._disableTrueFalseTargets (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:2419:14)
    at b.visitBinaryOperation (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\binder.ts:1804:18)
    at b.visitNode (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:154:26)
    at b.walk (c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.3\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:96:37)
```

## Code Snippet / Additional information

This issue occured when I was trying to reproduce an issue.
```python
from typing import Any, Callable


def my_decorator(arg: list):
    def _inside(func: Callable[..., Any]) -> Callable[..., Any]:
        return func
    return _inside


@my_decorator([triple_i for i in range(10) if (triple_i := i * 3) & 1])
def foo():
    pass
```
![屏幕截图 2021-09-01 152011](https://user-images.githubusercontent.com/62426149/131629871-02ddf977-eeaf-4129-9a4d-bf533b662f63.png)
![屏幕截图 2021-09-01 152032](https://user-images.githubusercontent.com/62426149/131629881-062fac24-bfa9-4974-bc3b-f944d3313d3f.png)

**Comment by CodeCrazy-ywt** [comment]
When I changed `[triple_i for i in range(10) if (triple_i := i * 3) & 1]` into `[]`, all the errors were gone.

**Comment by jakebailey** [comment]
Is this #1745?

**Comment by CodeCrazy-ywt** [comment]
Oh yes, these issues are similar.

**Comment by CodeCrazy-ywt** [comment]
Oh sorry, I didn't look at it carefully. 😅 Feel free to mark this issue as duplicate and close it.
