### ISSUE TITLE
Virtual Environment is not activated in the first terminal instance

### ISSUE THREAD

**Issue by mdryden** [microsoft/pylance-release#1784]
## Environment data

-   Language Server version: 2021.9.0
-   OS and version: Windows 10 / WSL 2 + Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8

## Expected behaviour

Virtual environment is activated in the terminal on startup

## Actual behaviour

Virtual environment is not activated in the terminal window which opens with VSCode.  Subsequent terminals have the virtual environment automatically activated.

## Logs

```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Error 2021-09-08 15:22:32: Custom .env is likely not pointing to a valid file [EntryIsADirectory (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' (Error: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' that is actually a directory)
	at _handleError (/home/mike/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160293)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async h.parseFile (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:408867)
	at async m._getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412149)
	at async m.getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412047)
	at async u.create (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:92999)
	at async S.create (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:94603)
	at async E.getActiveInterpreter (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:915819)
	at async f.updateDisplay (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:901640)
	at async f.refresh (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:901105)
	at async Timeout._onTimeout (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:37:30153)] {
  code: 'FileIsADirectory'
}
Python interpreter path: ./.env/bin/python
Error 2021-09-08 15:22:33: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/home/mike/.config/Code/User/settings.json')
	at _handleError (/home/mike/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async p.doesFileNeedToBeFixed (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:823850)
	at async /home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822977
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822923)
	at async p.updateTestSettings (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822550)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Error 2021-09-08 15:22:34: Custom .env is likely not pointing to a valid file [EntryIsADirectory (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' (Error: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' that is actually a directory)
	at _handleError (/home/mike/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160293)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async h.parseFile (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:408867)
	at async m._getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412149)
	at async m.getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412047)
	at async u.create (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:92999)
	at async y.getCondaVersion (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:51657)] {
  code: 'FileIsADirectory'
}
Error 2021-09-08 15:22:34: Custom .env is likely not pointing to a valid file [EntryIsADirectory (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' (Error: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/mike/src/self/110yards/api/.env' that is actually a directory)
	at _handleError (/home/mike/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160293)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async h.parseFile (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:408867)
	at async m._getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412149)
	at async m.getEnvironmentVariables (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:412047)
	at async u.create (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:92999)
	at async S.create (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:94603)
	at async E.getActiveInterpreter (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:915819)
	at async Promise.all (index 1)
	at async f (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:417712)
	at async Object.t.sendStartupTelemetry (/home/mike/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:78:418480)] {
  code: 'FileIsADirectory'
}
> conda --version
```

## Code Snippet / Additional information

![terminal](https://user-images.githubusercontent.com/5611490/132580126-1f2e8576-3228-462d-a679-6885fbd2f42a.gif)

**Comment by jakebailey** [comment]
Environment selection and activation is handled by the Python extension, not Pylance. Transferring.
