### ISSUE TITLE
"The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted." as I switch to the extension's 'Changelog' tab

### ISSUE THREAD

**Issue by darkred** [microsoft/pylance-release#2040]
### VS Code version

1.62.0

### Extension version

2021.11.1422169775

### OS type

Windows

### OS version

11 x64

### Python distribution

python.org

### Python version

3.10.0 x86 and x64, 2.7.18 x64, 

### Language server

Default

### Expected behaviour

As I updated Python extension to todays version, v2021.11.1422169775, in today's updated VSCode 1.62.0,
I switched to the 'Extensions' panel and its "Changelog" tab.

### Actual behaviour

I got the title error in statusbar:

> The Python Tools server crashed 5 times in the last 3 minutes. 
> The server will not be restarted.

I also notice high cpu usage during that time.

### Steps to reproduce

Simply open VSCode, without opening any specific folder, and open the 'Extensions' panel and its "Changelog" tab.

<details>
<summary>Here is a screen capture to show what I mean:</summary>

![](https://user-images.githubusercontent.com/723651/140404674-a7186ea2-6004-436a-8b08-929ffe237f2d.gif)
</details>

### Logs

<details>
<summary>Click to expand:</summary>

```
Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotificationcf' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
> conda info --json
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Programs\Python\Python310-32\python.exe ~\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
Starting Jedi language server.
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
Error 2021-11-04 21:16:31: Failed to start language server, Class name = r, completed in 596ms, has a falsy return value, Arg 1: undefined, Arg 2: undefined, Arg 3: {"documentSelector":[{"scheme":"file","language":"python"},{"scheme":"untitled","language":"python"},{"scheme":"vscode-notebook","language":"python"},{"scheme":"vscode-notebook-cell","language":"python"},{"scheme":"vscode-interactive-input","language":"python"}],"synchronize":{"configurationSection":"python"},"outputChannel":{"name":"Python Language Server","_channel":{}},"revealOutputChannelOn":4,"initializationOptions":{"markupKindPreferred":"markdown","completion":{"resolveEagerly":false,"disableSnippets":false},"diagnostics":{"enable":true,"didOpen":true,"didSave":true,"didChange":true},"workspace":{"extraPaths":[],"symbols":{"maxSymbols":0}}},"middleware":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"serverVersion":"0.34.6","lastCaptured":{},"nextWindow":0,"eventCount":0,"workspace":{},"connectedPromise":{"scope":null,"_resolved":false,"_rejected":false,"_promise":{}},"eventName":"JEDI_LANGUAGE_SERVER.REQUEST","notebookAddon":{}},"connectionOptions":{"cancellationStrategy":{"_sender":{"folderName":"cdbc37254a7d33e3df0b296c6f345e7384f67ec951"}}}}, Return Value: undefined Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: Starting language server, Class name = r, completed in 597ms, has a falsy return value, , Return Value: undefined Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: Failed to start language server, Class name = r, completed in 601ms, has a falsy return value, Arg 1: undefined, Arg 2: undefined, Return Value: undefined Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: Failed to activate language server, Class name = a, completed in 602ms, has a falsy return value, Arg 1: undefined, Arg 2: undefined, Return Value: undefined Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: Failed to activate a workspace, Class name = m, completed in 1312ms, has a falsy return value, Arg 1: undefined, Return Value: undefined Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: Failure during activation. Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Error 2021-11-04 21:16:31: sendStartupTelemetry() failed. Error: Connection to server got closed. Server will not be restarted.
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:146083)
    at S.handleConnectionClosed (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:17:10273)
    at t (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:143862)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at X (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:230363)
    at invoke (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:264940)
    at o.fire (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:9:265701)
    at g.fireClose (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:220432)
    at Socket.<anonymous> (c:\Users\Kostas\.vscode\extensions\ms-python.python-2021.11.1422169775\out\client\extension.js:52:222012)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
> ~\AppData\Local\Programs\Python\Python38-32\python.exe -c "import sys;print(sys.executable)"
```
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakebailey** [comment]
@karthiknadig 

The logs here say:

```
Starting Jedi language server.
```

So, this isn't a Pylance problem.
