### ISSUE TITLE
Type hints cause syntax high lighting trouble.

### ISSUE THREAD

**Issue by mcmxl22** [microsoft/pylance-release#2173]
### VS Code version

v1.63.0

### Extension version

v2021.12.1559732655

### OS type

Windows

### OS version

Winows 11 v10.0.22000

### Python distribution

python.org

### Python version

3.10.0 64-bit

### Language server

Default

### Expected behaviour

![Screenshot_1](https://user-images.githubusercontent.com/6622640/145918838-c680227f-212b-4b88-b964-1869dcfb0a13.png)

### Actual behaviour

![Screenshot_2](https://user-images.githubusercontent.com/6622640/145918869-e80710ac-d525-4ff8-a70f-44f52ecd0c01.png)

### Steps to reproduce

```python
def func() -> str:
    """doc string"""
    f = 'foo'
    return f

def main():
    pass
```

### Logs

[2021-12-14 12:10:15.333] [exthost] [info] Extension host with pid 38688 started
[2021-12-14 12:10:15.333] [exthost] [info] Skipping acquiring lock for c:\Users\mcmxl\AppData\Roaming\Code\User\workspaceStorage\8ebf3e3a70b9a93ce82f2566bc087943.
[2021-12-14 12:10:15.418] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-12-14 12:10:15.449] [exthost] [info] ExtensionService#_doActivateExtension batisteo.vscode-django, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.461] [exthost] [info] ExtensionService#_doActivateExtension KevinRose.vsc-python-indent, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.465] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.vscode-pylance
[2021-12-14 12:10:15.608] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.836] [exthost] [info] ExtensionService#_doActivateExtension njpwerner.autodocstring, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.861] [exthost] [info] ExtensionService#_doActivateExtension tht13.python, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.881] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:python'
[2021-12-14 12:10:15.981] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2021-12-14 12:10:15.984] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2021-12-14 12:10:15.989] [exthost] [info] ExtensionService#_doActivateExtension TabNine.tabnine-vscode, startup: true, activationEvent: '*'
[2021-12-14 12:10:16.676] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-12-14 12:10:16.682] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-12-14 12:10:16.740] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-12-14 12:10:16.799] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2021-12-14 12:10:16.895] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2021-12-14 12:10:18.665] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2021-12-14 12:10:22.593] [exthost] [info] Eager extensions activated
[2021-12-14 12:10:22.604] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-12-14 12:10:22.678] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2021-12-14 12:10:22.701] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2021-12-14 12:10:22.712] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
[2021-12-14 12:10:25.123] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'api', root cause: ms-python.python
[2021-12-14 12:13:49.503] [exthost] [error] [ms-python.python] provider FAILED
[2021-12-14 12:13:49.507] [exthost] [error] Canceled: Canceled
	at S.makeCancelError (c:\Users\mcmxl\.vscode\extensions\ms-python.python-2021.12.1559732655\out\client\extension.js:24:159824)
	at S.handleFailedRequest (c:\Users\mcmxl\.vscode\extensions\ms-python.python-2021.12.1559732655\out\client\extension.js:24:159675)
	at c:\Users\mcmxl\.vscode\extensions\ms-python.python-2021.12.1559732655\out\client\extension.js:24:120017
	at async o.provideHover (c:\Users\mcmxl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:90908)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judej** [comment]
We were not able to repro this. Could you please send us the logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by mcmxl22** [comment]
I have added the logs.

**Comment by mcmxl22** [comment]
Disabling the 'Python for VSCode' extension as discussed here, microsoft/vscode-python#14367 (comment), solved the problem
![Screenshot_3](https://user-images.githubusercontent.com/6622640/146065978-a3bc6a24-e4ea-4571-b62a-7a73e33bf614.png)
.

**Comment by bschnurr** [comment]
from the guide. "Select "View: Toggle Output" from the command palette (Ctrl+Shift+P on Windows/Linux, Command+Shift+P on macOS), then select "Python Language Server" in the dropdown on the right. Look for the line Pylance Language Server version X in the console."

**Comment by mcmxl22** [comment]
[Info  - 12:37:04 PM] Pylance language server 2021.12.2 (pyright 211ebe44)

**Comment by bschnurr** [comment]
try creating a `pyrightconfig.json` in your workspace and add

```
{
     "verboseOutput": true
}
```

maybe related https://github.com/microsoft/pylance-release/issues/1368

**Comment by mcmxl22** [comment]
I am not having CPU trouble but here are more logs.

[Info  - 1:00:49 PM] Pylance language server 2021.12.2 (pyright 211ebe44) starting
[Info  - 1:00:49 PM] Server root directory: c:\Users\mcmxl\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist
[Info  - 1:00:49 PM] Setting pythonPath for service "Inventory": "C:\Users\mcmxl\AppData\Local\Programs\Python\Python310\python.exe"
[Info  - 1:00:49 PM] Loading configuration file at c:\Users\mcmxl\mystuff\Inventory\pyrightconfig.json
[Info  - 1:00:49 PM] Assuming Python version 3.10
[Info  - 1:00:49 PM] Assuming Python platform Windows
[Info  - 1:00:49 PM] No include entries specified; assuming c:\Users\mcmxl\mystuff\Inventory
[Info  - 1:00:49 PM] Auto-excluding **/node_modules
[Info  - 1:00:49 PM] Auto-excluding **/__pycache__
[Info  - 1:00:49 PM] Auto-excluding .git
[Warn  - 1:00:49 PM] stubPath c:\Users\mcmxl\mystuff\Inventory\typings is not a valid directory.
[Info  - 1:00:49 PM] Search paths for c:\Users\mcmxl\mystuff\Inventory
[Info  - 1:00:49 PM]   c:\Users\mcmxl\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist\typeshed-fallback\stdlib
[Info  - 1:00:49 PM]   c:\Users\mcmxl\mystuff\Inventory
[Info  - 1:00:49 PM]   c:\Users\mcmxl\mystuff\Inventory\typings
[Info  - 1:00:49 PM]   c:\Users\mcmxl\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist\typeshed-fallback\stubs\...
[Info  - 1:00:49 PM]   c:\Users\mcmxl\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist\bundled\stubs
[Info  - 1:00:49 PM]   c:\Users\mcmxl\AppData\Local\Programs\Python\Python310\DLLs
[Info  - 1:00:49 PM]   c:\Users\mcmxl\AppData\Local\Programs\Python\Python310\Lib
[Info  - 1:00:49 PM]   c:\Users\mcmxl\AppData\Local\Programs\Python\Python310
[Info  - 1:00:49 PM]   c:\Users\mcmxl\AppData\Local\Programs\Python\Python310\Lib\site-packages
[Info  - 1:00:49 PM] Adding fs watcher for library directories:
 C:\Users\mcmxl\AppData\Local\Programs\Python\Python310\DLLs
C:\Users\mcmxl\AppData\Local\Programs\Python\Python310\lib
C:\Users\mcmxl\AppData\Local\Programs\Python\Python310
C:\Users\mcmxl\AppData\Local\Programs\Python\Python310\lib\site-packages
[Info  - 1:00:49 PM] Adding fs watcher for directories:
 c:\Users\mcmxl\mystuff\Inventory
[Info  - 1:00:49 PM] Searching for source files
[Info  - 1:00:49 PM] Auto-excluding c:\Users\mcmxl\mystuff\Inventory\inventory
[Info  - 1:00:49 PM] Found 5 source files
[Info  - 1:00:49 PM] Background analysis(1) root directory: c:\Users\mcmxl\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist
[Info  - 1:00:49 PM] Background analysis(1) started

**Comment by bschnurr** [comment]
there should be more after `[Info - 1:00:49 PM] Background analysis(1) started`

looking for `Background analysis message: getSemanticTokens full`

**Comment by mcmxl22** [comment]
This is all I could find.

[Info  - 1:14:13 PM] Background analysis(1) started
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'collections\__pycache__'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'Lib\collections\__pycache__'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'ctypes\__pycache__'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'Lib\ctypes\__pycache__'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'ctypes\macholib'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'ctypes\test'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'Lib\ctypes\macholib'}'
[Info  - 1:14:13 PM] LibraryFile: Received fs event 'change' for path 'Lib\ctypes\test'}'

**Comment by mcmxl22** [comment]
Adding "python.analysis.logLevel": "Trace" makes no difference in the logs.
And I get 'Duplicate id declaration: '#/properties/pythonPlatform'' on my pyrightconfig.json.

**Comment by heejaechang** [comment]
the log shows no message from trace though. is it in the settings.json?

**Comment by IceTDrinker** [comment]
> Disabling the 'Python for VSCode' extension as discussed here, [microsoft/vscode-python#14367](https://github.com/microsoft/vscode-python/issues/14367) (comment), solved the problem ![Screenshot_3](https://user-images.githubusercontent.com/6622640/146065978-a3bc6a24-e4ea-4571-b62a-7a73e33bf614.png) .

Apparently it was solved by the author disabling the extension. On my end I don't know why I had some coloring issue but this morning it seems fine for whatever reason...
