### ISSUE TITLE
Unable to update to 2021.12.2

### ISSUE THREAD

**Issue by windless0530** [microsoft/pylance-release#2186]
Every time I try to update, the following error occurs.

[2021-12-21 15:54:01.866] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at $.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:205704)","    at async $.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:204229)"]
[2021-12-21 15:54:01.894] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at $.downloadInstallableExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:205704)
    at async $.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:204229)

Even if I try to manually download, it's the same.
All other extensions are working just fine.

Version: 1.63.1
提交: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

**Comment by judej** [comment]
Are you still seeing this problem? Looks like a corrupt zip file. Surprised that manually downloading it did not fix it. Please let us know if you still seeing this.

**Comment by judej** [comment]
closing stale issue
