### ISSUE TITLE
Reporting Missing imports 

### ISSUE THREAD

**Issue by ishita199615** [microsoft/pylance-release#2202]
reportMissingModuleSource

pylance is not supporting the basic imports

<img width="1342" alt="Screen Shot 2021-12-31 at 2 09 10 PM" src="https://user-images.githubusercontent.com/49127145/147837925-680aee2c-7e0e-4274-af40-2fe860c063e1.png">

**Comment by erictraut** [comment]
This message means that you don't have django installed in the Python environment that is currently selected. If you look in the bottom left corner of the window, you should see which environment is selected. Make sure that matches what you expect.

**Comment by LuciferSacred** [comment]
Hello , if you seeing this.. this is the same as me I tried to reportMissingImports it is not supported in pylance in flask.. and I looked at the bottom left corner of the window, what do I should do with it? Do I need to make environment to my python file? then trying again if it still works to import the flask.
![Error](https://user-images.githubusercontent.com/79697171/147875115-f5f3ff52-9fed-4404-aed6-f9d4f2cde11c.PNG)

**Comment by bschnurr** [comment]
I suggest using "open folder" and refer to this guide on selecting your environment. https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

**Comment by ishita199615** [comment]
> This message means that you don't have django installed in the Python environment that is currently selected. If you look in the bottom left corner of the window, you should see which environment is selected. Make sure that matches what you expect.

Thanks! I was able to resolve it.

**Comment by Rabiawaheed786** [comment]
This is my terminal error  module not found plz resolve
Microsoft Windows [Version 10.0.26100.4061]
(c) Microsoft Corporation. All rights reserved.

(practice-agents) C:\Users\ehtis\OneDrive\Desktop\practice-agents>uv run chainlit run main.py -w
2025-05-24 18:45:54 - Loaded .env file
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Scripts\chainlit.exe\__main__.py", line 7, in <module>   
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1442, in __call__ 
    return self.main(*args, **kwargs)   
           ^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1363, in main     
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1830, in invoke   
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1226, in invoke   
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 794, in invoke    
    return callback(*args, **kwargs)    
           ^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\cli\__init__.py", line 214, in chainlit_run
    run_chainlit(target)
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\cli\__init__.py", line 78, in run_chainlit
    load_module(config.run.module_name) 
  File "C:\Users\ehtis\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\config.py", line 491, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module       
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed  
dule>
dule>
    from agents import Agent, OpenAIChatCompletionsModel ,AsyncOpenAI,Runner, set_tracing_disabled
ModuleNotFoundError: No module named 'agents'

(practice-agents) C:\Users\ehtis\OneDrive\Desktop\practice-agents>

**Comment by Rabiawaheed786** [comment]
plz give ans only five mint

**Comment by rchiodo** [comment]
@Rabiawaheed786 your error is on the terminal and has nothing to do with Pylance. You might try searching for '[ModuleNotFoundError](https://pytutorial.com/how-to-solve-modulenotfounderror-no-module-named-in-python/)' in Python documentation. You likely need to install a package.

**Comment by RudraneelDutta8x** [comment]
how to save it, i have installed but it is not working

**Comment by Rabiawaheed786** [comment]
Ok jazakallah

**Comment by daedalus345** [comment]
Hello i have a problem  with import pygame how to fix it

**Comment by debonte** [comment]
@daedalus345, please open a new issue and include details on how to reproduce the issue you are seeing including a code sample and required packages (with package versions).

**Comment by palak770** [comment]
![Image](https://github.com/user-attachments/assets/9a6a477d-10f6-40e1-a846-6da657d8e1c3)
I'm not able to reslove this

**Comment by abhirampolnati** [comment]
![Image](https://github.com/user-attachments/assets/cd0efdf5-fe33-499a-9943-492f8e028cc5)

**Comment by Rabiawaheed786** [comment]
It works!

**Comment by palak770** [comment]
No, it's throwing an error but when I changed the interpreter to local then the code got executed successfully. Is it a good approach or it will later throw me any other problem

**Comment by prey801** [comment]
change the interpreter to Global if your using an environment

**Comment by mipaabhishek** [comment]
<img width="660" height="105" alt="Image" src="https://github.com/user-attachments/assets/15ec5e53-97a0-4d5e-a7bb-44d67c14c2f0" />

**Comment by prey801** [comment]
Try to first import the entire module and see if it runs > <img width="660" height="105" alt="Image" src="https://github.com/user-attachments/assets/15ec5e53-97a0-4d5e-a7bb-44d67c14c2f0" />

**Comment by Tonylafleur** [comment]
Hi
Please i'm working in a website flask project and i faced this issue. Can somebody help me?

<img width="821" height="129" alt="Image" src="https://github.com/user-attachments/assets/8b51612f-977d-4c1c-8465-4110c4184bab" />

**Comment by rchiodo** [comment]
@Tonylafleur your issue is likely one of:

- You don't have the correct interpreter [selected in VS code](https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters). VS code doesn't necessarily know which python environment you're using so you have to tell it. 

or

- You have to install the flask-mail module into the environment that is current selected.

**Comment by Tonylafleur** [comment]
This is the screenshoot of what VS Code proposed me about my interpreter

<img width="385" height="104" alt="Image" src="https://github.com/user-attachments/assets/7d4ecfc1-36da-4b2a-bdd3-d6acff1f9dc9" />

**Comment by rchiodo** [comment]
You should pick the one that you installed 'flask-mail' into. If you have not installed it anywhere yet, it's better to install it into the venv than your global environment.

**Comment by rchiodo** [comment]
Python has more information on virtual environments here:
https://docs.python.org/3/tutorial/venv.html

**Comment by dataanlytic-source** [comment]
import panda as pd
reportMissingImports

**Comment by rchiodo** [comment]
@dataanlytic-source I'd have the same advice as I gave above. Your problem is likely you don't have an interpreter selected with Pandas installed into it.

**Comment by shelby360** [comment]
report missing flask import

**Comment by abdulazizmamatov023-web** [comment]
<img width="1116" height="354" alt="Image" src="https://github.com/user-attachments/assets/7f2a01a6-033c-4f14-badd-818383a3dcc1" />

**Comment by abdulazizmamatov023-web** [comment]
buni nima qlish kerak

**Comment by dawood197659** [comment]
hi

**Comment by dawood197659** [comment]
hi
