### ISSUE TITLE
Recursive type hint reference not understood in some new files, while working in others

### ISSUE THREAD

**Issue by YSaxon** [microsoft/pylance-release#2258]
<h3> Environment data </h3>

-   Language Server version: 2022.1.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.1
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

A class should be able to reference itself as a type, eg. to annotate passing in a member of the same type in a method.

<h3> Actual behaviour </h3>

In my original python file, the self reference is dealt with fine, but in a new file I create, it fails.

<h3> Logs </h3>

Python Language Server Log

Output when pasting TestClass into the file where it works
```
[FG] parsing: /Users/[dependency]/__init__.py [fs read 0ms] (5ms)
[FG] binding: /Users/[dependency]/__init__.py (0ms)
[FG] parsing: /Users/[dependency]/models/blocks/__init__.py [fs read 1ms] (8ms)
[FG] binding: /Users/[dependency]/models/blocks/__init__.py (0ms)
[FG] parsing: /Users/[dependency]/models/views/__init__.py [fs read 1ms] (15ms)
[FG] binding: /Users/[dependency]/models/views/__init__.py (1ms)
[FG] parsing: /Users/[dependency]/web/__init__.py [fs read 2ms] (2ms)
[FG] binding: /Users/[dependency]/web/__init__.py (0ms)
[FG] parsing: /Users/[dependency]/web/client.py [fs read 1ms] (171ms)
[FG] binding: /Users/[dependency]/web/client.py (11ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/[file_where_it_works] (48ms)
[FG] binding: /Users/[file_where_it_works] (18ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/[file_where_it_works] ...
[BG(1)]   parsing: /Users/[file_where_it_works] (286ms)
[BG(1)]   binding: /Users/[file_where_it_works] (54ms)
[BG(1)]   checking: /Users/[file_where_it_works] (1286ms)
[BG(1)] analyzing: /Users/[file_where_it_works] (1630ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1642451535601 at /Users/[file_where_it_works] (6265ms)
[Info  - 3:32:48 PM] [BG(1)] Long operation: getSemanticTokens delta previousResultId:1642451535601 at /Users/[file_where_it_works] (6265ms)
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: analyze
[BG(1)] analyzing: /Users/[file_where_it_works] ...
[BG(1)]   checking: /Users/[file_where_it_works] (372ms)
[BG(1)] analyzing: /Users/[file_where_it_works] (372ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
[BG(1)] analyzing: /Users/[other_file].py ...
[BG(1)]   checking: /Users/[other_file].py (134ms)
[BG(1)] analyzing: /Users/[other_file].py (135ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange

```

Output when pasting it into a new file where it doesn't work
```
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/[redacted]/testselfreference.py (1ms)
[FG] binding: /Users/[redacted]/testselfreference.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1642451877421 at /Users/[redacted]/testselfreference.py ...
[BG(1)]   parsing: /Users/[redacted]/testselfreference.py (0ms)
[BG(1)]   binding: /Users/[redacted]/testselfreference.py (1ms)
[BG(1)] getSemanticTokens delta previousResultId:1642451877421 at /Users/[redacted]/testselfreference.py (5ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/[redacted]/testselfreference.py ...
[BG(1)]   checking: /Users/[redacted]/testselfreference.py (1ms)
[BG(1)] analyzing: /Users/[redacted]/testselfreference.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: markFilesDirty
Background analysis message: analyze
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

<h3> Code Snippet / Additional information </h3>

```python
class TestClass:
    def __init__(self,
                 other:TestClass) -> None:
        pass
```
![Screen Shot 2022-01-17 at 3 25 28 PM](https://user-images.githubusercontent.com/11711101/149834580-b875ebf0-55bc-4a44-9a21-c26a58dadf88.png)

**Comment by erictraut** [comment]
If you run your example in the Python interpreter, you'll receive a runtime exception:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    class TestClass:
  File "test.py", line 2, in TestClass
    def __init__(self, other: TestClass) -> None:
NameError: name 'TestClass' is not defined
```
Pylance is warning you about this exception.

Is it possible that some of your source files include `from __future__ import annotations`? This will cause the type annotation to be deferred, so no runtime exception will occur, and pylance will correspondingly not report an error in this case.

**Comment by YSaxon** [comment]
Thanks so much, you are absolutely right!

**Comment by YSaxon** [comment]
I wonder if it would be worthwhile for pylance to briefly explain this (or otherwise link to such an explanation) in the error message in such cases (assuming such a thing is technically feasible)..?
