### ISSUE TITLE
Pylance extension installation failed vscode

### ISSUE THREAD

**Issue by sarankumar88** [microsoft/pylance-release#2280]
Failed to install the pylance on vscode running from windows 10 os.

## Environment data

Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

-   OS and version: Windows 10 Enterprise OS Build: 19042.1466 , Windows Feature Experience Pack 120.2212.3920.0
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8.8 , conda 4.10.1

## Expected behaviour

Installation of pylance extension should be successful.

## Actual behaviour

Failing to install through the marketplace as well  as via manually using file "ms-python.vscode-pylance-2022.1.3.vsix"

## Logs

`[2022-01-24 16:18:40.289] [renderer1] [error] ["Error: Corrupt ZIP: end of central directory record signature not found,XHR failed","    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:19042","    at Array.reduce (<anonymous>)","    at E (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:19028)","    at A.joinAllSettled (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:10109)","    at async A.installExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:7819)","    at async A.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)"]
[2022-01-24 16:18:40.322] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found,XHR failed: Error: Corrupt ZIP: end of central directory record signature not found,XHR failed
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:19042
    at Array.reduce (<anonymous>)
    at E (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:19028)
    at A.joinAllSettled (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:10109)
    at async A.installExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:7819)
    at async A.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)`

## Tried methods or config changes..

Validated Proxy settings.
Tried installing using admin user.
Manual installation also fails. (ms-python.vscode-pylance-2022.1.3.vsix)

**Comment by debonte** [comment]
It looks like your install got corrupted somehow. Can you try opening the VS Code extensions folder via the "Extensions: Open Extensions Folder" command and deleting the ms-python.vscode-pylance-* folder? And then reinstall should work.

**Comment by sarankumar88** [comment]
Hi @debonte 
I have tried the above mentioned recommendation, but it didn't worked for me. I have tried installing pylance in a fresh machine today(MAC) facing the same error in that PC too. I am installing the extension in a company controlled PC let me know the configurations need to validate in such cases.

**Comment by judej** [comment]
Sorry to hear you are seeing these errors. It appears that there is a corrupted file. Could you please do the following:

1. Uninstall Pylance from VC Code.
2. download the latest VSIX from https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance and download the latest version from the "Version history" tab? (current version is 2022.2.0.
3. Validate that the file is not corrupted by validating that the checksum is 985bf30764a5aa9a15ff0191bb21bb703d6edee9
You can get the check sum with following command `certutil -hashfile .\ms-python.vscode-pylance-2022.2.0.vsix`
4. Install the downloaded VSIX by using the "Install from VSIX..." command on the ellipsis on the first line of the extensions tab

Please let me know if that works for you.

**Comment by sarankumar88** [comment]
@judej
I tried the same. but still it fails. The file hash is matching though.
$ certutil -hashfile ms-python.vscode-pylance-2022.2.0.vsix
SHA1 hash of ms-python.vscode-pylance-2022.2.0.vsix:
985bf30764a5aa9a15ff0191bb21bb703d6edee9
CertUtil: -hashfile command completed successfully.

Error:
[2022-02-09 15:02:44.110] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at $.downloadInstallableExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:244:227199)
    at async $.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:244:225611)

**Comment by judej** [comment]
Saran, unfortunately, we have not been able to reproduce this problem. If this is still a problem, please download the vsix again, making sure that you have the latest version, and try again. Please reopen this is still a problem.
