### ISSUE TITLE
installing and running matplotlib on OSX (Python 11)

### ISSUE THREAD

**Issue by machinelearning7** [microsoft/pylance-release#2374]
Trying to learn how to install and run matplotlib in OSX from Terminal using VSC to run code but tried PyCharm as well, no difference getting following error:

#code:

import matplotlib.pyplot as plt

squares = [1, 4, 9, 16, 25]

fig, ax = plt.subplots()
ax.plot(squares)

plt.show()

#error:
/Users/user/PycharmProjects/pythonProject/venv/bin/python /Users/user/PycharmProjects/pythonProject/mpl_squares.py
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pythonProject/mpl_squares.py", line 1, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot

Process finished with exit code 1

 #Final part of matplotlib install with error message:

BUILDING MATPLOTLIB
            python: yes [3.11.0a5 (v3.11.0a5:c4e4b91557, Feb  3 2022, 14:54:01) [Clang
                        13.0.0 (clang-1300.0.29.30)]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

I'm a newbie and not really sure what I'm doing wrong. I'm following instructions on p. 306 of Python Crash Course (Eric Matthew) but there are no troubleshooting notes on matplotlib installation. Couldn't find any decent answer online? I have Py 2.7, 3.10, and 3.11 installed.  I'd appreciate some help. 
See attached for full error install file,

**Comment by luabud** [comment]
Hi @machinelearning7! At first glance it seems that the error you're seeing is because matplotlib doesn't support Python 3.11 yet. I would recommend filing an issue at their repo: https://github.com/matplotlib/matplotlib 

Otherwise you could try using Python 3.10 instead.

**Comment by machinelearning7** [comment]
Hi luabud and thank you. I filed the issue but I may just try to uninstalll python 3.11 and use 3.10 instead as you suggested. Hopefully matplotlib will get the issue resolved in a timely manner. Thanks again for your precious help.

**Comment by machinelearning7** [comment]
I'm using 3.10 still not working. Please see below.

Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/tmp8zb7db9u
       cwd: /private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c
  Complete output (175 lines):
  Running from numpy source directory.
  /private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/tools/cythonize.py:63: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Processing numpy/random/_bounded_integers.pyx.in
  Processing numpy/random/_sfc64.pyx
  Processing numpy/random/_mt19937.pyx
  Processing numpy/random/bit_generator.pyx
  Processing numpy/random/mtrand.pyx
  Processing numpy/random/_generator.pyx
  Processing numpy/random/_pcg64.pyx
  Processing numpy/random/_common.pyx
  Cythonizing sources
  INFO: blas_opt_info:
  INFO: blas_armpl_info:
  INFO: customize UnixCCompiler
  INFO:   libraries armpl_lp64_mp not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blas_mkl_info:
  INFO:   libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blis_info:
  INFO:   libraries blis not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_info:
  INFO:   libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: accelerate_info:
  INFO:   libraries accelerate not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO: Library accelerate was not found. Ignoring
  INFO:   libraries veclib not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO: Library veclib was not found. Ignoring
  INFO:   FOUND:
  INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
  INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
  INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  INFO:
  INFO:   FOUND:
  INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
  INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
  INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  INFO:
  non-existing path in 'numpy/distutils': 'site.cfg'
  INFO: lapack_opt_info:
  INFO: lapack_armpl_info:
  INFO:   libraries armpl_lp64_mp not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: lapack_mkl_info:
  INFO:   libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_lapack_info:
  INFO:   libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_clapack_info:
  INFO:   libraries openblas,lapack not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: flame_info:
  INFO:   libraries flame not found in ['/Library/Frameworks/Python.framework/Versions/3.10/lib', '/usr/lib', '/opt/local/lib']
  INFO:   NOT AVAILABLE
  INFO:
  INFO:   FOUND:
  INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
  INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
  INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  INFO:
  Warning: attempted relative import with no known parent package
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  INFO: build_src
  INFO: building py_modules sources
  creating build
  creating build/src.macosx-10.9-universal2-3.10
  creating build/src.macosx-10.9-universal2-3.10/numpy
  creating build/src.macosx-10.9-universal2-3.10/numpy/distutils
  INFO: building library "npymath" sources
  WARN: Could not locate executable gfortran
  WARN: Could not locate executable f95
  WARN: Could not locate executable nagfor
  WARN: Could not locate executable f90
  WARN: Could not locate executable f77
  WARN: Could not locate executable xlf90
  WARN: Could not locate executable xlf
  WARN: Could not locate executable ifort
  WARN: Could not locate executable ifc
  WARN: Could not locate executable g77
  WARN: Could not locate executable g95
  WARN: Could not locate executable pgfortran
  WARN: don't know how to compile Fortran code on platform 'posix'
  creating build/src.macosx-10.9-universal2-3.10/numpy/core
  creating build/src.macosx-10.9-universal2-3.10/numpy/core/src
  creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath
  INFO: conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_internal.h
  INFO:   adding 'build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath' to include_dirs.
  INFO: conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/ieee754.c
  INFO: conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_complex.c
  INFO: None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_internal.h']
  INFO: building library "npyrandom" sources
  INFO: building extension "numpy.core._multiarray_tests" sources
  creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray
  INFO: conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/_multiarray_tests.c
  INFO: building extension "numpy.core._multiarray_umath" sources
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 461, in <module>
      setup_package()
    File "setup.py", line 453, in setup_package
      setup(**metadata)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-build-env-z0qnl3om/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/command/build.py", line 61, in run
      old_build.run(self)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/command/build_src.py", line 161, in build_sources
      self.build_extension_sources(ext)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
      sources = self.generate_sources(sources, ext)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/distutils/command/build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/core/setup.py", line 456, in generate_config_h
      moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/core/setup.py", line 50, in check_types
      out = check_types(*a, **kw)
    File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-pf6yc2ar/numpy_e70678bc747b48cc8586ba59cbb3fd2c/numpy/core/setup.py", line 311, in check_types
      raise SystemError(
  SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
  ----------------------------------------
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.

**Comment by luabud** [comment]
@machinelearning7  it _might_ be worth upgrading pip and trying it again, but would you mind sharing what is the command you're using to install matplotlib?

to upgrade pip you would run the command suggested by the warning message you got:
```
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip
```

**Comment by machinelearning7** [comment]
Thank you. The command is:   pip3 install matplotlib

I upgraded pip and this is the error I'm getting now:

  File "/private/var/folders/tj/bswjbhsn6j39f632vdqnkl680000gn/T/pip-install-4lw1w773/numpy_09aa465689d54e149377b5fe322fd120/numpy/core/setup.py", line 311, in check_types
          raise SystemError(
      **SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.**
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by machinelearning7** [comment]
Update: uninstalled python 3.10 installed 3.9 and it's now FINALLY working!
