### ISSUE TITLE
Missing type information for arcpy, arcgispro-py3

### ISSUE THREAD

**Issue by vovchykbratyk** [microsoft/pylance-release#240]
## Environment data

-   VS Code version: 1.48.0-insider
-   Extension version (available under the Extensions sidebar): 2020.9.100875-dev
-   OS and version: Windows 10 x64 19042.450
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: arcpy (ArcGIS Pro 2.6)
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance (tested with Jedi too)

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

The modules I require are split into standard and non-standard locations.  Code completion for standard locations works fine: for example:

```
import arcpy
if arcpy.Exists(dataset)`
```
completes correctly.

However there is a pointer module called `da` at a _nonstandard_ location, which calls the file `_arcgisscripting.pyd` under the _standard_ site-packages location.  When I add both resources specifically into `settings.json`:

```
[""C:\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy",
"C:\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\sa",  # This is a set of other nonstandard modules I need to get working as well
"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\arcgisscripting\\_arcgisscripting.pyd",
"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\arcgisscripting"]
```

...I would expect for the classes and methods contained in the .pyd file to be available to VSC code completion.

## Actual behaviour

The classes and methods of `_arcgisscripting.pyd` are not auto-completed:

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. I guess I typed up all the steps as part of "Expected Behavior."  I'm not sure a gif is helpful, as it would simply show anything starting with

`arcpy.da.` failing to autocomplete (e.g., `arcpy.da.SearchCursor()`, `arcpy.da.InsertCursor()`, etc).

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> pyenv root
> python3.7 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\python.exe c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-08-13 15:04:19: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\user\PycharmProjects\geoindexer\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\user\PycharmProjects\geoindexer\.vscode\settings.json')
	at _handleError (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:672:249)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\out\client\extension.js:1:502786)
	at async p.doesFileNeedToBeFixed (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\out\client\extension.js:48:952696)
	at async c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\out\client\extension.js:48:951823
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\out\client\extension.js:48:951769)
	at async p.updateTestSettings (c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\out\client\extension.js:48:951396)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> conda env list
Starting Pylance language server.
Python interpreter path: C:\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\python.exe
Error 2020-08-13 15:04:19: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
> conda env list
Error 2020-08-13 15:04:19: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
Error 2020-08-13 15:04:19: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-08-13 15:04:19: Detection of Python Interpreter for Command python and args  failed as file  does not exist
Error 2020-08-13 15:04:19: Failed to get interpreter information for 'C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\user\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py" "c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-08-13 15:04:19: Failed to get interpreter information for 'C:\Users\user\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\user\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py" "c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\interpreterInfo.py"'
}
> conda --version
Error 2020-08-13 15:04:24: getActivatedEnvironmentVariables [Error: Command failed: C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py"
}
Error 2020-08-13 15:04:24: getActivatedEnvironmentVariables, Class name = E, completed in 5157ms, has a falsy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.10-final","major":3,"minor":6,"patch":10,"prerelease":["final"],"build":[],"version":"3.6.10-final"},"sysPrefix":"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3","fileHash":"2a467c346aeaf2a8b2d985dece96171fecc7b266fe417ce79b35b263668245d49282885c314a8114f07f53507f7a43140fcfa6a746453db011dcdbf0c8a5dc6a","type":"Unknown","displayName":"Python 3.6.10 64-bit"}, Arg 3: true [Error: Command failed: C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py"
}
Error 2020-08-13 15:04:24: getActivatedEnvironmentVariables [Error: Command failed: C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py"
}
Error 2020-08-13 15:04:24: getActivatedEnvironmentVariables, Class name = E, completed in 5184ms, has a falsy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.6.10-final","major":3,"minor":6,"patch":10,"prerelease":["final"],"build":[],"version":"3.6.10-final"},"sysPrefix":"C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3","fileHash":"2a467c346aeaf2a8b2d985dece96171fecc7b266fe417ce79b35b263668245d49282885c314a8114f07f53507f7a43140fcfa6a746453db011dcdbf0c8a5dc6a","type":"Unknown","displayName":"Python 3.6.10 64-bit"}, Arg 3: true [Error: Command failed: C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py"
}
Error 2020-08-13 15:04:24: getActivatedEnvironmentVariables [Error: Command failed: C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\user\.vscode-insiders\extensions\ms-python.python-2020.9.100875-dev\pythonFiles\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\user\\.vscode-insiders\\extensions\\ms-python.python-2020.9.100875-dev\\pythonFiles\\pyvsc-run-isolated.py c:/Users/ericc/.vscode-insiders/extensions/ms-python.python-2020.9.100875-dev/pythonFiles/printEnvVariables.py"
}
```

</p>
</details>

**Comment by erictraut** [comment]
Pylance uses type stubs and Python code for type information. It does not extract type information from native binaries like ".pyd" files. You will need a corresponding type stub file if you want type completion information for that submodule. Many library providers have recently started to ship type stubs with their packages. Please check the latest version. If there are no type stubs provided, request it from the library author.

**Comment by vovchykbratyk** [comment]
> 
> 
> Pylance uses type stubs and Python code for type information. It does not extract type information from native binaries like ".pyd" files. You will need a corresponding type stub file if you want type completion information for that submodule. Many library providers have recently started to ship type stubs with their packages. Please check the latest version. If there are no type stubs provided, request it from the library author.

Thanks! This is the first straightforward, authoritative reply on this issue that I've received.  I'll get with the provider and hopefully get it on their roadmap.
