### ISSUE TITLE
Pylance doesn't work with Python extension 2022.6.0

### ISSUE THREAD

**Issue by russkev** [microsoft/pylance-release#2797]
<h3> Environment data </h3>

-   Language Server version: 2022.4.3
-   OS and version: linux x64
-   Python version: 3.7.5
-   Python extension version: 2022.6.0
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off
-   vsCode version: 1.67.0-insider

<h3> Expected behaviour </h3>

Pylance works

<h3> Actual behaviour </h3>

Pylance doesn't work with Python extension version 2022.6.0. It does work with Python extension version 2022.4.1

<h3> Logs </h3>

Python Language Server Log
```
> conda info --json
> /film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /usr/share/anaconda/bin/conda info --json
Python interpreter path: /film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python
> /bin/python ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /film/tools/packages/nuke/13.1.3/python3 ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
> /film/tools/packages/python/3.7.5.6/openssl-1.0.2/bin/python ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-insiders/extensions/ms-python.python-2022.6.0/pythonFiles/interpreterInfo.py
[ERROR 2022-4-11 9:59:17.392]: [
  'Failed to start language server, Class name = f, completed in 25ms, has a falsy return value, Arg 1: <Uri:/depts/rnd/dev/kevinru/workspace/Lighting/src/AL/apps/Silo2>, Arg 2: {"id":"/film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python","sysPrefix":"/film/tools/packages/python/3.9.7/openssl-1.1.1","envType":"Global","envName":"","envPath":"","path":"/film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python","architecture":3,"sysVersion":"3.9.7 (default, Oct 21 2021, 15:11:26) \\n[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]","version":{"raw":"3.9.7","major":3,"minor":9,"patch":7,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.7 64-bit","detailedDisplayName":"Python 3.9.7 64-bit"}, Arg 3: {"documentSelector":[{"scheme":"file","language":"python"},{"scheme":"untitled","language":"python"},{"scheme":"vscode-notebook","language":"python"},{"scheme":"vscode-notebook-cell","language":"python"},{"scheme":"vscode-interactive-input","language":"python"}],"synchronize":{"configurationSection":"python"},"outputChannel":{"name":"Python Language Server"},"revealOutputChannelOn":4,"initializationOptions":{"experimentationSupport":true,"trustedWorkspaceSupport":true},"middleware":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":true},"id":0,"_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"serverVersion":"2022.4.3","lastCaptured":{},"nextWindow":0,"eventCount":0,"workspace":{},"connectedPromise":{"scope":null,"_resolved":false,"_rejected":false,"_promise":{}},"eventName":"LANGUAGE_SERVER.REQUEST","notebookAddon":{}},"connectionOptions":{"cancellationStrategy":{"_sender":{"folderName":"c754e29647a878380e4522c27312321535a88a3da1"}}}}, Return Value: undefined',
  [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
  Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
   The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
  	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
  	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
  	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
  	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
  	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
  	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
  	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
  	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
  	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
  	at processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]
]
[ERROR 2022-4-11 9:59:17.392]: [
  'Starting language server, Class name = p, completed in 25ms, has a falsy return value, , Return Value: undefined',
  [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
  Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
   The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
  	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
  	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
  	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
  	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
  	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
  	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
  	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
  	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
  	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
  	at processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]
]
[ERROR 2022-4-11 9:59:17.393]: [
  'Failed to start language server, Class name = p, completed in 27ms, has a falsy return value, Arg 1: <Uri:/depts/rnd/dev/kevinru/workspace/Lighting/src/AL/apps/Silo2>, Arg 2: {"id":"/film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python","sysPrefix":"/film/tools/packages/python/3.9.7/openssl-1.1.1","envType":"Global","envName":"","envPath":"","path":"/film/tools/packages/python/3.9.7/openssl-1.1.1/bin/python","architecture":3,"sysVersion":"3.9.7 (default, Oct 21 2021, 15:11:26) \\n[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]","version":{"raw":"3.9.7","major":3,"minor":9,"patch":7,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.7 64-bit","detailedDisplayName":"Python 3.9.7 64-bit"}, Return Value: undefined',
  [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
  Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
   The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
  	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
  	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
  	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
  	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
  	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
  	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
  	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
  	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
  	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
  	at processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]
]
[ERROR 2022-4-11 9:59:17.393]: [
  'Failed to activate a workspace, Class name = f, completed in 6417ms, has a falsy return value, Arg 1: <Uri:/depts/rnd/dev/kevinru/workspace/Lighting/src/AL/apps/Silo2>, Return Value: undefined',
  [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
  Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
   The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
  	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
  	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
  	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
  	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
  	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
  	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
  	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
  	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
  	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
  	at processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]
]
[ERROR 2022-4-11 9:59:17.394]: Failure during activation. [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]
[ERROR 2022-4-11 9:59:17.394]: sendStartupTelemetry() failed. [Error: Extension 'ms-python.python' CANNOT use API proposal: tabs.
Its package.json#enabledApiProposals-property declares: quickPickSortByLabel, testObserver, notebookEditor but NOT tabs.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:61468)
	at Object.get tabGroups [as tabGroups] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43872)
	at e (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201234)
	at new h (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2201419)
	at new y (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2213650)
	at S.registerBuiltinFeatures (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2170339)
	at new te (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2148803)
	at new S (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:2318187)
	at t.NodeLanguageClientFactory.createLanguageClient (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:32002)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f.start (/home/users/kevinru/.vscode-insiders/extensions/ms-python.python-2022.6.0/out/client/extension.js:2:33749)]

```

**Comment by debonte** [comment]
>Python Language Server Log

@russkev, this is the Python log, not the Python Language Server log, right?

**Comment by russkev** [comment]
Correct, I updated the issue. Python Language Server log is empty as far as I can tell.

**Comment by debonte** [comment]
Thanks. I'll transfer this to the Python extension team, but was worried that they might send it right back after seeing "Python Language Server log". :)

Appreciate you reporting this!
