### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'onDidChangeCellLanguage')

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2849]
TypeError: Cannot read properties of undefined (reading 'onDidChangeCellLanguage')
	at u.addEventHandlers (\out\client\extension.js:78:175816)
	at new u (\out\client\extension.js:78:174085)
	at Object.t.resolveInstance (\out\client\extension.js:44:268557)
	at \out\client\extension.js:44:267523
	at Object.t.resolve (\out\client\extension.js:44:267786)
	at \out\client\extension.js:44:258362
	at e._get (\out\client\extension.js:44:258128)
	at e.get (\out\client\extension.js:44:256840)
	at a.get (\out\client\extension.js:78:444806)
	at new b (\out\client\extension.js:9:418400)
	at r.startLanguageServer (\out\client\extension.js:59:245270)
	at processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)

**Comment by debonte** [comment]
According to telemetry this is only reproducing for users with very old Python extensions from February 2021. Probably fixed by https://github.com/microsoft/vscode-python/pull/15639.
