### ISSUE TITLE
Pylance fails with "Error: Debug Failure. createKeyForReference received unexpected index type"

### ISSUE THREAD

**Issue by dhkim09a** [microsoft/pylance-release#3092]
<h3> Environment data </h3>

-   Language Server version: 2022.7.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.9 64-bit
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

**Code that Pylance fails:**

```python
from os import path as _p
from typing import Dict, List


class VersionedStr(str):
    version: dict

    def __new__(cls, value):
        obj = super().__new__(cls, value)
        obj.version = {}
        return obj


def find_interface_srcs(root: str) -> set:
    return set()


def find_interface_srcs_from_both_os(guest_pathes: List[str], host_pathes: List[str]) -> List[VersionedStr]:
    srcs: Dict[str, VersionedStr] = {}

    for guest_path in guest_pathes:
        guest_srcs = find_interface_srcs(guest_path)
        for src in guest_srcs:
            if (name := src[:-5]) not in srcs:
                srcs[name] = VersionedStr(name)
            srcs[name].version['guest'] = _p.join(guest_path, src)

    for host_path in host_pathes:
        host_srcs = find_interface_srcs(host_path)
        for src in host_srcs:
            if (name := src[:-5]) not in srcs:
                srcs[name] = VersionedStr(name)
            srcs[name].version['host'] = _p.join(host_path, src)

    return list(srcs.values())
```

**Code that Pylance works:**

```python

from os import path as _p
from typing import Dict, List


class VersionedStr(str):
    version: dict

    def __new__(cls, value):
        obj = super().__new__(cls, value)
        obj.version = {}
        return obj


def find_interface_srcs(root: str) -> set:
    return set()


def find_interface_srcs_from_both_os(guest_pathes: List[str], host_pathes: List[str]) -> List[VersionedStr]:
    srcs: Dict[str, VersionedStr] = {}

    for guest_path in guest_pathes:
        guest_srcs = find_interface_srcs(guest_path)
        for src in guest_srcs:
            if (name := src[:-5]) not in srcs:
                srcs[name] = VersionedStr(name)
            s = srcs[name]
            s.version['guest'] = _p.join(guest_path, src)

    for host_path in host_pathes:
        host_srcs = find_interface_srcs(host_path)
        for src in host_srcs:
            if (name := src[:-5]) not in srcs:
                srcs[name] = VersionedStr(name)
            s = srcs[name]
            s.version['host'] = _p.join(host_path, src)

    return list(srcs.values())
```

<h3> Repro Steps </h3>

1. Open VSCode
2. Create a new python file
3. Copy & paste the above code

<h3> Expected behavior </h3>

Pylance correctly analyze the source code

<h3> Actual behavior </h3>

1. Pylance fails with the below error log.
2. Pylance says L28 (`for host_path in host_pathes:`) is unreachable.
3. Pylance says `host_path` at L29 is undefined. 

<h3> Logs </h3>

```
An internal error occurred while binding file "Untitled-1": Error: Debug Failure. createKeyForReference received unexpected index type
    at createKeyForReference (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/codeFlowTypes.ts:237:13)
    at createKeyForReference (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/codeFlowTypes.ts:218:25)
    at C.visitAssignment (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:849:50)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:132:29)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at forEach (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:107:22)
    at Array.forEach (<anonymous>)
    at C.walkMultiple (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:105:15)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:100:18)
    at C._walkStatementsAndReportUnreachable (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:2583:22)
    at C.visitSuite (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:345:14)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:330:29)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at callback (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:1148:18)
    at C._trackCodeFlowExpressions (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:3236:9)
    at C._bindLoopStatement (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:3258:49)
    at C.visitFor (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:1147:14)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:205:29)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at C._walkStatementsAndReportUnreachable (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:2583:22)
    at C.visitSuite (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:345:14)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:330:29)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at callback (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:1148:18)
    at C._trackCodeFlowExpressions (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:3236:9)
    at C._bindLoopStatement (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:3258:49)
    at C.visitFor (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:1147:14)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:205:29)
    at C.walk (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at C._walkStatementsAndReportUnreachable (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:2583:22)
    at C.visitSuite (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:345:14)
    at C.visitNode (/Users/dhkim/.vscode/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:330:29)
```

**Comment by erictraut** [comment]
Thanks for reporting the problem. This is a known issue, and the bug has been fixed in pyright (the type checker that underlies pylance). The fix is already incorporated in the prerelease (insiders) build of pylance (2022.7.41).

**Comment by xiachenrui** [comment]
> Thanks for reporting the problem. This is a known issue, and the bug has been fixed in pyright (the type checker that underlies pylance). The fix is already incorporated in the prerelease (insiders) build of pylance (2022.7.41).

Thanks! It is useful for me.

**Comment by MagedSaeed** [comment]
@xiachenrui 

Please let us know when the stable release is issued. We are desperately waiting.

Thanks Much,.
