### ISSUE TITLE
Unreachable code is reachable

### ISSUE THREAD

**Issue by adlantz** [microsoft/pylance-release#3105]
## Environment data

-   Language Server version: v2022.7.40
-   OS and version: MacOs Monterey 12.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0

## Code Snippet

<img width="447" alt="Screen Shot 2022-07-27 at 15 03 55" src="https://user-images.githubusercontent.com/37378372/181361968-ba028940-4c76-48be-8483-f8d299b8eed9.png">

```
class fruit:
    def __init__(self, kind):
        self.kind = kind


def test(obj: any):
    str1 = "a"
    obj[str1].kind["type"] = None
    print("this code is reachable")


b1 = fruit({"type": "banana"})
obj = {"a": b1}

test(obj)
```

## Repro Steps

1. Run the above code, see that the code is reachable

## Expected behavior

pylance doesn't see anything wrong

## Actual behavior

pylance says it's unreachable

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing.

In your sample code, you are used the symbol `any` in the type annotation for the `obj` parameter. Where is `any` defined? This isn't a built-in symbol. Are you importing it from a library? Was your intent to use `typing.Any`?

I also see from your screen shot that there is a red squiggle under the `class` keyword. What error is reported for you there?

**Comment by wisscot** [comment]
I think this is a bug as I can reproduce it as 
```
d = {}
v = "dummy"
d[v].some_attr["dummy2"] = "dummy3"

print("this line is marked as unreachable by Pylance")
```
<img width="671" alt="image" src="https://user-images.githubusercontent.com/4357844/181564531-9771e943-28ca-4df0-81ad-147890b1a2a2.png">

**Comment by wisscot** [comment]
Here's the error trace @erictraut 
```
An internal error occurred while binding file "/home/guoliang.he/cruise/cruise/unified-analysis-metadata/ros/src/sim_analysis/src/sim_analysis/aaa.py": Error: Debug Failure. createKeyForReference received unexpected index type
    at createKeyForReference (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/codeFlowTypes.ts:237:13)
    at createKeyForReference (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/codeFlowTypes.ts:218:25)
    at C.visitAssignment (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:849:50)
    at C.visitNode (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:132:29)
    at C.walk (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at forEach (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:107:22)
    at Array.forEach (<anonymous>)
    at C.walkMultiple (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:105:15)
    at C.walk (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:100:18)
    at C._walkStatementsAndReportUnreachable (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:2583:22)
    at callback (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:287:22)
    at C._createNewScope (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:3424:9)
    at C.bindModule (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/binder.ts:262:14)
    at callback (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/sourceFile.ts:1197:28)
    at s.timeOperation (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/common/timing.ts:40:20)
    at callback (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/sourceFile.ts:1184:38)
    at t.LogTracker.log (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/common/logTracker.ts:43:20)
    at t.SourceFile.bind (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/sourceFile.ts:1181:33)
    at O._bindFile (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/program.ts:931:34)
    at O.getBoundSourceFile (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/analyzer/program.ts:501:14)
    at _0x38dc26.<computed> (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:247770)
    at callback (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:9565)
    at t.LogTracker.log (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/common/logTracker.ts:43:20)
    at /home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:9443
    at _0x149aa5.trackPerf (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:96324)
    at code (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:8823)
    at t.run (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/backgroundThreadBase.ts:93:24)
    at _0x215411.onMessage (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/server.bundle.js:1:8536)
    at MessagePort.<anonymous> (/home/guoliang.he/.vscode-server/extensions/ms-python.vscode-pylance-2022.7.40/dist/pyright-internal/src/backgroundAnalysisBase.ts:313:66)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)Pylance
```

**Comment by erictraut** [comment]
You are hitting a bug that was fixed a couple of weeks ago in pyright. The fix is included in the prerelease (insiders) version of pylance, and it will be included in the next production release.

**Comment by wisscot** [comment]
Thank you @erictraut .  Switching to pre-release solved the issue.
