### ISSUE TITLE
Pylance server not starting

### ISSUE THREAD

**Issue by tinmarr** [microsoft/pylance-release#3248]
<h3> Environment data </h3>

-   Language Server version: 2022.8.41
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.6
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

NA

<h3> Repro Steps </h3>

1. Restarting VSCode or running the `Python: Restart Language Server` command.

<h3> Expected behavior </h3>

I expect Pylance to start

<h3> Actual behavior </h3>

It doesn't

<h3> Logs </h3>

```
[ERROR 2022-7-25 16:27:58.154]: [
  'Failed to get analysis options, Class name = u, completed in 10ms, has a falsy return value, , Return Value: undefined',
  Error: Can not delete in empty document
      at R (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
      at D.getEdits (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:9718)
      at D.updateConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8952)
      at D.doWriteConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8556)
      at async Object.factory (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8216)
]
[ERROR 2022-7-25 16:27:58.155]: [
  'Starting language server, Class name = d, completed in 11ms, has a falsy return value, , Return Value: undefined',
  Error: Can not delete in empty document
      at R (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
      at D.getEdits (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:9718)
      at D.updateConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8952)
      at D.doWriteConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8556)
      at async Object.factory (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8216)
]
[ERROR 2022-7-25 16:27:58.156]: [
  'Restarting language server, Class name = d, completed in 12ms, has a falsy return value, , Return Value: undefined',
  Error: Can not delete in empty document
      at R (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
      at D.getEdits (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:9718)
      at D.updateConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8952)
      at D.doWriteConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8556)
      at async Object.factory (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8216)
]
[ERROR 2022-7-25 16:27:58.157]: [
  'Failed to restart language server, Class name = d, completed in 13ms, has a falsy return value, , Return Value: undefined',
  Error: Can not delete in empty document
      at R (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
      at D.getEdits (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:9718)
      at D.updateConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8952)
      at D.doWriteConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8556)
      at async Object.factory (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8216)
]
```

**Comment by debonte** [comment]
What version of the Python extension do you have installed?

Does this happen if the only open Python file is blank, or a very simple file? If not, can you provide a file that reproduces the issue?

**Comment by tinmarr** [comment]
I was on the prerelease version of the python extension. Switched back to the stable version fixed the problem. Not sure whats up but must be something on their end.

This wasn't an issue with any specific file. Even with no files open and the search mode set to openFilesOnly it was breaking.

**Comment by debonte** [comment]
Probably the same issue as this: https://github.com/microsoft/vscode-python/issues/19737

If you have any more details, please add them there.
