### ISSUE TITLE
Pylance client: couldn't create connection to server.

### ISSUE THREAD

**Issue by Pratikanand8386** [microsoft/pylance-release#3391]
Pylance client: couldn't create connection to server.It doesn't detect errors in my code there is error showing in output.

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by TaqiHaider-el** [comment]
I also have encountered the  same issue
![Capture](https://user-images.githubusercontent.com/96980772/193423300-68637ea7-b15e-429b-aca7-f39804900dea.JPG)

**Comment by jonleeacc** [comment]
I have the same problem

**Comment by Boltynight** [comment]
Me too
<img width="344" alt="image" src="https://user-images.githubusercontent.com/98009648/196833102-473b1ad3-2867-426f-9877-f64610c1a6ac.png">
But the worst part is I have been trying to find a solution for a dang long time but I can't

**Comment by debonte** [comment]
@jonleeacc, @Boltynight, if you are still seeing this please open a new issue and provide your "Python Language Server" log.

**Comment by paulpacaud** [comment]
Just go to your .vscode folder in your computer. Then in .vscode/extensions. There you will see one (or several) folders related to pylance. Just delete them. Then reopen VSCode, reinstall Pylance, it shall work. Maybe at the end, you'll need to restart VSCode to apply the changes. ;)

**Comment by gbowne1** [comment]
I get a lot of errors with this.

and 

this was in the report in output

2023-03-19 13:44:59.381 [info] [Error - 1:44:59 PM] Server initialization failed.
2023-03-19 13:44:59.381 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-03-19 13:44:59.381 [info] [Info  - 1:44:59 PM] Connection to server got closed. Server will restart.
2023-03-19 13:44:59.381 [info] true
2023-03-19 13:44:59.381 [info] [Error - 1:44:59 PM] Pylint client: couldn't create connection to server.
2023-03-19 13:44:59.381 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-03-19 13:44:59.381 [info] [Error - 1:44:59 PM] Restarting server failed
2023-03-19 13:44:59.381 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 

then 

2023-03-19 13:44:59.885 [info] Traceback (most recent call last):
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/tool/lsp_server.py", line 48, in <module>
    name="pylint-server", version="v0.1.0", max_workers=MAX_WORKERS
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pygls/server.py", line 358, in __init__
    super().__init__(protocol_cls, converter_factory, loop, max_workers)
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pygls/server.py", line 200, in __init__
    self.lsp = protocol_cls(self, converter_factory())
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pygls/protocol.py", line 166, in default_converter
    converter = converters.get_converter()
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/lsprotocol/converters.py", line 17, in get_converter
    return _hooks.register_hooks(converter)
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/lsprotocol/_hooks.py", line 35, in register_hooks
    _resolve_forward_references()
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/lsprotocol/_hooks.py", line 30, in _resolve_forward_references
    attrs.resolve_types(value, lsp_types.ALL_TYPES_MAP, {})
  File "/home/gbowne1/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/attr/_funcs.py", line 408, in resolve_types
    hints = typing.get_type_hints(cls, globalns=globalns, localns=localns)
  File "/usr/lib/python3.7/typing.py", line 973, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.7/typing.py", line 262, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/usr/lib/python3.7/typing.py", line 262, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/usr/lib/python3.7/typing.py", line 263, in _eval_type
    if ev_args == t.__args__:
  File "/usr/lib/python3.7/typing.py", line 658, in __eq__
    return frozenset(self.__args__) == frozenset(other.__args__)

After that this keeps repeating:

File "/usr/lib/python3.7/typing.py", line 664, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/usr/lib/python3.7/typing.py", line 477, in __hash__
    return hash((self.__forward_arg__, self.__forward_value__))
  File "/usr/lib/python3.7/typing.py", line 663, in __hash__
    return hash((Union, frozenset(self.__args__)))
  File "/usr/lib/python3.7/typing.py", line 664, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/usr/lib/python3.7/typing.py", line 477, in __hash__
    return hash((self.__forward_arg__, self.__forward_value__))

**Comment by nav9** [comment]
I tried paulpacaud's solution of deleting the pylance-related folder and reinstalling the extension. It initially seemed to work, but after restarting the system and opening VS Code, the error showed up again. Please fix it. I've opened a new issue [here](https://github.com/microsoft/pylance-release/issues/4485).

**Comment by Miladiouss** [comment]
My issue (on a remote server) was resolved by add the following to my workspace `settings.json`. Don't forget to adjust the correct python path.

```json
{
    "python.languageServer": "Pylance",
    "pylint.path": [
        ">>>path/to/python<<<",
        "-m",
        "pylint"
    ]
}
```

**Comment by ShekharamShashi** [comment]
I'm facing the same issue with my local server on Ubuntu. Can anyone help me?

**Comment by VALilly** [comment]
I am facing this issue as well

**Comment by lucvsbraga** [comment]
I had the same issue. I will try the @Miladiouss solution. Hope it works.

**Comment by CavxL** [comment]
Run VS Code as admin or globally disable trust.

**Comment by MBounouar** [comment]
Uninstalling pylance and restarting vscode solved the issue in my case.

**Comment by Miladiouss** [comment]
FYI - Setting up a new VS Code profile worked for me which is much easier than reinstalling.

**Comment by yuanjv** [comment]
> I'm facing the same issue with my local server on Ubuntu. Can anyone help me?

same issue

**Comment by yuanjv** [comment]
my error log said that my Jedi server was unable to boot. After changing the "python.languageServer" in workspace settings to "Jedi", the issue was fixed.

**Comment by ArtGMlg** [comment]
The same problem occurred with the version of the pylance vs code v2024.4.1 extension.
The rollback to version 2024.3.2 helped

**Comment by ArtGMlg** [comment]
It looks like it was some kind of problem with vs code, because now, after restarting it and updating pylance to the latest version, the connection failure no longer appears. But back than even a complete reinstallation of Python and pylance packages had no effect.

**Comment by notwatermango** [comment]
I had to install the newest Pylance to fix this

**Comment by Kareneveve** [comment]
it happen in v2025.2.1 again and i don't know how to fix this
anyone can help me?
please🥺

**Comment by ArtGMlg** [comment]
@Kareneveve You can try to roll back to the previous version of the extension via the extension management menu (gear icon) and then restart VS Code. In my case, rolling back and then switching back to the latest version solved the problem.

**Comment by Kareneveve** [comment]
@ArtGMlg it seems don't Pylance cause this promble. i uninstall Pylance, only install Python and Python Debugger still show 'Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.'
:-(

**Comment by debonte** [comment]
@Kareneveve, please open a new issue.

**Comment by Terrence-zzh** [comment]
> Just go to your .vscode folder in your computer. Then in .vscode/extensions. There you will see one (or several) folders related to pylance. Just delete them. Then reopen VSCode, reinstall Pylance, it shall work. Maybe at the end, you'll need to restart VSCode to apply the changes. ;)

i meet the same issue when i use the remote code in remote server, firstly I try to make it in remote extension and failed. At last, I try it at my own pc and succeded. So the key is the local extension
