### ISSUE TITLE
Test discovery breaks when switching to pylance

### ISSUE THREAD

**Issue by rsokl** [microsoft/pylance-release#341]
## Environment data

I am not sure if this is relevant, but I am using the Remote-SSH extension

-   Language Server version: 2020.9.0 (pyright 60eb2cca)
-   OS and version: Ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7 Anaconda

## Expected behaviour

For tests to be discovered automatically - this works fine when I am using `jedi`. 

## Actual behaviour
Any time I start the `pylance` language server, I see a `Couldn't start client Python Tools` message along with the message `Error: command 'pyright.createtypestub' already exists`. 

Furthermore, I don't see any attempt to discover tests. When I manually prompt vscode to discover tests, I see `command: python.discoverTests not found`

![image](https://user-images.githubusercontent.com/29104956/92501652-d8bb5700-f1cc-11ea-89b2-84501bf03d5c.png)

## Logs

```
[Info  - 12:23:54 PM] Pylance language server 2020.9.0 (pyright 60eb2cca) starting
[Info  - 12:23:54 PM] Server root directory: /home/rsokl/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist
[Error - 12:23:54 PM] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at _.registerCommand (/home/rsokl/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:665:142)
	at Object.registerCommand (/home/rsokl/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:961:119)
	at J.register (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:285965)
	at J.initialize (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:285523)
	at _.initializeFeatures (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:304477)
	at /home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:296497
[Error - 12:23:54 PM] Starting client failed
Error: command 'pyright.createtypestub' already exists
	at _.registerCommand (/home/rsokl/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:665:142)
	at Object.registerCommand (/home/rsokl/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:961:119)
	at J.register (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:285965)
	at J.initialize (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:285523)
	at _.initializeFeatures (/home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:304477)
	at /home/rsokl/.vscode-server/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:296497
```

**Comment by judej** [comment]
@rsokl, would you please try running after disabling/uninstalling PyRight? Pylance and PyRight are both registering commands that are in conflict.

**Comment by rsokl** [comment]
@judej That worked! Thank you for the insight. Perhaps there would be a way to warn other `pyright` users of this.  

Much appreciated, and I am excited to see the benefits of this over the old language server!
