### ISSUE TITLE
fails to download version 2022.9.40 event manually

### ISSUE THREAD

**Issue by maorgur** [microsoft/pylance-release#3415]
## Environment data

-   Language Server version: 2022.9.30
-   OS and version: windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Repro Steps

updating pylance from version 2022.9.30 to 2022.9.40  (including manually)

## Expected behavior

download update
## Actual behavior

error while downloading

## Logs

```
[2022-09-30 11:30:42.944] [renderer1] [error] ["Download: XHR failed","    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)","    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)"]
[2022-09-30 11:30:43.195] [renderer1] [error] XHR failed: Download: XHR failed
    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)
    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)
[2022-09-30 11:31:44.106] [renderer1] [error] ["Download: XHR failed","    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)","    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)"]
[2022-09-30 11:31:44.230] [renderer1] [error] XHR failed: Download: XHR failed
    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)
    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)
[2022-09-30 11:35:05.723] [renderer1] [error] [Extension Host] Error: Binary request timed out. {"Autocomplete":{"filename":"c:\\Users\\מאור\\vscode\\vscode\\.vscode\\settings.json","before":"{\r\n    \"python.testing.unittestArgs\": [\r\n        \"-v\",\r\n        \"-s\",\r\n        \"./python\",\r\n        \"-p\",\r\n        \"*test*.py\"\r\n    ],\r\n    \"python.testing.pytestEnabled\": false,\r\n    \"python.testing.unittestEnabled\": true,","after":"\r\n}","region_includes_beginning":true,"region_includes_end":true,"max_num_results":5,"offset":223,"line":9,"character":43,"indentation_size":4}}
	at Timeout._onTimeout (c:\Users\מאור\.vscode\extensions\tabnine.tabnine-vscode-3.6.15\out\extension.js:17:33073)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[2022-09-30 11:35:14.073] [renderer1] [error] ["Download: XHR failed","    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)","    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)"]
[2022-09-30 11:35:14.356] [renderer1] [error] XHR failed: Download: XHR failed
    at G.downloadExtension (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170479)
    at async G.doRun (vscode-file://vscode-app/c:/Users/user123/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)
```
![Untitled](https://user-images.githubusercontent.com/90182341/193230727-4ba67fcb-fd87-4e05-8ade-03503024a83c.png)
![Untitled](https://user-images.githubusercontent.com/90182341/193231126-e3197252-c7c4-4840-9a8a-1ea374cdf2c2.png)
[dd_VSIXInstaller_20220930114547_4734.log](https://github.com/microsoft/pylance-release/files/9682434/dd_VSIXInstaller_20220930114547_4734.log)

**Comment by judej** [comment]
Could you please repro steps for this?

**Comment by maorgur** [comment]
> Could you please repro steps for this?

Somehow now it's working, i don't know what happened. (I did all the obvious steps like restarting the computer, checking network connection)

**Comment by judej** [comment]
Ok, thanks, please reopen if this reoccurs.
