### ISSUE TITLE
Pylance crashes when topmost cell of notebook is deleted

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3469]
-   Language Server version: 2022.10.21

## Repro Steps

1. "Create: New Jupyter Notebook"
2. Add a second cell
3. Delete topmost cell

## Result

Error: Debug Failure. False expression: Chained file path should be undefined
    at _0x4abe8f (c:\Users\erikd\.vscode\extensions\ms-python.vscode-pylance-2022.10.21\dist\server.bundle.js:1:426854)
    at _0x42fb36 (c:\Users\erikd\.vscode\extensions\ms-python.vscode-pylance-2022.10.21\dist\server.bundle.js:1:425677)
    at _0x31fe1d._onDidChangeNotebookDocument (c:\Users\erikd\.vscode\extensions\ms-python.vscode-pylance-2022.10.21\dist\server.bundle.js:1:396250)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221031-19-October-2022-PreRelease)
