### ISSUE TITLE
Pylance client: couldn't create connection to server

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#3615]
Type: <b>Bug</b>

```
Error: command 'pyright.createtypestub' already exists
    at s.registerCommand (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:109710)
    at Object.registerCommand (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:32839)
    at t.ExecuteCommandFeature.register (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:1814323)
    at t.ExecuteCommandFeature.initialize (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:1813902)
    at S.initializeFeatures (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:1765816)
    at S.doInitialize (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:1753365)
    at S.start (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:1750380)
    at h.start (c:\Users\kanadig\.vscode\extensions\ms-python.python-2022.19.13151009\out\client\extension.js:2:38509)
[Error - 12:10:03 PM] Pylance client: couldn't create connection to server.
```

Extension version: 2022.11.20
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.82GB free)|
|Process Argv|C:\\GIT\\linters\\vscode-pylint --crash-reporter-id a228f424-c4b5-46af-9d39-ca54fee042cd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30566498
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30605430
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by judej** [comment]
@karthiknadig, could you please add the repro steps for this?

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
