### ISSUE TITLE
"Organize Imports" does nothing

### ISSUE THREAD

**Issue by Lexicality** [microsoft/pylance-release#375]
## Environment data
-   Language Server version: 2020.9.4
-   OS and version: WSL2/Ubuntu 20.04.1 LTS
-   Python version: 3.6.11

## Expected behaviour
Running "Organise Imports" from the command palette invokes `isort` and fixes import order

## Actual behaviour
No change to file, no output

## Logs
Pylance:
```none
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - experiment'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonTipPromptWording'
> conda --version
> python3.7 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-09-16 14:20:24: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu2/home/lex/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/lex/.config/Code/User/settings.json')
	at _handleError (/home/lex/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteExtensionHostProcess.js:730:74)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async v.readText (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:1:495755)
	at async p.doesFileNeedToBeFixed (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:953520)
	at async /home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952647
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952593)
	at async p.updateTestSettings (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-09-16 14:20:24: Failed to get interpreter information for '/home/lex/.pyenv/shims/python3.8' [Error: Command failed: "/home/lex/.pyenv/shims/python3.8" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/interpreterInfo.py"
pyenv: python3.8: command not found

The `python3.8' command exists in these Python versions:
  3.8.4

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

	at ChildProcess.exithandler (child_process.js:295:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/home/lex/.pyenv/shims/python3.8" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/interpreterInfo.py"'
}
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
Starting Pylance language server.
Python interpreter path: ./.venv/bin/python3.6
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> conda --version
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
##########Linting Output - flake8##########
4,1,I,I004:isort found an unexpected blank line in imports
6,1,I,I001:isort found an import in the wrong position
7,1,I,I004:isort found an unexpected blank line in imports
8,101,E,E501:line too long (102 > 100 characters)
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py black --diff --quiet ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py black --diff --quiet ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
##########Linting Output - flake8##########
4,1,I,I004:isort found an unexpected blank line in imports
6,1,I,I001:isort found an import in the wrong position
7,1,I,I004:isort found an unexpected blank line in imports
8,101,E,E501:line too long (102 > 100 characters)
```
Microsoft (where it works):
```none
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - experiment'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonTipPromptWording'
> conda --version
> conda info --json
> python3.7 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-16 14:22:45: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu2/home/lex/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/lex/.config/Code/User/settings.json')
	at _handleError (/home/lex/.vscode-server/bin/e790b931385d72cf5669fcefc51cdf65990efa5d/out/vs/server/remoteExtensionHostProcess.js:730:74)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async v.readText (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:1:495755)
	at async p.doesFileNeedToBeFixed (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:953520)
	at async /home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952647
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952593)
	at async p.updateTestSettings (/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/out/client/extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-09-16 14:22:45: Failed to get interpreter information for '/home/lex/.pyenv/shims/python3.8' [Error: Command failed: "/home/lex/.pyenv/shims/python3.8" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/interpreterInfo.py"
pyenv: python3.8: command not found

The `python3.8' command exists in these Python versions:
  3.8.4

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

	at ChildProcess.exithandler (child_process.js:295:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/home/lex/.pyenv/shims/python3.8" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py" "/home/lex/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/interpreterInfo.py"'
}
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Starting Microsoft Python language server.
Python interpreter path: ./.venv/bin/python3.6
> conda --version
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
##########Linting Output - flake8##########
4,1,I,I004:isort found an unexpected blank line in imports
6,1,I,I001:isort found an import in the wrong position
7,1,I,I004:isort found an unexpected blank line in imports
8,101,E,E501:line too long (102 > 100 characters)
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/sortImports.py - --diff
cwd: ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py black --diff --quiet ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py.782ed9ea092c1f1aad5ec65bfe1037d5.tmp
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py black --diff --quiet ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py.782ed9ea092c1f1aad5ec65bfe1037d5.tmp
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
> ~/projects/data-lake/.venv/bin/python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.109390/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/projects/data-lake/src/retailer_service_retailer_facts_compactor/tests/test_retailer_service_retailer_facts_compactor.py
cwd: ~/projects/data-lake
##########Linting Output - flake8##########
6,101,E,E501:line too long (102 > 100 characters)
```
## Code Snippet / Additional information

```python
from unittest.mock import Mock

import pytest

from pyspark.sql.session import SparkSession
from _pytest.monkeypatch import MonkeyPatch

from retailer_service_retailer_facts_compactor.glue.retailer_service_retailer_facts_compactor import (
    main,
)
```

`isort` exists, is installed in the virtualenv and is configured via `pyproject.toml`.

**Comment by jakebailey** [comment]
We don't handle the organize imports command, the core extension does. I'll move this issue there as it's the one running `isort`.
