### ISSUE TITLE
Language server crashing with `TypeError: this._token.cancel is not a function`

### ISSUE THREAD

**Issue by andreaschiappacasse** [microsoft/pylance-release#4055]
Hello, I  am getting random errors while editing files, causing the server to crash. I can manually restart the language server and it works for some time, before crashing again after some time (which could be minutes or hours).

I couldn't find a way to reproduce it consistently, but the error is always the same, I attach the log of the error in the hope that someone can point out possible root causes or debugging steps.

Please let me know how can I help debugging this problem.

## Environment data

-   Language Server version: v2023.3.10
-   Python version: 3.9

## Logs

I get two types of log, before the crashes, related to the same root cause.
Sometimes I get:

```
TypeError: this._token.cancel is not a function
    at m.cancel (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1:1006856)
    at Function.cancelIndexingRequest (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\server.bundle.js:1:483332)
    at Function.requestIndexingFromBackgroundThread (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\server.bundle.js:1:482427)
    at _0x3cd8fb.refreshIndexing (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\server.bundle.js:1:4278)
    at _0x225280.refreshIndexing (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1:8460)
    at _0x225280.invalidateAndForceReanalysis (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1:9231)
    at C.invalidateAndForceReanalysis (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1:420084)
    at Timeout.<anonymous> (c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1:431230)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[Error - 12:17:23 PM] Client Pylance: connection to server is erroring. Shutting down server.
[Error - 12:17:23 PM] Client Pylance: connection to server is erroring. Shutting down server.
[Error - 12:17:23 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:17:23 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:17:23 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:17:23 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

other times I get;
```
....
[Info  - 12:51:37 PM] (26200) [BG(4)] Long operation: analyzing: c:\Users\REDACTED\notebooks\REDACTED.ipynb:pylance-notebook-cell:W0sZmlsZQ==.py (11101ms)
[Error - 12:52:10 PM] Notification handler 'workspace/didChangeWatchedFiles' failed with message: this._token.cancel is not a function
```

below this error the log prints the full dump of 

`c:\Users\REDACTED\.vscode\extensions\ms-python.vscode-pylance-2023.3.10\dist\pyright.bundle.js:1`

that I omit, but I can attach if useful.

**Comment by debonte** [comment]
@heejaechang, since this is indexing related, can you take a look?

**Comment by andreaschiappacasse** [comment]
**Update:**
It could be that the bug happens only when "_format on save_" is enabled in vscode.  
Disabling that feature seems to have fixed the problem. I was using _black_ as python formatter, if relevant.
I can't be 100% sure it's related, but the crash was happening every 15 or so minutes, and it didn't happen in a couple of hours after disabling "_format on save_".

**Comment by heejaechang** [comment]
@andreaschiappacasse thank you for reporting the issue. can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) while the crash is happening? 

and some description how to set up the repro so we can try to repro the issue?

**Comment by andreaschiappacasse** [comment]
Hi @heejaechang, here I attach a trace log of the crash happening twice in a row .
The crashes happen at [3:59:23] and [4:00:07].

[LOG.txt](https://github.com/microsoft/pylance-release/files/10970343/LOG.txt)

I am sorry but I couldn't repro it outside of my project, so I cannot provide any description on how to repro it.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.3.25, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022325-17-March-2023-PreRelease)

**Comment by MosesLake-Engr** [comment]
I got that same error code and I'm just a new to programing and Python. Code: -32097.
Is there a way to restart either Python or VS Studio to bypass the error? This is what the error message looks like:
2023-05-31 16:04:53.722 [info] [Error - 4:04:53 PM] Client Pylance: connection to server is erroring. Shutting down server.
2023-05-31 16:04:53.727 [info] [Error - 4:04:53 PM] Connection to server got closed. Server will not be restarted.
2023-05-31 16:04:53.727 [info] [Error - 4:04:53 PM] Stopping server failed
2023-05-31 16:04:53.727 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
Any help would be appreciated. Thanks

**Comment by heejaechang** [comment]
@MosesLake-Engr can you open new issue with logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

this issue is already closed and the error code is common code so I dont think it is related to this issue.

**Comment by MosesLake-Engr** [comment]
Hello Heejae,

I appreciate your response.
I am just trying to learn Python and thought it was hung up.
I reran the code and today it works.

Thanks for your attention

Patrick
