### ISSUE TITLE
Pylance not working at all.

### ISSUE THREAD

**Issue by Bezmehrabi** [microsoft/pylance-release#413]
-   Language Server version: v2020.9.6
-   OS and version: ArchLinux, Kernel 5.8.10-arch1-1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-  VSCode version: 1.49.0

Hi, it's not working at all whatsoever. I did change the languageServer to pylance in settings, I have python pacakge installed
## Logs

> python ~/.vscode-oss/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-24 20:27:45: Listing Nuget Packages, Class name = d, completed in 1ms, has a falsy return value, Arg 1: "https://pvsc.blob.core.windows.net", Arg 2: "-stable", Arg 3: "", Arg 4: "https://pvsc.azureedge.net", Arg 5: <Uri:/tmp/test.py>, Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:184960)
	at v.t.containerNameIsValid (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:185222)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:410066
	at Object.t.validateArgs (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:189467)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:409993)
	at z.listBlobsSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:367960)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313790
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313768)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async listPackages (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313474)]
Error 2020-09-24 20:27:45: Get latest language server nuget package version, Class name = d, completed in 1ms, has a falsy return value, Arg 1: <Uri:/tmp/test.py>, Arg 2: "0.0.0", Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:184960)
	at v.t.containerNameIsValid (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:185222)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:410066
	at Object.t.validateArgs (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:189467)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:409993)
	at z.listBlobsSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:367960)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313790
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313768)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async listPackages (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313474)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
Error 2020-09-24 20:27:45: Get latest version of language server, Class name = f, completed in 2ms, has a falsy return value, Arg 1: <Uri:/tmp/test.py>, Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:184960)
	at v.t.containerNameIsValid (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:185222)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:410066
	at Object.t.validateArgs (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:189467)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:409993)
	at z.listBlobsSegmentedWithPrefix (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/node_modules/azure-storage.js:211:367960)
	at /home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313790
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313768)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async listPackages (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:47:313474)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
Error 2020-09-24 20:27:45: Get language server folder name, Class name = f, completed in 5ms, has a falsy return value, Arg 1: <Uri:/tmp/test.py>, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at getLanguageServerFolderName (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:24:193095)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-09-24 20:27:45: Failed to start language server, Class name = r, completed in 9ms, has a falsy return value, Arg 1: <Uri:/tmp/test.py>, Arg 2: {"architecture":3,"path":"/usr/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysPrefix":"/usr","fileHash":"1464759c31e1da69bb7f6ffdb3bb22a39cfef12e58f642c2c193cd404a009bde8f52ade67fd62c17898def6a05c9dc9c3496101e0d1b200a7097d22d98f8f80e","envType":"Unknown","displayName":"Python 3.8.5 64-bit"}, Arg 3: {"documentSelector":[{"scheme":"file","language":"python"},{"scheme":"untitled","language":"python"},{"scheme":"vscode-notebook","language":"python"},{"scheme":"vscode-notebook-cell","language":"python"}],"synchronize":{"configurationSection":"python"},"outputChannel":{"name":"Python Language Server","_channel":{}},"revealOutputChannelOn":4,"middleware":{"configService":{"serviceContainer":{"container":{"options":{"autoBindInjectable":false,"defaultScope":"Transient","skipBaseClassChecks":false},"guid":"f396513f-11a8-c16b-a909-ba29840f2997","_bindingDictionary":{"_map":{}},"_snapshots":[],"_middleware":null,"parent":null,"_metadataReader":{}}},"workspaceService":{}},"lastCaptured":{},"nextWindow":0,"eventCount":0,"workspace":{},"connected":false,"eventName":"LANGUAGE_SERVER.REQUEST"},"connectionOptions":{"cancellationStrategy":{"_sender":{"folderName":"e9f61e331a2b997e6c7e60d9406fd9c97ff531926e"}}}}, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at getLanguageServerFolderName (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:24:193095)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 2020-09-24 20:27:45: Starting language server, Class name = r, completed in 11ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at getLanguageServerFolderName (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:24:193095)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 2020-09-24 20:27:45: Restarting language server, Class name = r, completed in 12ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at getLanguageServerFolderName (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:24:193095)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 2020-09-24 20:27:45: Failed to restart language server, Class name = r, completed in 12ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at getLanguageServerFolderName (/home/behzad/.vscode-oss/extensions/ms-python.python-2020.9.111407/out/client/extension.js:24:193095)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}

**Comment by jakebailey** [comment]
Pylance is only supported in official builds of VS Code; you appear to be using "VS Code - OSS" from the Arch repos. See https://github.com/microsoft/pylance-release/issues/135#issuecomment-662607952.
