### ISSUE TITLE
Wrong return type from pandas.DataFrame().loc

### ISSUE THREAD

**Issue by wikiped** [microsoft/pylance-release#419]
## Environment data

-   Language Server version: 
  Pylance language server 2020.9.5 (pyright a6a34d5b)
-   OS and version: 
  Windows 10 (2004)
-   Python version (& distribution if applicable, e.g. Anaconda): 
  Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

## Expected behaviour

```
import pandas as pd

def func(values: pd.Series) -> pd.Series:
    return values

df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})

func(df.loc[df.a == 1, "b"])  # should not have any warnings
```

## Actual behaviour
Warning appears:

```
Argument of type "DataFrame" cannot be assigned to parameter "values" of type "Series[Unknown]" in function "func"
  "DataFrame" is incompatible with "Series[Unknown]"Pylance (reportGeneralTypeIssues)
```

## Logs

<details>

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonTipPromptWording'
> conda --version
> pyenv root
> python3.7 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python3.6 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python2 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> py -3.6 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> py -3 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> py -2 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python3 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> py -3.7 "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
Error 2020-09-25 13:04:14: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\UserName\AppData\Roaming\Code\User\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\UserName\AppData\Roaming\Code\User\settings.json')
	at _handleError (D:\Visual Studio Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:706:74)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async v.readText (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:1:495817)
	at async p.doesFileNeedToBeFixed (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:953520)
	at async D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952647
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952593)
	at async p.updateTestSettings (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-09-25 13:04:14: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'd:\WorkspaceFolder\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'd:\WorkspaceFolder\.vscode\settings.json')
	at _handleError (D:\Visual Studio Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:706:74)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async v.readText (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:1:495817)
	at async p.doesFileNeedToBeFixed (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:953520)
	at async D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952647
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952593)
	at async p.updateTestSettings (D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\out\client\extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
> python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" -c "import sys;print(sys.executable)"
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command py and args -3.7 failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command py and args -3 failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command py and args -3.6 failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command py and args -2 failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command python and args  failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-09-25 13:04:15: Detection of Python Interpreter for Command python and args  failed as file  does not exist
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
Python interpreter path: D:\Anaconda\python.exe
Starting Pylance language server.
> pyenv root
> pyenv root
> conda info --json
> conda env list
##########Linting Output - pycodestyle##########
Error 2020-09-25 13:04:20: Failed to get interpreter information for 'C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python3.exe" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\UserName\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\pyvsc-run-isolated.py" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-09-25 13:04:20: Failed to get interpreter information for 'C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python.exe" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\UserName\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\pyvsc-run-isolated.py" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-09-25 13:04:20: Failed to get interpreter information for 'C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python3.exe" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\UserName\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\pyvsc-run-isolated.py" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-09-25 13:04:20: Failed to get interpreter information for 'C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\Users\UserName\AppData\Local\Microsoft\WindowsApps\python.exe" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\UserName\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\pyvsc-run-isolated.py" "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\interpreterInfo.py"'
}
> conda info --json
> conda info --json
> conda env list
##########Linting Output - pylama##########
Error 2020-09-25 13:05:06: getActivatedEnvironmentVariables [Error: Command failed: D:/Anaconda/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" "D:/Visual Studio Code/data/extensions/ms-python.python-2020.8.109390/pythonFiles/printEnvVariables.py"

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `D:/Anaconda/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python "D:\\Visual Studio Code\\data\\extensions\\ms-python.python-2020.8.109390\\pythonFiles\\pyvsc-run-isolated.py" "D:/Visual Studio Code/data/extensions/ms-python.python-2020.8.109390/pythonFiles/printEnvVariables.py"`
}
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\testing_tools\run_adapter.py" discover pytest -- --rootdir "d:\WorkspaceFolder" -s --cache-clear --no-cov
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\testing_tools\run_adapter.py" discover pytest -- --rootdir "d:\WorkspaceFolder" -s --cache-clear --no-cov
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
##########Linting Output - pycodestyle##########
120,101,E,E501:line too long (101 > 100 characters)
##########Linting Output - pylama##########
some_module.py:120:101: [C] E501 line too long (101 > 100 characters) [pycodestyle]
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
##########Linting Output - pycodestyle##########
120,101,E,E501:line too long (101 > 100 characters)
##########Linting Output - pylama##########
some_module.py:120:101: [C] E501 line too long (101 > 100 characters) [pycodestyle]
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" black --line-length 100 --diff --quiet "d:\WorkspaceFolder\some_module.py.9477e8811515f299840223bba6cda662.tmp"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" black --line-length 100 --diff --quiet "d:\WorkspaceFolder\some_module.py.9477e8811515f299840223bba6cda662.tmp"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
##########Linting Output - pycodestyle##########
##########Linting Output - pylama##########
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pycodestyle --max-line-length=100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
> D:\Anaconda\python.exe "D:\Visual Studio Code\data\extensions\ms-python.python-2020.8.109390\pythonFiles\pyvsc-run-isolated.py" pylama --format=parsable "d:\WorkspaceFolder\some_module.py"
cwd: d:\WorkspaceFolder
```
</details>

**Comment by gramster** [comment]
Unfortunately there isn't a great solution here, other than using `df["a"]` instead of `df.a`, or casting the argument to a Series, as the Python typing system isn't yet able to handle dynamic attributes. This is something I have brought up in the typing SIG before and will do so again, as it would be great to have a way to be able to handle such cases. Alternatively maybe one day if we add special case typing extensions to Pylance.

Closing as won't fix for now until there is a technically feasible way of dealing with such cases.
