### ISSUE TITLE
vscode continues to crash, extension reload

### ISSUE THREAD

**Issue by SchumErik** [microsoft/pylance-release#4443]

**Comment by rchiodo** [comment]
Is this the 'pylance' error?

```
2023-05-28 21:24:30.947 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
	at /Users/Erik/.vscode/extensions/ms-python.vscode-pylance-2023.5.40/dist/extension.bundle.js:1:55300
	at _0x510d3a (/Users/Erik/.vscode/extensions/ms-python.vscode-pylance-2023.5.40/dist/extension.bundle.js:1:64725)
	at async oe.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js💯52890)
```

**Comment by karthiknadig** [comment]
That is the I am suspecting is causing the crash.

**Comment by rchiodo** [comment]
@stellahuang95, you should be able to use the tools we use in our dashboard to see what that callstack maps to in the real code.

This file here should be able to find the real stack:

build\automation\map_callstacks.js

As long as you have the map files for build 2023.5.40.

**Comment by rchiodo** [comment]
Sorry I was curious, so I did the mapping myself. Here's what I think is the top of that stack:

```
C:\Users\aku91\source\repos\pyrx>node build\automation\map_callstacks.js "C:\Users\aku91\Downloads\extension.bundle.js.map" 1 55300
{
  source: 'vscode-pylance/src/sharedExtension.ts',
  line: 220,
  column: 90,
  name: null
}
```

Which comes to here:
https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/vscode-pylance/src/sharedExtension.ts#L220

Which doesn't make any sense. Perhaps this python module will be able to map better. 

https://pypi.org/project/sourcemap/

That's what we use in our internal dashboard.

**Comment by cydhhp** [comment]
Still Crash

I try everything about solution.

If uninstall reboot install
It always show this, but this is before settings
![截圖 2023-06-01 12 48 36](https://github.com/microsoft/pylance-release/assets/30332287/73128332-1be2-4f5c-896a-6f98c2c68c16)

always
`
023-05-29 21:36:30.596 [info] Getting sessions for the following scopes: email offline_access openid profile
2023-05-29 21:36:30.596 [trace] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
2023-05-29 21:36:30.596 [info] Got 0 sessions for scopes: email offline_access openid profile
2023-05-29 21:36:36.037 [info] Logging in for the following scopes: email offline_access openid profile
2023-05-29 21:36:41.136 [info] Exchanging login code for token for scopes: email offline_access openid profile
2023-05-29 21:36:46.381 [error] Fetching token failed for scopes (email offline_access openid profile): request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: certificate has expired
2023-05-29 21:36:46.381 [error] Error exchanging code for token (for scopes email offline_access openid profile): Error: Network failure
2023-05-29 21:36:46.381 [error] Error creating session for scopes: email offline_access openid profile Error: Error: Network failure
2023-05-29 21:37:21.044 [error] Fetching token failed for scopes (email offline_access openid profile): request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: certificate has expired
2023-05-29 21:37:21.044 [error] Error exchanging code for token (for scopes email offline_access openid profile): Error: Network failure
2023-05-29 21:37:21.044 [error] Error creating session for scopes: email offline_access openid profile Error: Error: Network failure
2023-05-29 21:37:51.804 [error] Fetching token failed for scopes (email offline_access openid profile): request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: certificate has expired
2023-05-29 21:37:51.804 [error] Error exchanging code for token (for scopes email offline_access openid profile): Error: Network failure
2023-05-29 21:37:51.804 [error] Error creating session for scopes: email offline_access openid profile Error: Error: Network failure
2023-05-29 21:39:21.684 [info] Getting sessions for the following scopes: email offline_access openid profile
2023-05-29 21:39:21.684 [trace] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
2023-05-29 21:39:21.684 [info] Got 0 sessions for scopes: email offline_access openid profile
2023-05-29 21:39:24.955 [info] Logging in for the following scopes: email offline_access openid profile
2023-05-29 21:39:32.391 [info] Exchanging login code for token for scopes: email offline_access openid profile
2023-05-29 21:40:43.049 [error] Fetching token failed for scopes (email offline_access openid profile): request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: certificate has expire
`

**reason: certificate has expire**
But keychain has no about vscode

**Comment by SchumErik** [comment]
Hello, 

not sure how I got into this feed, but my VSCode extension server continues to crash… until - by waiting or continued restarting it finally works. But after a while my whole machine slows down. MAC MBP. Please advise what I should do / if this is the right group for me..


On 1. Jun 2023, at 02:04, Rich Chiodo ***@***.***> wrote:


Sorry I was curious, so I did the mapping myself. Here's what I think is the top of that stack:

C:\Users\aku91\source\repos\pyrx>node build\automation\map_callstacks.js "C:\Users\aku91\Downloads\extension.bundle.js.map" 1 55300
{
  source: 'vscode-pylance/src/sharedExtension.ts',
  line: 220,
  column: 90,
  name: null
}
Which comes to here:
https://github.com/microsoft/pyrx/blob/4f734066a174a67333aa351f6f62d6e266ec7d7d/packages/vscode-pylance/src/sharedExtension.ts#L220

Which doesn't make any sense. Perhaps this python module will be able to map better.

https://pypi.org/project/sourcemap/

That's what we use in our internal dashboard.

**Comment by StellaHuang95** [comment]
Hi @cydhhp, thanks for reporting the issue. In order to address issues effectively, we aim to tackle one issue at a time. Could you please file a new issue at https://github.com/microsoft/vscode? Thanks.

@SchumErik Could you try switching the python language server to Jedi and see if you're still experiencing the same crash? Thanks.

**Comment by SchumErik** [comment]
Hi Stella, 

unfortunately the extension server still crashed w/ Jedi as language server. Here the logs: 

WINDOW:

2023-06-04 12:27:25.847 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-06-04 12:27:26.251 [warning] Settings pattern "security.*" doesn't match any settings
2023-06-04 12:27:26.252 [warning] SettingsEditor2: Settings not included in settingsLayout.ts: interactiveEditor.editMode, accessibility.verbosity.diff-editor, accessibility.verbosity.terminal
2023-06-04 12:27:26.441 [error] Error: The editor could not be opened because the file was not found.
    at lu.cc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2285:93538)
    at async lu.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2285:92524)
    at async e.EditorPanes.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2283:23399)
    at async e.EditorPanes.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2283:21994)
    at async e.EditorPanes.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2283:20897)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:13516
2023-06-04 12:27:28.303 [warning] Settings pattern "security.*" doesn't match any settings
2023-06-04 12:27:29.421 [warning] Settings pattern "security.*" doesn't match any settings
2023-06-04 12:27:30.876 [warning] Settings pattern "security.*" doesn't match any settings
2023-06-04 12:27:31.680 [info] [perf] Render performance baseline is 29ms
2023-06-04 12:27:32.219 [warning] Settings pattern "security.*" doesn't match any settings
2023-06-04 12:27:54.036 [error] IsADirectoryError: [Errno 21] Is a directory: '/': Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:27:58.809 [error] IsADirectoryError: [Errno 21] Is a directory: '/': Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:28:15.203 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
2023-06-04 12:28:15.205 [info] Automatically restarting the extension host.
2023-06-04 12:28:17.662 [error] IsADirectoryError: [Errno 21] Is a directory: '/': Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:28:19.385 [error] IsADirectoryError: [Errno 21] Is a directory: '/': Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:29:46.905 [error] IsADirectoryError: [Errno 21] Is a directory: '/': Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:30:26.291 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-06-04 12:30:31.423 [warning] UNRESPONSIVE extension host: 'ms-python.python' took 83.23181383015552% of 4183.474ms, saved PROFILE here: 'file:///var/folders/f2/28b0gjr94d30gxt79tc_qrsh0000gn/T/exthost-332c29.cpuprofile’



MAIN:

2023-06-04 12:27:25.304 [info] update#setState idle
2023-06-04 12:27:55.309 [info] update#setState checking for updates
2023-06-04 12:27:55.738 [info] update#setState idle
2023-06-04 12:28:15.094 [info] Extension host with pid 7386 exited with code: 6, signal: unknown.
2023-06-04 12:28:15.095 [error] [UtilityProcess id: 1, type: extensionHost, pid: 7386]: crashed with code 6 and reason ‘crashed'



EXTENSION HOST:

2023-06-04 12:27:28.485 [info] Extension host with pid 7386 started
2023-06-04 12:27:28.485 [info] Skipping acquiring lock for /Users/Erik/Library/Application Support/Code/User/workspaceStorage/9b3868f31889efb2221e33472b7c387e.
2023-06-04 12:27:28.565 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-06-04 12:27:28.573 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.black-formatter
2023-06-04 12:27:28.651 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:27:28.724 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-04 12:27:29.245 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2023-06-04 12:27:29.259 [info] ExtensionService#_doActivateExtension ms-python.black-formatter, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:27:29.274 [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:27:29.578 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-06-04 12:27:29.583 [info] ExtensionService#_doActivateExtension vscodevim.vim, startup: true, activationEvent: '*'
2023-06-04 12:27:29.717 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-06-04 12:27:29.780 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-06-04 12:27:29.823 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-06-04 12:27:30.296 [info] Eager extensions activated
2023-06-04 12:27:30.450 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-06-04 12:27:30.453 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-06-04 12:27:54.035 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:27:54.035 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:27:54.689 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:27:54.689 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:27:55.891 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2023-06-04 12:27:55.897 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2023-06-04 12:27:58.808 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:27:58.808 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:28:15.754 [info] Extension host with pid 7561 started
2023-06-04 12:28:15.754 [info] Skipping acquiring lock for /Users/Erik/Library/Application Support/Code/User/workspaceStorage/9b3868f31889efb2221e33472b7c387e.
2023-06-04 12:28:15.795 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-06-04 12:28:15.805 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.black-formatter
2023-06-04 12:28:15.868 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:28:15.918 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-04 12:28:15.928 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-06-04 12:28:15.943 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
2023-06-04 12:28:15.945 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'onNotebook:*'
2023-06-04 12:28:15.951 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2023-06-04 12:28:15.955 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2023-06-04 12:28:16.257 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
2023-06-04 12:28:16.390 [info] ExtensionService#_doActivateExtension ms-python.black-formatter, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:28:16.406 [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'onLanguage:python'
2023-06-04 12:28:16.769 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-06-04 12:28:16.773 [info] ExtensionService#_doActivateExtension vscodevim.vim, startup: true, activationEvent: '*'
2023-06-04 12:28:16.926 [info] Eager extensions activated
2023-06-04 12:28:16.932 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-06-04 12:28:16.934 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-06-04 12:28:17.660 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:28:17.660 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:28:19.384 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:28:19.384 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:29:46.904 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:29:46.904 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:30:45.203 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:30:45.204 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:30:59.140 [warning] ExtHostTextEditorOptions 'setCursorStyle' failed:'
2023-06-04 12:30:59.140 [warning] TextEditor(vs.editor.ICodeEditor:7,$model8) has been disposed
2023-06-04 12:31:08.850 [error] [ms-toolsai.jupyter] provider FAILED
2023-06-04 12:31:08.850 [error] Error: IsADirectoryError: [Errno 21] Is a directory: '/'
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:775869
	at /Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776163
	at Immediate.<anonymous> (/Users/Erik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/extension.node.js:2:776525)
	at process.processImmediate (node:internal/timers:466:21)
2023-06-04 12:31:08.853 [warning] TextEditor is closed/disposed
2023-06-04 12:31:08.853 [warning] TextEditor is closed/disposed
2023-06-04 12:31:08.853 [warning] TextEditor is closed/disposed




Any help greatly appreciated…. 

Best, 
Erik 






On 1. Jun 2023, at 20:43, Stella ***@***.***> wrote:


Hi @cydhhp <https://github.com/cydhhp>, thanks for reporting the issue. In order to address issues effectively, we aim to tackle one issue at a time. Could you please file a new issue at https://github.com/microsoft/vscode? Thanks.

@SchumErik <https://github.com/SchumErik> Could you try switching the python language server to Jedi and see if you're still experiencing the same crash? Thanks.

**Comment by luabud** [comment]
@karthiknadig given this repro's with Jedi, could it be a Python extension issue?

**Comment by karthiknadig** [comment]
@SchumErik Can you use the steps described here to figure out the exact extension causing the issue: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect

**Comment by SchumErik** [comment]
Hello Karthik,Not sure if this helps - tried this several times, and eventually the bisection switches off the Jupiter extension, which means interactive mode does not work anymore (in particular starting an interactive window from a python script with cells starting with # %%), and I no longer can reproduce the problem… Any suggestion how to deal with this (maybe it is the jupyter extension….) Aside from the Jupyter extension I only use the black, pylance and VIM extensions…sent from my mobile device - please excuse brevity and typosOn 5. Jun 2023, at 22:56, Karthik Nadig ***@***.***> wrote:﻿
@SchumErik Can you use the steps described here to figure out the exact extension causing the issue: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect

**Comment by karthiknadig** [comment]
@SchumErik I think that might be a clue that this this needs to be further investigated in jupyter extension. This might be triggering  something that is causing the crash. I will move this issue there to see they can help find anything.
