### ISSUE TITLE
Pylance client: couldn't create connection to server error

### ISSUE THREAD

**Issue by nav9** [microsoft/pylance-release#4485]
I'm reopening this as a new issue since the [earlier one](https://github.com/microsoft/pylance-release/issues/3391) was closed without being resolved.  
   
## Environment data
-   Language Server version: v2023.6.10
-   OS and version: Linux Mint 21.1 Cinnamon. Kernel: 5.15.0-72-generic
-   Python version: Python 3.9.0  via PyEnv.

## Repro Steps
Install PyLance in VS Code 1.78.2. Restart the computer and open VS Code. When the IDE opens, the error is shown as visible in the screenshot below.
  
## Expected behavior
No error should be shown.
  
## Actual behavior

![pylanceError](https://github.com/microsoft/pylance-release/assets/2093933/c135c69b-8479-46ce-8198-9c68dbea1ea5)

## Logs
I didn't see any log. If you'd like me to provide a log, please mention how I can find it. I did however, find some output:  
```
2023-06-11 00:12:37.958 [info] [Info  - 00:12:37] (21519) Pylance language server 2023.6.10 (pyright 7784093a) starting
2023-06-11 00:12:37.959 [info] [Info  - 00:12:37] (21519) Server root directory: /home/nav/.vscode/extensions/ms-python.vscode-pylance-2023.6.10/dist
2023-06-11 00:12:37.959 [info] [Info  - 00:12:37] (21518) Pylance language server 2023.6.10 (pyright 7784093a) starting
2023-06-11 00:12:37.959 [info] [Info  - 00:12:37] (21519) Starting service instance "myprog"
2023-06-11 00:12:37.959 [info] [Info  - 00:12:37] (21518) Server root directory: /home/nav/.vscode/extensions/ms-python.vscode-pylance-2023.6.10/dist
2023-06-11 00:12:37.964 [info] [Info  - 00:12:37] (21518) Starting service instance "myprog"
2023-06-11 00:12:37.967 [info] [Error - 00:12:37] Server initialization failed.
2023-06-11 00:12:37.967 [info] Error: command 'pyright.createtypestub' already exists
	at e.ExtHostCommands.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123788)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:23226)
	at t.ExecuteCommandFeature.register (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2106221)
	at t.ExecuteCommandFeature.initialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2105800)
	at S.initializeFeatures (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2057711)
	at S.doInitialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2045260)
	at async S.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2042275)
	at async h.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:37203)
2023-06-11 00:12:37.967 [info] [Error - 00:12:37] Pylance client: couldn't create connection to server.
2023-06-11 00:12:37.967 [info] Error: command 'pyright.createtypestub' already exists
	at e.ExtHostCommands.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123788)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:23226)
	at t.ExecuteCommandFeature.register (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2106221)
	at t.ExecuteCommandFeature.initialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2105800)
	at S.initializeFeatures (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2057711)
	at S.doInitialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2045260)
	at async S.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2042275)
	at async h.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:37203)
2023-06-11 00:12:37.967 [info] [Error - 00:12:37] Sending notification textDocument/didOpen failed.
2023-06-11 00:12:37.967 [info] Error: command 'pyright.createtypestub' already exists
	at e.ExtHostCommands.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123788)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:23226)
	at t.ExecuteCommandFeature.register (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2106221)
	at t.ExecuteCommandFeature.initialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2105800)
	at S.initializeFeatures (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2057711)
	at S.doInitialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2045260)
	at async S.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2042275)
	at async h.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:37203)
2023-06-11 00:12:37.969 [info] [Error - 00:12:37] Sending document notification textDocument/didOpen failed
2023-06-11 00:12:37.969 [info] Error: command 'pyright.createtypestub' already exists
	at e.ExtHostCommands.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123788)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:23226)
	at t.ExecuteCommandFeature.register (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2106221)
	at t.ExecuteCommandFeature.initialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2105800)
	at S.initializeFeatures (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2057711)
	at S.doInitialize (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2045260)
	at async S.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:2042275)
	at async h.start (/home/nav/.vscode/extensions/ms-python.python-2023.8.0/out/client/extension.js:2:37203)
2023-06-11 00:12:37.980 [info] [Info  - 00:12:37] (21519) Setting pythonPath for service "myprog": "/home/nav/.pyenv/versions/3.9.0/bin/python"
2023-06-11 00:12:38.003 [info] [Info  - 00:12:38] (21519) Assuming Python version 3.9
2023-06-11 00:12:38.080 [info] [Info  - 00:12:38] (21519) Found 20 source files
2023-06-11 00:12:38.339 [info] [Info  - 00:12:38] (21519) Background analysis(1) root directory: /home/nav/.vscode/extensions/ms-python.vscode-pylance-2023.6.10/dist
2023-06-11 00:12:38.339 [info] [Info  - 00:12:38] (21519) Background analysis(1) started
2023-06-11 00:12:38.370 [info] [Info  - 00:12:38] (21519) Indexer background runner(2) root directory: /home/nav/.vscode/extensions/ms-python.vscode-pylance-2023.6.10/dist (index)
2023-06-11 00:12:38.370 [info] [Info  - 00:12:38] (21519) Indexing(2) started
2023-06-11 00:12:38.832 [info] [Info  - 00:12:38] (21519) scanned(2) 102 files over 1 exec env
2023-06-11 00:12:40.728 [info] [Info  - 00:12:40] (21519) indexed(2) 65 files over 1 exec env
2023-06-11 00:12:40.738 [info] [Info  - 00:12:40] (21519) Indexing finished(2).
```

**Comment by navels** [comment]
I just encountered this as well, switched to the pre-release versions of the ms python and pylance extensions and that appears to have resolved it . . . knock on wood.

**Comment by mlove4u** [comment]
I have associated two computers with my account (A: Intel CPU (macOS), B: Apple M2), and I have enabled automatic synchronization. I experience this issue on computer A, but not on computer B. (Previously, I had one account associated with two Intel CPU machines (macOS), and I did not encounter any issues.)

**Comment by bschnurr** [comment]
did you have the pryight extension installed as well?

**Comment by nav9** [comment]
I did not have any pryight extension installed. As navels suggested, switching to the pre-release version solved it. Anyway, I now have VS code 1.80.1 and pylance v2023.7.30, and didn't encounter any issue.
