### ISSUE TITLE
No intellisense

### ISSUE THREAD

**Issue by AxelVoitier** [microsoft/pylance-release#4593]
# Behaviour

When loading the application, after a few seconds a popup error appears saying Intellisense for python cannot work because of an error.

By looking at the Python output, I can see it fails a few times during what seems to be interpreters discovery. First it output "Unknown option: -I" errors with system-installed python2 interpreters. Then another similar error ("Invalid command line arguments.") with a micropython interpreter from pyenv.

And later another error about an invalid version for that micropython interpreter.

From that, intellisense is not working, eventhough I don't currently use any of these interpreters in my workspace actually. Leading to basically a "broken" development environment.

That behaviour is new since latest updates. Though, just rolling back python extension version by 1 or 2 versions does not fix the issue. I suspect the errors could have been here before, but now it would prevent latest intellisense to work at all, maybe?

Or it is due to something completely different. Unfortunately, I cannot confirm my interpretation of the issue as I cannot really remove the python2 interpreter as it is the system one, and I understand it is still used by many system packages.
And I am not rely willing to remove or update the micropython one, as this one is related to an embedded device I use from time to time.

## Expected vs. Actual

Either that such interpreter discovery errors do not break all important features of this extension for other interpreters actively used.
Or that there would be a way to exclude some interpretters (only option middly related to that is to exclude some pyenv environment from Jupyter, which is ineffective here).

Actual behaviour is a "wide" loss of functionality (ie. I can still edit, but for instance I already spent hours debugging a stupid issue in my code that intellisense would have otherwise identified in a snap...), due to not used interpreters.

## Steps to reproduce:

1. Have some python2 or micropython interpreters installed.
2. Start the application.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.3
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Pyenv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>VS IntelliCode</code> in the <code>Output</code> panel
</summary>

<p>

```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
vs-intellicode-python was passed a model: {}.
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at e.CommandService._tryExecuteCommand (vscode-file://vscode-app/snap/codium/329/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1514:15997)
    at e.CommandService.executeCommand (vscode-file://vscode-app/snap/codium/329/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1514:15879)
Error while activating Python: {}
```

</p>

</details>
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-07-11 10:59:24.257 [info] Telemetry level is off
2023-07-11 10:59:24.257 [info] Experiments are disabled, only manually opted experiments are active.
2023-07-11 10:59:24.368 [info] Test server listening.
2023-07-11 10:59:24.394 [info] > conda info --json
2023-07-11 10:59:24.552 [info] Python interpreter path: ~/.pyenv/versions/3.11.3/bin/python
2023-07-11 10:59:25.041 [info] Found: /bin/python2 --> /bin/python2.7
2023-07-11 10:59:25.057 [info] Found: /bin/python2.7 --> /bin/python2.7
2023-07-11 10:59:25.216 [info] Found: /bin/python3 --> /bin/python3.8
2023-07-11 10:59:25.218 [info] Found: /bin/python3.8 --> /bin/python3.8
2023-07-11 10:59:25.328 [info] > ~/.pyenv/versions/3.10.11/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:25.332 [info] Found: /usr/bin/python2 --> /usr/bin/python2.7
2023-07-11 10:59:25.334 [info] Found: /usr/bin/python2.7 --> /usr/bin/python2.7
2023-07-11 10:59:25.336 [info] Found: /usr/bin/python3 --> /usr/bin/python3.8
2023-07-11 10:59:25.336 [info] Found: /usr/bin/python3.8 --> /usr/bin/python3.8
2023-07-11 10:59:25.387 [info] > ~/.pyenv/versions/3.10.5/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:25.418 [info] > ~/.pyenv/versions/3.10.9/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:25.464 [info] > ~/.pyenv/versions/3.11.1/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:25.478 [info] > ~/.pyenv/versions/3.11.3/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:26.829 [info] > ~/.pyenv/versions/3.8.16/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:27.613 [info] > ~/.pyenv/versions/3.9.16/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
[...]
2023-07-11 10:59:28.297 [info] > ~/.pyenv/versions/micropython-1.19.1/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:28.325 [error] [Error: Command failed: /home/lexa/.pyenv/versions/micropython-1.19.1/bin/python -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
Invalid command line arguments. Use -h option for help.

	at ChildProcess.exithandler (node:child_process:409:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)] {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/home/lexa/.pyenv/versions/micropython-1.19.1/bin/python -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py'
}
2023-07-11 10:59:28.386 [info] > ~/.pyenv/versions/3.11.3/envs/py-project-py3.11.3/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
[...]
2023-07-11 10:59:29.386 [info] > ~/.virtualenvs/lookups/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.400 [info] > ~/.virtualenvs/lookups-0.3.0/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.515 [info] > ~/.virtualenvs/lookups-3.10/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.529 [info] > ~/.virtualenvs/openide-examples/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.593 [info] > ~/.virtualenvs/openide-py3.9.16/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.673 [info] > ~/.virtualenvs/openide-release/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.772 [info] > ~/.virtualenvs/openide-rescue/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
[...]
2023-07-11 10:59:29.938 [info] > ~/.virtualenvs/pynand2tetris/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.975 [info] > ~/.virtualenvs/pynand2tetris-nollvm/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:29.995 [info] > ~/.virtualenvs/qmk/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.030 [info] > ~/.virtualenvs/rpi-pio/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
[...]
2023-07-11 10:59:30.086 [info] > /bin/python2 -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.100 [info] > /bin/python3 -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.118 [info] > /usr/bin/python2 -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.136 [info] > /usr/bin/python3 -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.141 [warning] [Error: Command failed: /bin/python2 -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:409:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)] {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/bin/python2 -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py'
}
2023-07-11 10:59:30.141 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2023-07-11 10:59:30.153 [info] > /bin/python2 ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.154 [warning] [Error: Command failed: /usr/bin/python2 -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:409:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)] {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/usr/bin/python2 -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py'
}
2023-07-11 10:59:30.154 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2023-07-11 10:59:30.167 [info] > /usr/bin/python2 ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.357 [info] > ~/.pyenv/versions/micropython-1.19.1/bin/python -I ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
2023-07-11 10:59:30.363 [error] [Error: Command failed: /home/lexa/.pyenv/versions/micropython-1.19.1/bin/python -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py
Invalid command line arguments. Use -h option for help.

	at ChildProcess.exithandler (node:child_process:409:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)] {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/home/lexa/.pyenv/versions/micropython-1.19.1/bin/python -I /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /home/lexa/.vscode-oss/extensions/ms-python.python-2023.12.0/pythonFiles/interpreterInfo.py'
}
2023-07-11 10:59:30.450 [info] Starting Pylance language server.
2023-07-11 10:59:30.456 [info] Found: /bin/python2 --> /bin/python2.7
2023-07-11 10:59:30.460 [info] Found: /bin/python2.7 --> /bin/python2.7
2023-07-11 10:59:30.464 [info] Found: /bin/python3 --> /bin/python3.8
2023-07-11 10:59:30.465 [info] Found: /bin/python3.8 --> /bin/python3.8
2023-07-11 10:59:30.490 [info] Found: /usr/bin/python2 --> /usr/bin/python2.7
2023-07-11 10:59:30.491 [info] Found: /usr/bin/python2.7 --> /usr/bin/python2.7
2023-07-11 10:59:30.493 [info] Found: /usr/bin/python3 --> /usr/bin/python3.8
2023-07-11 10:59:30.494 [info] Found: /usr/bin/python3.8 --> /usr/bin/python3.8
2023-07-11 10:59:30.749 [error] Invalid version for /home/lexa/.pyenv/versions/micropython-1.19.1/bin/python: {"name":"micropython-1.19.1","location":"/home/lexa/.pyenv/versions/micropython-1.19.1","kind":"global-pyenv","executable":{"filename":"/home/lexa/.pyenv/versions/micropython-1.19.1/bin/python","sysPrefix":"","ctime":1669931344374,"mtime":1665003120155},"display":"Python ('micropython-1.19.1')","version":{"major":-1,"minor":-1,"micro":-1,"release":{"level":"final","serial":-1}},"arch":1,"distro":{"org":"micropython"},"source":[],"id":"/home/lexa/.pyenv/versions/micropython-1.19.1/bin/python","detailedDisplayName":"Python ('micropython-1.19.1': pyenv)"}
2023-07-11 10:59:31.644 [info] Extension search path: /home/lexa/.vscode-oss/extensions
2023-07-11 10:59:31.646 [info] Extension search path: /home/lexa/.vscode-oss/extensions
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

linting
• flake8Args: "<placeholder>"
• flake8Enabled: true
• mypyArgs: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"

testing
• pytestEnabled: true

```

</p>
</details>

**Comment by karrtikr** [comment]
Meanwhile can you upload:

<details>

<summary>Output for <code>Python language server</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python language server</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
If the interpreter isn't set, Pylance won't work for most stuff. Only things like `import sys` will find modules.

The log for Pylance should tell us if we got an interpreter or not.

**Comment by rchiodo** [comment]
Can you also include what version of VS code you're on? This might be this issue here:
https://github.com/microsoft/vscode/issues/187312
