### ISSUE TITLE
Python LSP stops after a few minutes

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/pylance-release#4627]
I am running a remote development environment which connects from a windows 11 machine to a linux server (SLES12).
- Pylance version: 2023.7.20
- Python version: using anaconda to manage py3.9 environment
- Python extension: 2023.12.0
- VScode: 1.80

When I open a python file, the python language server works fine (showing autocompletion , go to definition, etc. ) for a couple of minutes and then stops. I have to restart the language server manually to get the autocompletion for a few minutes again and then the same thing happens.

Below you can see the log of the language server

```
2023-07-18 16:22:41.429 [info] [Info  - 4:22:41 PM] (14825) Pylance language server 2023.7.20 (pyright 74d8f3c4) starting
2023-07-18 16:22:41.445 [info] [Info  - 4:22:41 PM] (14825) Server root directory: /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.20/dist
2023-07-18 16:22:41.445 [info] [Info  - 4:22:41 PM] (14825) Starting service instance "1_variation_sil2sim"
2023-07-18 16:22:41.500 [info] [Info  - 4:22:41 PM] (14825) Setting pythonPath for service "1_variation_sil2sim": "/nfs/site/home/adavoody/.conda/envs/adavoody/bin/python"
2023-07-18 16:22:41.510 [info] [Warn  - 4:22:41 PM] (14825) stubPath /nfs/site/home/adavoody/workspace/1_variation_sil2sim/typings is not a valid directory.
2023-07-18 16:22:41.547 [info] [Info  - 4:22:41 PM] (14825) Assuming Python version 3.11
2023-07-18 16:22:42.001 [info] [Info  - 4:22:42 PM] (14825) Found 22 source files
2023-07-18 16:22:42.029 [info] [Info  - 4:22:42 PM] (14825) Background analysis(1) root directory: /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.20/dist
2023-07-18 16:22:42.029 [info] [Info  - 4:22:42 PM] (14825) Background analysis(1) started
2023-07-18 16:22:42.592 [info] [Info  - 4:22:42 PM] (14825) Indexer background runner(2) root directory: /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.20/dist (index)
2023-07-18 16:22:42.592 [info] [Info  - 4:22:42 PM] (14825) Indexing(2) started
2023-07-18 16:22:44.639 [info] [Info  - 4:22:44 PM] (14825) [IDX(2)] Long operation: scan packages /nfs/site/home/adavoody/workspace/1_variation_sil2sim (2245ms)
2023-07-18 16:22:44.639 [info] [Info  - 4:22:44 PM] (14825) scanned(2) 367 files over 1 exec env
2023-07-18 16:22:50.314 [info] [Info  - 4:22:50 PM] (14825) [BG(1)] Long operation: checking: /nfs/site/disks/MHC/src/process_data.py (7194ms)
2023-07-18 16:22:50.315 [info] [Info  - 4:22:50 PM] (14825) [BG(1)] Long operation: analyzing: /nfs/site/disks/MHC/src/process_data.py (7721ms)
2023-07-18 16:22:54.229 [info] [Info  - 4:22:54 PM] (14825) [IDX(2)] Long operation: index execution environment /nfs/site/home/adavoody/workspace/1_variation_sil2sim (9407ms)
2023-07-18 16:22:54.453 [info] [Info  - 4:22:54 PM] (14825) [IDX(2)] Long operation: index packages /nfs/site/home/adavoody/workspace/1_variation_sil2sim (9639ms)
2023-07-18 16:22:54.453 [info] [Info  - 4:22:54 PM] (14825) indexed(2) 246 files over 1 exec env
2023-07-18 16:22:54.493 [info] [Info  - 4:22:54 PM] (14825) Indexing finished(2).
2023-07-18 16:24:28.872 [info] [Info  - 4:24:28 PM] Connection to server got closed. Server will restart.
2023-07-18 16:24:28.872 [info] true
2023-07-18 16:24:29.234 [info] [Info  - 4:24:29 PM] (16868) Pylance language server 2023.7.20 (pyright 74d8f3c4) starting
2023-07-18 16:24:29.234 [info] [Info  - 4:24:29 PM] (16868) Server root directory: /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.20/dist
2023-07-18 16:24:29.243 [info] [Info  - 4:24:29 PM] (16868) Starting service instance "1_variation_sil2sim"
2023-07-18 16:24:29.600 [info] [Info  - 4:24:29 PM] (16868) Background analysis(1) root directory: /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.20/dist
2023-07-18 16:24:29.602 [info] [Info  - 4:24:29 PM] (16868) Background analysis(1) started
```

**Comment by StellaHuang95** [comment]
Thanks for the issue. Could you also share the entire logs or the logs right before pylance stops?

**Comment by amirhosseindavoody** [comment]
I think I copied the entire logs under python language server section. There are only a few minutes before the issue happens, so the logs are pretty short. If I am looking at the wrong places show me where to get all the logs.

**Comment by rchiodo** [comment]
I believe we need this setting changed to 'trace'? It looks like it's not set to trace at the moment.

```json
"python.analysis.logLevel" : "trace"
```

That should show more information about why it suddenly stopped.

**Comment by amirhosseindavoody** [comment]
Here is the logs after setting the `logLevel` flag to `trace`: [log.txt](https://github.com/microsoft/pylance-release/files/12114858/log.txt)

**Comment by rchiodo** [comment]
Okay I guess that didn't show anything else. Just that the connection was dropped for some reason. We'll likely have to add more logging. 

This option here (if we set it) might help track down what the problem might be.
https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/client/src/common/client.ts#L368

There is something suspicious though. This error here:
```
2023-07-20 17:05:40.546 [info] o [Error]: Unhandled method python/isTrustedWorkspace
    at /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.30/dist/vendor.bundle.js:2:1203703
    at ie (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.30/dist/vendor.bundle.js:2:1203997)
    at /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.30/dist/vendor.bundle.js:2:1198756
    at Immediate.<anonymous> (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.30/dist/vendor.bundle.js:2:1198776)
    at processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
```

That tells me that the client side of the extension wasn't created correctly.

@amirhosseindavoody can you share your settings.json for the remote and local machines?

**Comment by amirhosseindavoody** [comment]
Sure, here are the json settings:

[local-user-settings.txt](https://github.com/microsoft/pylance-release/files/12130859/local-user-settings.txt)
[workspace-settings.txt](https://github.com/microsoft/pylance-release/files/12130860/workspace-settings.txt)
[remote-settings.txt](https://github.com/microsoft/pylance-release/files/12130861/remote-settings.txt)

**Comment by rchiodo** [comment]
Can you tell us the version of the python and pylance extensions for both remote and local? 

And I assume you're using SSH to connect to the linux machine?

**Comment by amirhosseindavoody** [comment]
Yes, I am using ssh.

Both Local and Remote are:
- Python: v2023.12.0
- Pylance: v2023.7.30

**Comment by escummy** [comment]
Have you tried Increasing Memory Limit? Just try to open your VS Code settings (File > Preferences > Settings), search for "Pylance Memory Limit," and set a higher value (For example `8192MB`).

> On the other hand, `disable extensions` temporarily to check if any extension conflicts are causing the issue.

**Comment by rchiodo** [comment]
Not sure where 'Pylance memory limit' is found. I don't see that in my settings.

However, there is a way to increase the memory allowed by VS code. See this comment here:
https://github.com/microsoft/pylance-release/issues/4121#issuecomment-1479713013

This tells VS code to start the node process for pylance (or any other node process it starts) with a higher memory limit.

That being said, I don't think @amirhosseindavoody's issue is an out of memory problem. We'd see that in the logs. It's more like the connection is timing out.

**Comment by escummy** [comment]
Uhm maybe, because I though about update Pylance and Python Extension to ensure that you are using the latest versions of Pylance and the Python extension for Visual Studio Code, because could be going to the Extensions view in VS Code, search for "Pylance" and "Python," and click the "Update" button if updates are available.

Also is easy to check increasing server timeout in your VS Code settings for the language server to see if it helps with the issue:

```json
"python.languageServer": "Pylance",
"python.analysis.extraPaths": ["/nfs/site/home/adavoody/.conda/envs/adavoody/lib/python3.9/site-packages"],
````

I am agree about the resource utilization, in some cases the remote development environment has sufficient resources (CPU, memory, etc.) to handle the language server and your codebase. If the resources are limited, I would consider upgrading or optimizing your environment.

**Comment by Newtoniano** [comment]
It's possible it's a timeout issue, since in my logs I've got a few long operations running before the restart happened. Sometimes analyzing, renaming, saving, deleting and similar operations on files get stuck or take a long time for no good reason. Not sure if the issue is pylance or something else here.
```
2023-08-17 14:22:04.261 [info] [Info  - 2:22:04 PM] (1433053) [BG(2)] Long operation: checking: /home/ubuntu/projects/algotrading/pairs-trading/crypto_btc_eth_test/PairsTrading.ipynb:pylance-notebook-cell:Y125sdnNjb2RlLXJlbW90ZQ==.py (12617ms)
2023-08-17 14:22:04.261 [info] [Info  - 2:22:04 PM] (1433053) [BG(2)] Long operation: analyzing: /home/ubuntu/projects/algotrading/pairs-trading/crypto_btc_eth_test/PairsTrading.ipynb:pylance-notebook-cell:Y125sdnNjb2RlLXJlbW90ZQ==.py (12617ms)
2023-08-17 14:22:07.159 [info] [Info  - 2:22:07 PM] (1433053) [BG(2)] Long operation: analyzing: /home/ubuntu/projects/algotrading/pairs-trading/crypto_btc_eth_test/PairsTrading.ipynb:pylance-notebook-cell:pylancePrefixCell.py (15550ms)
2023-08-17 14:25:23.030 [info] [Info  - 2:25:23 PM] Connection to server got closed. Server will restart.
2023-08-17 14:25:23.031 [info] true
2023-08-17 14:25:23.587 [info] [Info  - 2:25:23 PM] (1455940) Pylance language server 2023.8.30 (pyright 634c8074) starting
````

**Comment by ivirabyan** [comment]
I also think it's a timeout issue, when I use "Go to Symbol in workspace" it sometimes takes very long, and never finds anything. And in the logs there's the same `Connection to server got closed. Server will restart.`. And it just stops working. And I have to manually restart the server or reload the window in order to make it work.

**Comment by ivirabyan** [comment]
It turned out to be a memory issue, looks like pylance was getting killed due to out of memory.
Once I increased memory in Docker desktop settings the issue is gone

**Comment by judej** [comment]
Thanks for the update @ivirabyan, glad the issue was resolved.

**Comment by dss010101** [comment]
> It turned out to be a memory issue, looks like pylance was getting killed due to out of memory. Once I increased memory in Docker desktop settings the issue is gone

how do you do this in docker desktop?  im seeing similar issues recently...and my code base is not large at all

**Comment by ivirabyan** [comment]
It's in the docker desktop settings, you can configure how much memory, cpu, disk space to use
