### ISSUE TITLE
Internal Error with `TypeVarTuple`

### ISSUE THREAD

**Issue by janekb04** [microsoft/pylance-release#4630]
## Environment data

-   Language Server version: `Pylance language server 2023.7.20 (pyright 74d8f3c4)`
-   OS and version: `Window 11 22H2`
-   Python version: `Python 3.10.6`

## Code Snippet

```python
from typing import Generic
from typing_extensions import TypeVarTuple, Unpack


Ts = TypeVarTuple("Ts")


class Foo(Generic[Unpack[Ts]]):
    def __init__(self, *args: Unpack[Ts]):
        args[0].bar # NOTE: removing `.bar` stops the error

```

## Expected behavior

No errors.

## Actual behavior

```
An internal error occurred while type checking file "test.py": RangeError: Maximum call stack size exceeded
    at mt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:574649)
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589158)
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589147)
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589147)
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589147)
    ...
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589147)
    at bt (/root/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2023.7.20/dist/pyright.bundle.js:1:589147)
Pylance
```

## Logs

Will add logs if needed.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release of pyright and a future release of pylance.
