### ISSUE TITLE
Language server is not starting

### ISSUE THREAD

**Issue by BeetMacol** [microsoft/pylance-release#4640]
## The issue

The language server does not seem to start on any of the reported versions (2023.7.10+). IntelliSense does not show up, hovering over identifiers does not bring up any pop up.

## Workaround

Downgrade Pylance to 2023.6.40.

## Environment data

-   Language Server version: 2023.7.10; 2023.7.20; 2023.7.30
-   OS and version: Arch Linux x86_64 with Linux 6.4.4
-   Python version: Python 3.11.3
-   Python related settings:
```
"python.analysis.logLevel": "Trace",
"python.defaultInterpreterPath": "/bin/python3",
"python.languageServer": "Pylance",
```

### Python Language Server

On version 2023.6.40 and lower, a lot of logs appear in this output. For the new versions, only the license text shows up.

### Python

Full logs:
```
2023-07-22 20:30:04.986 [info] Test server listening.
2023-07-22 20:30:04.986 [info] Python interpreter path: /bin/python3
2023-07-22 20:30:05.057 [info] Starting Pylance language server.
```

### VS IntelliCode

IntelliCode, unlike the Python extension, detects and reports the problem. First, a pop up appears with the following message:
```
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.
```
The logs also contain an error, but may not be really helpful in solving the problem:
```
[...]
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at e.CommandService.k (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1512:13402)
    at e.CommandService.executeCommand (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1512:13318)
Error while activating Python: {}
```

**Comment by rchiodo** [comment]
Thanks for the issue. What is your version of the python extension? This might be caused by an older python extension trying to work with a newer pylance extension.

**Comment by rchiodo** [comment]
And what do you mean by this statement:

```
For the new versions, only the license text shows up.
```

Can you be more specific? What license text shows up?

**Comment by mikey-boy** [comment]
I experienced the same issues, here's my environment:
Language Server version: 2023.7.10; 2023.7.20; 2023.7.30
    OS and version: Arch Linux x86_64 with Linux 6.4.4
    Python version: Python 3.11.3
    Python related settings:

**Comment by mikey-boy** [comment]
I experienced the same issues, here's my environment:
- Language Server version: 2023.7.40
- Python Extension version: 2023.12.0
- OSS Code version: 1.79.2
- OS and version: Arch Linux x86_64 with Linux 6.4.6
- Python version: Python 3.11.3

And by license text OP is referring to this:
```
2023-07-31 21:05:54.445 [info] (Client) You may install and use any number of copies ... or transfer the software or this agreement to any third party.
```

**Comment by rchiodo** [comment]
I believe Pylance doesn't work with the OSS version of VS code. The license prevents this:
https://marketplace.visualstudio.com/items/ms-python.vscode-pylance/license.

You might have to switch to using Pyright instead.

**Comment by johnmwu** [comment]
For posterity, I am also seeing this issue on Arch Linux.

**Comment by rchiodo** [comment]
@johnmwu you might be hitting this issue here (if you're using the official VS code): https://github.com/microsoft/pylance-release/issues/5084

**Comment by Gorddd** [comment]
Switching Color Theme to Dark+ may help

**Comment by krisutofu** [comment]
For anyone, who initially installed Code OSS like me (not knowing the differences) Pylyzer is another language server for Python which is usable with Code OSS.
