### ISSUE TITLE
Can't find and install pylance

### ISSUE THREAD

**Issue by Mr-Pepe** [microsoft/pylance-release#483]
When switching language server to Pylance, I see a popup stating that Pylance is not installed and that I should click yes to get to the Pylance page. However, the page does not open after clicking yes. I can also not find Pylance when searching for it in the extensions pane.

## Environment data

Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-23T22:26:38.399Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.67-1-MANJARO

## Expected behaviour

The Pylance page opens and I can install it.

## Actual behaviour

The Pylance page does not open.

## Logs
From developer tools:

Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at /home/felipe/.vscode…ent/extension.js:47
	at m (/home/felipe/.vscode…ent/extension.js:47)
	at e (/home/felipe/.vscode…ent/extension.js:47)
	at Object.t.plan (/home/felipe/.vscode…ent/extension.js:47)
	at /home/felipe/.vscode…ent/extension.js:47
	at e._get (/home/felipe/.vscode…ent/extension.js:47)
	at e.getTagged (/home/felipe/.vscode…ent/extension.js:47)
	at e.getNamed (/home/felipe/.vscode…ent/extension.js:47)
	at a.get (/home/felipe/.vscode…ent/extension.js:56)
	at C.createRefCountedServer (/home/felipe/.vscode…ent/extension.js:47)
	at processTicksAndRejections (internal/process/task_queues.js:94)
	at async C.activate (/home/felipe/.vscode…ent/extension.js:47)
	at async Promise.all (/usr/lib/code/out/vs…r/workbench/index 4)
	at async y.activateWorkspace (/home/felipe/.vscode…ent/extension.js:47)
﻿
​

**Comment by jakebailey** [comment]
Are you using an official build of VS Code, or one out of the manjaro repos? To find it, you can also open the extensions tab and search for Pylance.

Would potentially be fixed by microsoft/vscode-python#14264 (though it's not perfectly related). This is technically a core extension issue, but I'll leave it here for now.

**Comment by Mr-Pepe** [comment]
I use VS Code from the Manjaro repos and I can't find Pylance when I search for it in the extensions tab (neither "pylance" nor "ms-python.vscode-pylance" works).

I'll try with a different build.

**Comment by Mr-Pepe** [comment]
After installing visual-studio-code-bin from the AUR, I can find and install Pylance.

**Comment by jakebailey** [comment]
Weird, it should be searchable regardless. Either way, we can't support running in unofficial builds and installing from the AUR worked, so I'll close this.

**Comment by kopp** [comment]
I use the Arch Linux `code` package.  I also could not find it in the market place.  I could, though, download the extension as VSIX file and then install it.
Installing by just opening the file did not work, but in my extensions overview I could select "..." > "Install von VSIX..." and install it.

When I then look into the Extension Host Logs, I find

```
[2020-10-19 20:40:37.755] [exthost] [error] Activating extension ms-python.vscode-pylance failed due to an error:
[2020-10-19 20:40:37.756] [exthost] [error] Error: You may only use the Pylance extension with Visual Studio Code, Visual Studio or Xamarin Studio software
to help you develop and test your applications.
The software is licensed, not sold.
This agreement only gives you some rights to use the software.
Microsoft reserves all other rights
You may not work around any technical limitations in the software;
reverse engineer, decompile or disassemble the software
remove, minimize, block or modify any notices of Microsoft or 
its suppliers in the software share, publish, rent, or lease 
the software, or provide the software as a stand-alone hosted as solution for others to use.
```

**Comment by kopp** [comment]
In the case that it's useful, here is the rest of the logs:

```
[2020-10-19 20:40:37.755] [exthost] [error] Activating extension ms-python.vscode-pylance failed due to an error:
[2020-10-19 20:40:37.756] [exthost] [error] Error: You may only use the Pylance extension with Visual Studio Code, Visual Studio or Xamarin Studio software
to help you develop and test your applications.
The software is licensed, not sold.
This agreement only gives you some rights to use the software.
Microsoft reserves all other rights
You may not work around any technical limitations in the software;
reverse engineer, decompile or disassemble the software
remove, minimize, block or modify any notices of Microsoft or 
its suppliers in the software share, publish, rent, or lease 
the software, or provide the software as a stand-alone hosted as solution for others to use.
	at /home/skunk/.vscode-oss/extensions/ms-python.vscode-pylance-2020.10.1/dist/extension.bundle.js:1:33467
	at /home/skunk/.vscode-oss/extensions/ms-python.vscode-pylance-2020.10.1/dist/extension.bundle.js:1:33486
	at Generator.next (<anonymous>)
	at /home/skunk/.vscode-oss/extensions/ms-python.vscode-pylance-2020.10.1/dist/extension.bundle.js:1:31099
	at new Promise (<anonymous>)
	at _0x235f1d (/home/skunk/.vscode-oss/extensions/ms-python.vscode-pylance-2020.10.1/dist/extension.bundle.js:1:30296)
	at _0x176030.activate (/home/skunk/.vscode-oss/extensions/ms-python.vscode-pylance-2020.10.1/dist/extension.bundle.js:1:31953)
	at Function._callActivateOptional (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:927:841)
	at Function._callActivate (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:927:492)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:841
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
[2020-10-19 20:40:40.001] [exthost] [error] [ms-python.python] provider FAILED
[2020-10-19 20:40:40.003] [exthost] [error] Error: [ms-python.python]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
	at a (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:99)
	at Object.t.checkProposedApiEnabled (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:567)
	at Object.get activeNotebookEditor [as activeNotebookEditor] (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1003:116)
	at u.get activeNotebookEditor [as activeNotebookEditor] (/home/skunk/.vscode-oss/extensions/ms-python.python-2020.9.114305/out/client/extension.js:54:383170)
	at g.provideCodeLenses (/home/skunk/.vscode-oss/extensions/ms-python.python-2020.9.114305/out/client/extension.js:56:230947)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:671
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:51:976
	at new Promise (<anonymous>)
	at Object.t.asPromise (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:51:948)
	at _.provideCodeLenses (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:642)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:753:370
	at K._withAdapter (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:10)
	at K.$provideCodeLenses (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:753:348)
	at m._doInvokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870:464)
	at m._invokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870:156)
	at m._receiveRequest (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:868:766)
	at m._receiveOneMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:867:623)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:865:691
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1059:179
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:451)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:489
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at p.acceptChunk (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:851)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:203
	at Socket.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by jakebailey** [comment]
Pylance is not licensed for use in unofficial builds; that message is expected when pulling `code` from the Arch repos as it is not "VS Code". The alternative for Arch is building `visual-studio-code-bin` from the AUR, which pulls an official build.

**Comment by Mr-Pepe** [comment]
Could you please mention that on the marketplace site? That might save some people a headache.

**Comment by jakebailey** [comment]
Sure, we can add it to the readme or add a troubleshooting section that lists this.

**Comment by MitchTalmadge** [comment]
> Pylance is not licensed for use in unofficial builds

Hey @jakebailey, it looks like this thread has garnered a lot of attention [on Reddit](https://www.reddit.com/r/linux/comments/k0s8qw) today, and I think a lot of people including myself are wondering what the rationale was for only licensing Pylance for official builds. I believe your team is well within their rights to do this, I am just a bit curious is all. Are you able to shed some light on this? Thanks and have a wonderful day :)

**Comment by subnut** [comment]
Ping @jakebailey

**Comment by judej** [comment]
@subnut, We have shared our reason for licensing Pylance for use only in Microsoft products and services in issue #4. We are currently working on further clarifying the answers to this and other questions in a FAQ. 
Thanks

**Comment by DannyJJK** [comment]
@judej Embrace, extend, and extinguish

**Comment by chic-luke** [comment]
Far from the first time any of this happens. Let it be a reminder that Vscode is not how free software is done. I have already switched to something else since I take open source seriously, as should anyone that cares about open source.

**Comment by major-mayer** [comment]
Just stumbled across this, because I use an unofficial VSCode build that enables native Wayland support (Microsoft doesn't offer this yet, so I pretty much have to use this...)
So it seems to me like i have no chance to use the Pylance extension now, which really is a pity and unnecessary.

**Comment by flarn2006** [comment]
@jakebailey If you don't want to provide official support for unofficial builds, that's totally understandable. But there's a difference between merely not guaranteeing compatibility, and actively taking steps to *prevent* compatibility. Why can't you let us at least *try* it in unofficial builds, in case it does still work?

**Comment by tusqasi** [comment]
No answers.

**Comment by nektro** [comment]
"not licensed" doesnt mean "not supported". they're not going to remove the message unless they decide to open source in the future

**Comment by NicoHood** [comment]
Wow, that is really frustrating for me as archlinux user.

**Comment by norambna** [comment]
I'm using Manjaro and have VSCode installed from the 'Official Repositories'. In order to have the Python extension correctly running with Pylance, you just need to install from AUR [code-features](https://aur.archlinux.org/packages/code-features) and [code-marketplace](https://aur.archlinux.org/packages/code-marketplace).

**Comment by MathiasBaumgartinger** [comment]
Hey, I also stumbled across this issue as a manjaro user using code OSS. None of the other workarounds did not do the trick for me but installing pylance via cmd-line (`code --install-extension ms-python.vscode-pylanc`) and updating the user-settings with `"python.languageServer": "Pylance"` worked.
