### ISSUE TITLE
Cancellation exception from inlay hints

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4916]
```
2023-10-04 13:34:31.612 [info] s [Error]: request cancelled
    at t.throwIfCancellationRequested (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:1022211)
    at _0x13850d.visitCall (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\server.bundle.js:1:525255)
    at _0x13850d.visit (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:382202)
    at _0x13850d.visitNode (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388195)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388074)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388159
    at Array.forEach (<anonymous>)
    at _0x13850d.walkMultiple (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388138)
    at _0x13850d.walk (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:388104)
    at _0x2e13b4.<computed> (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\server.bundle.js:1:523126)
    at c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\server.bundle.js:1:26982
    at t.LogTracker.log (c:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.11\dist\pyright.bundle.js:1:1084506) {
```

Repro steps:

1. Turn on all the pytest options
1. Create a new file that imports pytest.
1. Add this code:

```python
import pytest

class Fruit:
    def __init__(self, name):
        self.name = name
        self.cubed = False

    def cube(self):
        self.cubed = True


class FruitSalad:
    def __init__(self, *fruit_bowl):
        self.fruit = fruit_bowl
        self._cube_fruit()

    def _cube_fruit(self):
        for fruit in self.fruit:
            fruit.cube()


# Arrange
@pytest.fixture
def fruit_bowl():
    return [Fruit("apple"), Fruit("banana")]


def test_fruit_salad(fruit_bowl):
    # Act
    fruit_salad = FruitSalad(*fruit_bowl)

    # Assert
    assert all(fruit.cubed for fruit in fruit_salad.fruit)
```

4. Hover over the `fruit_bowl`.

If that doesn't work, try adding removing `fruit_bowl` from the test_fruit_salad.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231021-11-October-2023-PreRelease)
