### ISSUE TITLE
Intellisense highlighting not working

### ISSUE THREAD

**Issue by gallodustin** [microsoft/pylance-release#5001]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The Python extension appears to find the relevant source files in the output, but no intellisense highlighting appears when looking at Python files. Intellisense is working on other file types.

## Steps to reproduce:

1. Launch VSCode and open a Python file. Intellisense color highlighting is missing (except for keywords and strings, it looks like).
2. This behavior happens on both release and pre-release versions of the extensions, and remains after restarting the language server or restarting VSCode itself. I also tried re-installing VSCode as well as the Python extensions.

OS: Arch Linux
VSCode version: 1.83.1
VSCode commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
VSCode extensions:
- Pylance v2023.10.41
- Pylint v2023.9.12961008
- v2023.19.12971007

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-10-24 08:04:27.898 [error] [
  'Restarting language server, Class name = d, completed in 1ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2410357)
      at _.shutdown (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2409533)
      at _.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2408961)
      at _.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2575349)
      at Object.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:52694)
      at Object.stop (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166776)
      at _0x374d7c.<computed>._stopClient (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110214)
      at _0x374d7c.<computed>._createNewRequest (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109810)
      at _0x374d7c.<computed>._enqueueRequestAndWaitForRun (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109128)
      at _0x374d7c.<computed>.stopClient (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:108585)
      at h.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:37320)
]
2023-10-24 08:04:27.898 [error] [
  'Failed to restart language server, Class name = d, completed in 1ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2410357)
      at _.shutdown (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2409533)
      at _.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2408961)
      at _.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:2575349)
      at Object.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:52694)
      at Object.stop (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166776)
      at _0x374d7c.<computed>._stopClient (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110214)
      at _0x374d7c.<computed>._createNewRequest (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109810)
      at _0x374d7c.<computed>._enqueueRequestAndWaitForRun (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109128)
      at _0x374d7c.<computed>.stopClient (/home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:108585)
      at h.stop (/home/dustino/.vscode/extensions/ms-python.python-2023.19.12971007/out/client/extension.js:2:37320)
]
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

envFile: "<placeholder>"

languageServer: "Pylance"

testing
• pytestArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2023.19.12971007
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 6.5.8-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7600 6-Core Processor (12 x 4111)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|30.51GB (16.49GB free)|
|Process Argv|datachat.code-workspace --crash-reporter-id 3c42b0a4-ed4c-4aca-964d-8695e0846a89|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
2e7ec940:30869480
pythontbext0:30864172

```

</details>

**Comment by rchiodo** [comment]
This is a dupe of https://github.com/microsoft/pylance-release/issues/5000. Try upgrading your pylance to 2023.10.41. Your log says you're still using 2023.10.40.

**Comment by gallodustin** [comment]
True, on Pylance 2023.10.41 I don't get that same stack trace in my Python output, but I still don't get any intellisense highlighting. It looks like this:

![image](https://github.com/microsoft/pylance-release/assets/48537601/f640a41d-e6e2-4fb5-bd7b-6dc6cee9db12)

<details><summary>The only output in the Python window is stuff like this, which is pointing to the correct spot.</summary>
<p>

```python
2023-10-24 10:08:52.556 [info] Python interpreter path: ./.venv/bin/python
2023-10-24 10:09:16.191 [info] Python interpreter path: ~/Documents/GitHub/datachat/.venv/bin/python
2023-10-24 10:09:20.208 [info] Python interpreter path: ./.venv/bin/python
2023-10-24 10:09:20.887 [info] Python interpreter path: ~/Documents/GitHub/datachat/.venv/bin/python
``` 

</p>
</details>

**Comment by rchiodo** [comment]
Can you upload the output from the "Python Language Server" tab? That looks like you don't have 'Pylance' enabled as the language server.

**Comment by gallodustin** [comment]
It does show that Pylance is selected as the Python language server in my settings. The python language server output is quite long due to the number of venv's in this repo. But the output for each one looks similar to this:

```python
2023-10-24 10:21:45.918 [info] [Info  - 10:21:45 AM] (256787) Setting pythonPath for service "foo": "/home/.../foo/.venv/bin/python"
2023-10-24 10:21:45.934 [info] [Info  - 10:21:45 AM] (256787) Setting environmentName for service "foo": "3.8.16 (.venv venv)"
2023-10-24 10:21:45.935 [info] [Info  - 10:21:45 AM] (256787) Loading pyproject.toml file at /home/.../foo/pyproject.toml
2023-10-24 10:21:45.955 [info] [Info  - 10:21:45 AM] (256787) Pyproject file "/home/.../foo/pyproject.toml" has no "[tool.pyright]" section.
2023-10-24 10:21:45.992 [info] [Info  - 10:21:45 AM] (256787) Assuming Python version 3.8
2023-10-24 10:21:46.117 [info] [Info  - 10:21:46 AM] (256787) Found 7 source files
```

**Comment by rchiodo** [comment]
If you open a new project with a single test.py file in it, do you get colorization?

Also what do the errors (yellow squiggles) say in that screenshot you showed?

**Comment by rchiodo** [comment]
The 'Python Language Server' output tab may also be saving the output from the previous runs. It's a new change that VS code made, which honestly makes it harder to debug problems.

You'd have to look at the last set of output. It should start with something like this:

```
2023-10-24 10:38:50.156 [info] [Info  - 10:38:50 AM] (6436) Pylance language server 2023.10.41 (pyright cfe56bfb) starting
```

**Comment by gallodustin** [comment]
> If you open a new project with a single test.py file in it, do you get colorization?

Nope, it looks the same.

> Also what do the errors (yellow squiggles) say in that screenshot you showed?

The errors I would expect. In this case, "missing docstring" for the class and function and "unused import" for the imports. As far as I can tell, everything is working besides the colors.

> The 'Python Language Server' output tab may also be saving the output from the previous runs. It's a new change that VS code made, which honestly makes it harder to debug problems.
> 
> You'd have to look at the last set of output. It should start with something like this:
> 
> ```python
> 2023-10-24 10:38:50.156 [info] [Info  - 10:38:50 AM] (6436) Pylance language server 2023.10.41 (pyright cfe56bfb) start
> ```

Here's the full output from the much smaller workspace I opened:

```python
2023-10-24 10:43:37.850 [info] [Info  - 10:43:37 AM] (44381) Pylance language server 2023.10.41 (pyright cfe56bfb) starting
2023-10-24 10:43:37.880 [info] [Info  - 10:43:37 AM] (44381) Server root directory: /home/dustino/.vscode/extensions/ms-python.vscode-pylance-2023.10.41/dist
2023-10-24 10:43:37.902 [info] [Info  - 10:43:37 AM] (44381) Starting service instance "fast-api-example"
2023-10-24 10:43:37.924 [info] [Info  - 10:43:37 AM] (44381) Setting pythonPath for service "fast-api-example": "/home/dustino/.pyenv/versions/3.11.4/bin/python"
2023-10-24 10:43:37.924 [info] [Info  - 10:43:37 AM] (44381) Setting environmentName for service "fast-api-example": "3.11.4 (global)"
2023-10-24 10:43:37.950 [info] [Info  - 10:43:37 AM] (44381) Assuming Python version 3.11
2023-10-24 10:43:37.976 [info] [Info  - 10:43:37 AM] (44381) Auto-excluding /home/dustino/Documents/GitHub/fast-api-example/venv
2023-10-24 10:43:37.978 [info] [Info  - 10:43:37 AM] (44381) Found 10 source files
```

Thanks for the help, by the way.

**Comment by rchiodo** [comment]
Okay I'd need to see what messages VS code is sending to Pylance. There's a setting for that but it generates a lot more output (you'll likely have to copy the output to a file and upload the file).

The setting is this:

```jsonc
  "python.trace.server": "verbose"
```

That tells VS code to log all of its requests to Pylance. There should be a 'semanticToken' request in the output somewhere. That's what generates the colors.

**Comment by gallodustin** [comment]
Sure, here is that output.

[Python Language Server.log](https://github.com/microsoft/pylance-release/files/13125178/Python.Language.Server.log)

**Comment by rchiodo** [comment]
Are the files marked as python in the bottom right?

![image](https://github.com/microsoft/pylance-release/assets/19672699/c23fcff7-8e57-4424-97f2-029e5ab850da)

We're not even getting a `textDocument/didOpen` notification.  

Sorry maybe you didn't open a file?

**Comment by gallodustin** [comment]
Sorry about that. Updating my previous post...

**Comment by rchiodo** [comment]
It looks like we're getting the semantic token requests and we're returning data, so it should be working as far as Pylance can tell. 

If you run this command: `Developer: Inspect Editor Tokens and Scopes`, and then hover over a python function name, what does it show?

This is an example for me:

![image](https://github.com/microsoft/pylance-release/assets/19672699/92bf8302-4d52-4851-8e72-6c656f6601ab)

If it shows a semantic token name, then there's something wrong in your theme or in VS code. If it doesn't show a semantic token type of 'function', then the data we're sending back is not be interpreted correctly.

**Comment by gallodustin** [comment]
You're right, the theme appears to be the problem. Selecting a different one, I get some colors. Odd though, because the one that isn't working for me isn't anything custom, it's "Dark (Visual Studio)". Also, "Light (Visual Studio)" has the same sort of problems.

I think this is an issue between `gnome-tweaks` and VSCode and how each handles themes. If I leave the VSCode theme as "Dark (Visual Studio)", I can cause or fix the coloring issue in VSCode by changing between different options in the _Appearance > Legacy Applications_ setting in `gnome-tweaks`. Perhaps related to [this issue](https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/434)?

For me, the workaround of using a different theme is good enough. Thanks!
