### ISSUE TITLE
Python language server crashing

### ISSUE THREAD

**Issue by DoctorCesar** [microsoft/pylance-release#5049]
Hello, i have a probleme with the python language server and i don't konw how to fix it.

Here is the log : 
2023-10-30 17:17:39.510 [info] Error: Debug Failure. Unable to find notebook URI for C:\Users\Jules Gazeau\Documents\#Dev\Language\Python\inventory system\main.py
    at _0x4f6f08._getNotebookUri (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:377799)
    at _0x4f6f08.getNotebookPathFromCell (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:375944)
    at _0x5e13d0.getContainingWorkspacesForFile (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1015301)
    at _0x5e13d0.onDidOpenTextDocument (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1155615)
    at _0x5e13d0.onDidOpenTextDocument (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1033753)
    at c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1143434
    at c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1471770
    at oe (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1471992)
    at c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1467932
    at Immediate.<anonymous> (c:\Users\Jules Gazeau\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1467952)
    at processImmediate (node:internal/timers:476:21)

2023-10-30 17:17:39.751 [info] [Error - 5:17:39 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Pylance version : v2023.10.50
Python extension version : v2023.18.0

**Comment by rchiodo** [comment]
Thanks for the issue. Sorry the problem is our parsing of file paths. We don't support `#` in file paths at the moment. You can workaround this issue by not having a file path with a `#` in it.

**Comment by DoctorCesar** [comment]
Ok thanks I will try that

**Comment by DoctorCesar** [comment]
Ok it worked thanks
