### ISSUE TITLE
Connection to server got closed. Server will not be restarted

### ISSUE THREAD

**Issue by T-256** [microsoft/pylance-release#5086]
<h3> Environment data </h3>

-   Language Server version: 2023.11.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Logs </h3>

```
2023-11-05 21:03:41.546 [info] [Info  - 9:03:41 PM] (20376) Setting pythonPath for service "test-proj": "c:\Python37x86\python.exe"
2023-11-05 21:03:41.546 [info] [Info  - 9:03:41 PM] (20376) Setting environmentName for service "test-proj": "3.7.9 (.venv venv)"
2023-11-05 21:03:41.636 [info] [Info  - 9:03:41 PM] (20376) Assuming Python version 3.7
2023-11-05 21:03:41.811 [info] [Info  - 9:03:41 PM] (20376) Found 164 source files
2023-11-05 21:03:46.278 [info] [Info  - 9:03:46 PM] (20376) [IDX(5)] Long operation: index execution environment E:\test-proj (3202ms)
2023-11-05 21:03:46.279 [info] [Info  - 9:03:46 PM] (20376) [IDX(5)] Long operation: index packages E:\test-proj (3280ms)
2023-11-05 21:16:08.418 [info] [Error - 9:16:08 PM] Server process exited with code 1.
2023-11-05 21:16:08.418 [info] [Error - 9:16:08 PM] Connection to server got closed. Server will not be restarted.
2023-11-05 21:16:08.418 [info] [Error - 9:16:08 PM] Handling connection close failed
2023-11-05 21:16:08.418 [info] TypeError: e.clear is not a function
	at _.cleanUp (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2412859)
	at _.handleConnectionClosed (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2417283)
	at _.handleConnectionClosed (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2578252)
	at <USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2416709
	at o.invoke (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
	at s.fire (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
	at te (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2349784)
	at o.invoke (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
	at s.fire (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
	at d.fireClose (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2372012)
	at ChildProcess.<anonymous> (<USER>.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2384364)
	at ChildProcess.emit (node:events:525:35)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by rchiodo** [comment]
Thanks for the issue. The prerelease version of the extension has the fix for this problem.
