### ISSUE TITLE
Failed to restart language server

### ISSUE THREAD

**Issue by skokado** [microsoft/pylance-release#5131]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I faced `Failed to restart language server` when I ran `Python: Restart Language Server`.
Once failed to restart, of course any features of Python language server would loss (e.g. Does not work code jump)

I've already tried re-install VS Code and re-install the extensions (remove `~/.vscode-server/extensions/ms-python.python*`).

It seems to work well only just after I opened the workpace.
So, once restarting failed but reopen the workspace and then it would work well.

![vscode-python-lsp](https://github.com/microsoft/vscode-python/assets/16687062/669d9632-f532-4e04-97cc-d7dc5c2af6fb)

## Steps to reproduce:

1. `Ctrl + Shift + P` and execute `Python: Restart Language Server`

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): venv
-   Value of the `python.languageServer` setting: Default

Version Info

- VS Code
    - Version: 1.84.2 (user setup)
    - Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
    - Date: 2023-11-09T10:51:52.184Z (1 週間前)
    - Electron: 25.9.2
    - ElectronBuildId: 24603566
    - Chromium: 114.0.5735.289
    - Node.js: 18.15.0
    - V8: 11.4.183.29-electron.0
    - OS: Windows_NT x64 10.0.19045
- Extension
    - Python: v2023.21.13211009
    - Pylance v2023.11.10

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-11-20 14:00:42.642 [error] [
  'Disposing language server, Class name = h, completed in 1ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2414564)
      at _.shutdown (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413740)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413168)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2579556)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:52680)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:167359)
      at _0x245439.<computed>._stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110667)
      at _0x245439.<computed>._createNewRequest (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110246)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at _0x245439.<computed>._enqueueRequestAndWaitForRun (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109555)
      at _0x245439.<computed>.stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109012)
      at h.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:37306)
]
2023-11-20 14:00:42.643 [error] [
  'Stopping language server, Class name = d, completed in 4ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2414564)
      at _.shutdown (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413740)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413168)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2579556)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:52680)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:167359)
      at _0x245439.<computed>._stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110667)
      at _0x245439.<computed>._createNewRequest (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110246)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at _0x245439.<computed>._enqueueRequestAndWaitForRun (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109555)
      at _0x245439.<computed>.stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109012)
      at h.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:37306)
]
2023-11-20 14:00:42.644 [error] [
  'Restarting language server, Class name = d, completed in 5ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2414564)
      at _.shutdown (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413740)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413168)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2579556)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:52680)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:167359)
      at _0x245439.<computed>._stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110667)
      at _0x245439.<computed>._createNewRequest (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110246)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at _0x245439.<computed>._enqueueRequestAndWaitForRun (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109555)
      at _0x245439.<computed>.stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109012)
      at h.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:37306)
]
2023-11-20 14:00:42.644 [error] [
  'Failed to restart language server, Class name = d, completed in 5ms, has a falsy return value, , Return Value: undefined',
  TypeError: e.clear is not a function
      at _.cleanUp (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2414564)
      at _.shutdown (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413740)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2413168)
      at _.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:2579556)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:52680)
      at Object.stop (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:167359)
      at _0x245439.<computed>._stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110667)
      at _0x245439.<computed>._createNewRequest (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110246)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at _0x245439.<computed>._enqueueRequestAndWaitForRun (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109555)
      at _0x245439.<computed>.stopClient (/home/skokado/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109012)
      at h.stop (/home/skokado/.vscode-server/extensions/ms-python.python-2023.21.13211009/out/client/extension.js:2:37306)
]
```

</p>
</details>

Thank you.

Extension version: 2023.20.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (45.13GB free)|
|Process Argv|--crash-reporter-id f14c760f-e2ec-4df1-a580-23365abe258c|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3593)|
|Memory (System)|31.35GB (29.23GB free)|
|VM|0%|
</details>

**Comment by rchiodo** [comment]
This is a dupe of https://github.com/microsoft/pylance-release/issues/5000, which has been fixed in our prerelease builds. Version 2023.11.13 would have the fix for this problem.

**Comment by NixBiks** [comment]
> This is a dupe of #5000, which has been fixed in our prerelease builds. Version 2023.11.13 would have the fix for this problem.

But we are both on version `2023.20.0` so that should already have the fix, no?

**Comment by kleynjan** [comment]
I had a similar issue, intermittently coming back for months. On latest production versions per september 2025 (1.103.2 VS Code, Pylance 2025.7.1). Posting this here in case anyone comes looking for it.

In my case the issue turned out to be due to old/stale virtualenvs in ~/.virtualenvs. Python or Pylance kept hunting for interpreters. After updating conda, cleaning up my conda envs and deleting ~/.virtualenvs my Pylance finally seems reliable again.
