### ISSUE TITLE
pylance crashing after switching profile

### ISSUE THREAD

**Issue by amunger** [microsoft/pylance-release#5152]
Type: <b>Bug</b>

1. Open a notebook let all extensions activate
2. Switch to a profile that also has jupyter/python/pylance extensions installed

:bug: Crash notifications from pylance

![Screenshot 2023-11-28 083120](https://github.com/microsoft/pylance-release/assets/2019016/bd92708c-2d84-45ba-8635-e8cfc3fe9335)

<details>
<summary>Pylance logs</summary>

```
2023-11-28 08:34:49.282 [info] [Error - 8:34:49 AM] Client Pylance: connection to server is erroring.
write EPIPE
2023-11-28 08:34:49.288 [info] [Error - 8:34:49 AM] Client Pylance: connection to server is erroring.
write EPIPE
Shutting down server.
2023-11-28 08:34:49.289 [info] [Error - 8:34:49 AM] Client Pylance: connection to server is erroring.
write EPIPE
Shutting down server.
2023-11-28 08:34:49.291 [info] [Error - 8:34:49 AM] Server process exited with code 1.
2023-11-28 08:34:49.291 [info] Error: Debug Failure. Cell path not found for cell vscode-notebook-cell:/c%3A/src/test/6/Test.ipynb#W3sZmlsZQ%3D%3D
    at _0x345de2.getNotebookCellPath (c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\server.bundle.js:1:386111)
    at _0x1abbbb.decodeTextDocumentUri (c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\server.bundle.js:1:355871)
    at _0x4d79de.onDidOpenTextDocument (c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\server.bundle.js:1:1043802)
    at c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\pyright.bundle.js:1:1149255
    at c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\vendor.bundle.js:2:1234062
    at oe (c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\vendor.bundle.js:2:1234284)
    at c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\vendor.bundle.js:2:1230224
    at Immediate.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\vendor.bundle.js:2:1230244)
    at processImmediate (node:internal/timers:476:21)

2023-11-28 08:34:49.294 [info] [Error - 8:34:49 AM] Connection to server got closed. Server will not be restarted.
2023-11-28 08:34:49.295 [info] [Error - 8:34:49 AM] Stopping server failed
2023-11-28 08:34:49.295 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-28 08:34:49.297 [info] [Error - 8:34:49 AM] Stopping server failed
2023-11-28 08:34:49.297 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-28 08:34:49.297 [info] [Error - 8:34:49 AM] Stopping server failed
2023-11-28 08:34:49.297 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

</details>

Extension version: 2023.11.13
VS Code version: Code - Insiders 1.85.0-insider (b3b84b5239037a2f0ef8499306df9a3bacda4105, 2023-11-28T12:02:59.475Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (3.65GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2cf:30871583
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by amunger** [comment]
It doesn't happen for every profile switch, but consistent for the ones that it does crash on.

**Comment by rchiodo** [comment]
This doesn't seem to repro for me, but maybe I'm doing something wrong. Everytime I switch profiles it tells me VS code has to reload, so that would likely force Pylance to refetch all of the cell uris. 

The assertion in the log isn't there anymore though, so maybe this is just fixed.

**Comment by debonte** [comment]
Maybe it was a dupe of the [trusted->untrusted crash](https://github.com/microsoft/pylance-release/issues/5194) which was [fixed](https://github.com/microsoft/vscode/issues/202232) in VS Code insiders this morning.
