### ISSUE TITLE
moving cells in a notebook causes pylance to crash

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5157]
## Environment data
<h3> Environment data </h3>

-   Language Server version: 2023.11.13
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

## Code Snippet

```
# %%
import time

time.sleep(20)

# %%
a = 10

# %%
b = a

```

## Repro Steps
1.  create a new notebook from the command palette
2.  do not save it
3. copy the 3 cells above
4. run all cells
5. when the first cell is running, move the second cell to above the first cell
6. save it (before it has finished running the first cell)

## Expected behavior

no crash

## Actual behavior

crash

## Logs

```
2023-11-28 14:13:52.048 [error] [ms-python.vscode-pylance] provider FAILED
2023-11-28 14:13:52.048 [error] TypeError: Cannot read properties of undefined (reading 'data')
    at c:\Users\bug-magnet-contender\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\extension.bundle.js:1:79765
    at _0x2aad0e (c:\Users\bug-magnet-contender\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.11.13\dist\extension.bundle.js:1:92881)
    at X.provideCompletionItems (c:\Users\bug-magnet-contender\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:52837)

```

**Comment by judej** [comment]
dupe
