### ISSUE TITLE
Failed to restart language server

### ISSUE THREAD

**Issue by pxl9588** [microsoft/pylance-release#5225]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected:
Language server should restart.

Actual:
Logs show the server failed to restart.
```
2023-12-07 11:46:48.977 [error] [
  'Failed to restart language server, Class name = d, completed in 4ms, has a falsy return value, , Return Value: undefined',
  [TypeError: e.clear is not a function
  	at _.cleanUp (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2412859)
  	at _.shutdown (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2412035)
  	at _.stop (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2411463)
  	at _.stop (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2577851)
  	at Object.stop (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:52694)
  	at Object.stop (/home/planders5/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:167359)
  	at _0x245439.<computed>._stopClient (/home/planders5/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110667)
  	at _0x245439.<computed>._createNewRequest (/home/planders5/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:110246)
  	at async _0x245439.<computed>._enqueueRequestAndWaitForRun (/home/planders5/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109555)
  	at async _0x245439.<computed>.stopClient (/home/planders5/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.10/dist/extension.bundle.js:1:109012)
  	at async h.stop (/home/planders5/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:37320)]
]
```

## Steps to reproduce:

1. Run `Python: Restart Language Server`

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.20.0
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (37.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|Memory (System)|35.24GB (33.27GB free)|
|VM|0%|
</details>

**Comment by pxl9588** [comment]
It looks like its also not able to find modules in ‘src/‘ despite having src in extraPaths
