### ISSUE TITLE
Starting server failed

### ISSUE THREAD

**Issue by namrataojha22** [microsoft/pylance-release#5233]
<h3> Environment data </h3>

-   Language Server version: 2023.11.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

Go to defination should work for python
Pylance:clear all persisted indexes should work

<h3> Actual behavior </h3>
Go to defination not working for python
Pylance:clear all persisted indexes not working

<h3> Logs </h3>

```
2023-12-08 15:08:43.333 [info] [Error - 3:08:43 PM] Request textDocument/foldingRange failed.
2023-12-08 15:08:43.333 [info] Error: Starting server failed at _.$start (c:\Users\nao8\.vscode\extensions\ms-python.python-2023.22.0\out\client\extension.js:2:2399752)
    at _.sendRequest (c:\Users\nao8\.vscode\extensions\ms-python.python-2023.22.0\out\client\extension.js:2:2383782)
    at _.provideFoldingRanges (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:61654)
```

**Comment by heejaechang** [comment]
@namrataojha22 thank you for reporting!

Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

currently, it doesn't have enough information for us to investigate.

**Comment by heejaechang** [comment]
please re-open if it is still an issue.
