### ISSUE TITLE
Out of memory while analyzing Terraform CDK Imports

### ISSUE THREAD

**Issue by jasongilman** [microsoft/pylance-release#5236]
## Environment data

-   VS Code Version: 1.84.2
-   Language Server version: 2023.11.10
-   OS and version: Mac OSX 13.6.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Repro Steps

1. Open a Terraform CDK Python project with AWS imports. This includes many large (~18K lines) files.
2. Wait for "files to analyze" to count down while watching the extension output.
3. Extension will crash after approximately 7 minutes with out of memory error. 

## Expected behavior

The file analysis will complete without running out of memory. If necessary there should be an option to increase the extensions memory allocation.

## Logs

With verbose logs turned out it prints out about 16K lines of output. This is the last couple dozen.

```
2023-12-09 15:09:59.473 [info] [Info  - 3:09:59 PM] (43086) Heap stats: total_heap_size=2821MB, used_heap_size=2659MB, total_physical_size=2820MB, total_available_size=1341MB, heap_size_limit=4096MB
2023-12-09 15:09:59.474 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc/__init__.py (230ms)
2023-12-09 15:09:59.487 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc_dhcp_options/__init__.py ...
2023-12-09 15:09:59.489 [info] (43086) [BG(1)]   parsing: /Users/redacted/redacted/imports/aws/data_aws_vpc_dhcp_options/__init__.py [fs read 1ms] (12ms)
2023-12-09 15:09:59.491 [info] (43086) [BG(1)]   binding: /Users/redacted/redacted/imports/aws/data_aws_vpc_dhcp_options/__init__.py (4ms)
2023-12-09 15:09:59.647 [info] (43086) [BG(1)]   checking: /Users/redacted/redacted/imports/aws/data_aws_vpc_dhcp_options/__init__.py (157ms)
2023-12-09 15:09:59.648 [info] [Info  - 3:09:59 PM] (43086) Heap stats: total_heap_size=2823MB, used_heap_size=2658MB, total_physical_size=2823MB, total_available_size=1342MB, heap_size_limit=4096MB
2023-12-09 15:09:59.648 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc_dhcp_options/__init__.py (173ms)
2023-12-09 15:09:59.658 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint/__init__.py ...
2023-12-09 15:09:59.658 [info] (43086) [BG(1)]   parsing: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint/__init__.py [fs read 2ms] (11ms)
2023-12-09 15:09:59.662 [info] (43086) [BG(1)]   binding: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint/__init__.py (3ms)
2023-12-09 15:09:59.850 [info] (43086) [BG(1)]   checking: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint/__init__.py (188ms)
2023-12-09 15:09:59.850 [info] [Info  - 3:09:59 PM] (43086) Heap stats: total_heap_size=2827MB, used_heap_size=2662MB, total_physical_size=2827MB, total_available_size=1338MB, heap_size_limit=4096MB
2023-12-09 15:09:59.850 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint/__init__.py (202ms)
2023-12-09 15:09:59.860 [info] (43086) [BG(1)] analyzing: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint_service/__init__.py ...
2023-12-09 15:09:59.861 [info] (43086) [BG(1)]   parsing: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint_service/__init__.py [fs read 2ms] (10ms)
2023-12-09 15:09:59.864 [info] (43086) [BG(1)]   binding: /Users/redacted/redacted/imports/aws/data_aws_vpc_endpoint_service/__init__.py (4ms)
2023-12-09 15:10:06.615 [info] 
<--- Last few GCs --->

[43086:0x10c003e4000]   577910 ms: Mark-Compact (reduce) 2280.0 (2782.9) -> 2280.0 (2698.4) MB, 1748.41 / 0.00 ms  (average mu = 0.842, current mu = 0.001) last resort; GC in old space requested
[43086:0x10c003e4000]   579885 ms: Mark-Compact (reduce) 2280.0 (2698.4) -> 2280.0 (2660.1) MB, 1975.46 / 0.00 ms  (average mu = 0.703, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

2023-12-09 15:10:06.616 [info]  1: 0x11bf3ada5 node::Buffer::New(v8::Isolate*, char*, unsigned long) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

2023-12-09 15:10:06.617 [info]  2: 0x11bf3afc8 node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x11663c6f0 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x11663c68d v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x116807bb3 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1167e31d0 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x1153b1b4c v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithMap(v8::internal::Handle<v8::internal::Map>, int, v8::internal::AllocationType) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x116b666fe v8::internal::OrderedHashMap::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x116ca3ace v8::internal::RegExp::CompileForTesting(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::RegExpFlag, int, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x11512fef6  [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

2023-12-09 15:10:07.368 [info] [Error - 3:10:07 PM] Server process exited with signal SIGABRT.
2023-12-09 15:10:07.369 [info] [Info  - 3:10:07 PM] Connection to server got closed. Server will restart.
2023-12-09 15:10:07.369 [info] true
2023-12-09 15:10:07.370 [info] [Error - 3:10:07 PM] Handling connection close failed
2023-12-09 15:10:07.370 [info] TypeError: e.clear is not a function
	at _.cleanUp (/Users/redacted/.vscode/extensions/ms-python.python-2023.23.13391009/out/client/extension.js:2:2396933)
	at _.handleConnectionClosed (/Users/redacted/.vscode/extensions/ms-python.python-2023.23.13391009/out/client/extension.js:2:2401616)

```

**Comment by jasongilman** [comment]
I was able to work around the issue by adding `"exclude":["imports"]` to the `pyrightconfig.json`.
