### ISSUE TITLE
Pylance fails to show any errors

### ISSUE THREAD

**Issue by Cpt-Dingus** [microsoft/pylance-release#5338]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The python syntax highlighting works fine, but does not highlight any issues. Opening `Extension` host in the `Output` tab shows several errors:
```
2024-01-07 16:02:14.437 [error] [ms-python.python] provider FAILED
2024-01-07 16:02:14.437 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at /home/meti/.vscode/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2354913
    at re (/home/meti/.vscode/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2355207)
    at /home/meti/.vscode/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2349991
    at Immediate.<anonymous> (/home/meti/.vscode/extensions/ms-python.python-2023.20.0-universal/out/client/extension.js:2:2350011)
    at processImmediate (node:internal/timers:476:21)
```

## Steps to reproduce:

1. Install the extension
2. Open a python file

![image](https://github.com/microsoft/vscode-python/assets/100243410/7534a460-0439-4861-a3a0-f18f111f68ff)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Jedi"

```

</p>
</details>

Extension version: 2023.20.0
VS Code version: Code 1.85.1 (Commit unknown, 2023-12-14T20:02:29.406Z)
OS version: Linux x64 6.6.8-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2725)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (7.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
i26e3531:30792625
welcomedialog:30910333
asynctok:30898717
2e7ec940:30885897
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by rchiodo** [comment]
Can you upload the contents of this output pane?

![image](https://github.com/microsoft/pylance-release/assets/19672699/79b5472b-012a-4e1f-ba76-36a3178c3754)

**Comment by Cpt-Dingus** [comment]
The only thing in that pane is as follows:

```
2024-01-09 19:31:28.255 [info] (Client) You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
```

**Comment by rchiodo** [comment]
Ah right. I forgot. You can't use pylance with vscode-oss. You have to use it with the VS code that ships from the store.

**Comment by Cpt-Dingus** [comment]
Ah okay, is there any place to get it on Linux? Currently using EndeavourOs (Arch based)

**Comment by rchiodo** [comment]
I believe vscode has pretty good docs on that:
https://code.visualstudio.com/docs/setup/linux
