### ISSUE TITLE
File System error with Pylance on activate

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#5686]
```
[Extension Host] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.101\package.nls.en.json'
	at C.e (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6084)
	at Object.readFile (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4463)
	at async _0x62c842 (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.101\dist\extension.bundle.js:1:205504)
	at async _0xa54774 (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.101\dist\extension.bundle.js:1:205086)
	at async _0x33f2ea (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.101\dist\extension.bundle.js:1:314183)
	at async _0xbbfc96 (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.101\dist\extension.bundle.js:1:243969)
	at async o.n (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:6237)
	at async o.m (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:6200)
	at async o.l (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:5657) (at console.<anonymous> (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:60451))

```

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2024.4.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20244100-4-April-2024-PreRelease)
