### ISSUE TITLE
 Debug Failure. False expression: Check called before parsing

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5868]
Stack trace from logs

Error: Debug Failure. False expression: Check called before parsing
at assert src/analyzer/sourceFile.ts#L867pyright-internal/src/analyzer/sourceFile.ts:867:8
at callback src/common/logTracker.ts#L61pyright-internal/src/common/logTracker.ts:61:19
at log src/analyzer/program.ts#L1884pyright-internal/src/analyzer/program.ts:1884:32
at callback src/analyzer/typeEvaluator.ts#L632pyright-internal/src/analyzer/typeEvaluator.ts:632:19
at callback src/common/timing.ts#L40pyright-internal/src/common/timing.ts:40:19
at runWithCancellationToken src/analyzer/program.ts#L1037pyright-internal/src/analyzer/program.ts:1037:40
at _runEvaluatorWithCancellationToken src/analyzer/program.ts#L612pyright-internal/src/analyzer/program.ts:612:20
at analyze src/analyzer/analysis.ts#L52pyright-internal/src/analyzer/analysis.ts:52:32
at this src/backgroundAnalysisBase.ts#L495pyright-internal/src/backgroundAnalysisBase.ts:495:12
at handleResumeAnalysis src/backgroundAnalysisBase.ts#L488pyright-internal/src/backgroundAnalysisBase.ts:488:13
at None src/backgroundAnalysis.ts#L417pylance-internal/src/backgroundAnalysis.ts:417:28
at handleAnalyze src/backgroundAnalysisBase.ts#L338pyright-internal/src/backgroundAnalysisBase.ts:338:21
at None src/backgroundAnalysis.ts#L405pylance-internal/src/backgroundAnalysis.ts:405:28
at onMessage src/backgroundAnalysisBase.ts#L657pyright-internal/src/backgroundAnalysisBase.ts:657:24
    at func (node:<REDACTED: user-file-path>:757:20)
    at func (node:<REDACTED: user-file-path>:23:28)

**Comment by bschnurr** [comment]
I have a feeling this is related to deleting files.. possibly notebooks.. can't repo it yet though

**Comment by heejaechang** [comment]
we might add something to code so we ask users to open an issue if it gets hit. like the code we added to ask users to file an issue if `completion` takes more than 10 seconds.
