### ISSUE TITLE
Pylance has collapsed. Want to try using the Node.js executable to run the language server?

### ISSUE THREAD

**Issue by piwawa** [microsoft/pylance-release#5891]
![image](https://github.com/microsoft/pylance-release/assets/46926496/db24138c-3b5e-4b67-8212-e7521bb59f6e)

I have set `export NODE_OPTIONS="--max-old-space-size=12288"` in `.bashrc` and restart the VSCODE, but it still report crash and can not highlight code. How to solve this? I tried to reinstall Pylance extension and switch to review vision, all failed!

![image](https://github.com/microsoft/pylance-release/assets/46926496/25d3a2b3-8e65-40e9-bbc8-7e8e85a4d35a)

**Comment by heejaechang** [comment]
are you using remote server `vscode-server` ? `export NODE_OPTIONS="--max-old-space-size=12288"` only works with remote server.

**Comment by piwawa** [comment]
> are you using remote server `vscode-server` ? `export NODE_OPTIONS="--max-old-space-size=12288"` only works with remote server.

I am using VSCODE Software and SSH connecting to my remote server.

**Comment by heejaechang** [comment]
can you provide us log? https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs

and how much memory do you have in your remote server that you connect through SSH?

**Comment by piwawa** [comment]
Memory:

```cmd
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           251Gi        29Gi        89Gi       1.5Gi       136Gi       221Gi
Swap:             0B          0B          0B
```

Trace Logs:

```
2024-05-18 01:34:22.959 [info] [Error - 1:34:22 AM] Notify file events failed.
2024-05-18 01:34:22.960 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:22.960 [info] [Error - 1:34:22 AM] Notify file events failed.
2024-05-18 01:34:22.960 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:23.348 [info] [Error - 1:34:23 AM] Notify file events failed.
2024-05-18 01:34:23.348 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:23.960 [info] [Error - 1:34:23 AM] Notify file events failed.
2024-05-18 01:34:23.960 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:23.960 [info] [Error - 1:34:23 AM] Notify file events failed.
2024-05-18 01:34:23.960 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:24.345 [info] [Error - 1:34:24 AM] Notify file events failed.
2024-05-18 01:34:24.345 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:24.959 [info] [Error - 1:34:24 AM] Notify file events failed.
2024-05-18 01:34:24.959 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:24.959 [info] [Error - 1:34:24 AM] Notify file events failed.
2024-05-18 01:34:24.959 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:25.344 [info] [Error - 1:34:25 AM] Notify file events failed.
2024-05-18 01:34:25.344 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:25.958 [info] [Error - 1:34:25 AM] Notify file events failed.
2024-05-18 01:34:25.958 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:25.958 [info] [Error - 1:34:25 AM] Notify file events failed.
2024-05-18 01:34:25.958 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:26.368 [info] [Error - 1:34:26 AM] Notify file events failed.
2024-05-18 01:34:26.368 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:26.965 [info] [Error - 1:34:26 AM] Notify file events failed.
2024-05-18 01:34:26.965 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:26.965 [info] [Error - 1:34:26 AM] Notify file events failed.
2024-05-18 01:34:26.965 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:27.361 [info] [Error - 1:34:27 AM] Notify file events failed.
2024-05-18 01:34:27.361 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:27.995 [info] [Error - 1:34:27 AM] Notify file events failed.
2024-05-18 01:34:27.996 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:27.996 [info] [Error - 1:34:27 AM] Notify file events failed.
2024-05-18 01:34:27.996 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:27.996 [info] [Error - 1:34:27 AM] Notify file events failed.
2024-05-18 01:34:27.996 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:27.996 [info] [Error - 1:34:27 AM] Notify file events failed.
2024-05-18 01:34:27.996 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:28.379 [info] [Error - 1:34:28 AM] Notify file events failed.
2024-05-18 01:34:28.379 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:29.200 [info] [Error - 1:34:29 AM] Notify file events failed.
2024-05-18 01:34:29.200 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:29.200 [info] [Error - 1:34:29 AM] Notify file events failed.
2024-05-18 01:34:29.200 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:29.200 [info] [Error - 1:34:29 AM] Notify file events failed.
2024-05-18 01:34:29.200 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:29.642 [info] [Error - 1:34:29 AM] Notify file events failed.
2024-05-18 01:34:29.642 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:30.053 [info] [Error - 1:34:30 AM] Notify file events failed.
2024-05-18 01:34:30.053 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:30.053 [info] [Error - 1:34:30 AM] Notify file events failed.
2024-05-18 01:34:30.053 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
2024-05-18 01:34:30.438 [info] [Error - 1:34:30 AM] Notify file events failed.
2024-05-18 01:34:30.439 [info] Error: Connection is disposed.
    at pe (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2311678)
    at Object.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2312521)
    at _.sendNotification (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2356142)
    at t.Delayer.<anonymous> (/home/bingo06/.vscode-server/extensions/ms-python.python-2024.6.0/out/client/extension.js:2:2368056)
```

**Comment by heejaechang** [comment]
First, `vscode` (which is based on `electron` that is based on `nodejs` which is based on `V8 JS engine`) doesn't use full machine memory so it is irrelevant how much your machine has as long as it is over certain memory (usually 4GB~8GB). 

that will be used on runtime by python, but it won't be used in `vscode` or `vscode-server` at edit time.

...

the log you shared is too late. server is already gone. so log doesn't provide any info. it just shows that server doesn't exist. what we want is why server is gone, so we need log before the server is gone.

https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs

you can see the above link to see how you can check whether you have proper log.

**Comment by piwawa** [comment]
[log.txt](https://github.com/microsoft/pylance-release/files/15360897/log.txt)

**Comment by heejaechang** [comment]
cool. thank you @piwawa

so, this seems the issue

```
^
RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at Function.a.value (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1215963)
    at p.resolvePaths (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1213270)
    at /home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500537
    at Array.some (<anonymous>)
    at i (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500507)
    at l (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501111)
    at i (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500932)
    at l (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501111)
    at i (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500932)
    at l (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501111)
    at i (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500932)
    at l (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501111)
    at i (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:500932)
    at l (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501111)
    at /home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501414
    at Array.forEach (<anonymous>)
    at A._matchFiles (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:501210)
    at /home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:497675
    at a.timeOperation (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1204592)
    at A._getFileNamesFromFileSpecs (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:497642)
    at A._updateTrackedFileList (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:499236)
    at A._applyConfigOptions (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:508408)
    at A.setOptions (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:484769)
    at Function.runWithOptions (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1258151)
    at _0x542e75.updateOptionsAndRestartService (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1236115)
    at _0x542e75.updateSettingsForWorkspace (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/pyright.bundle.js:1:1235838)
    at _0x542e75.updateSettingsForWorkspace (/home/bingo06/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/server.bundle.js:1:695984)
    at async Promise.all (index 0)
```

that's probably due to this

```
2024-05-18 16:24:32.007 [info] (995489) Searching for source files
2024-05-18 16:24:41.695 [info] [Error - 4:24:41 PM] (995489) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
```

my guess is `/home/bingo06` contains something that shouldn't be considered as user files that we should skip.

can you tell us what `folders` and `files` are right under `/home/bingo06`?

...

that said, until we figure out solution for this, you can tell us using `python.analysis.exclude` what folders/files we should exclude under `bingo06`

for example, `python.analysis.exclude: ['miniconda3/**`]`

**Comment by piwawa** [comment]
There are many files and folders under this path. I placed tens of python projects and miniconda3 in this directory.
Should i bypass all unnecessary folders to avoid memory used by pylance？

**Comment by heejaechang** [comment]
> Should i bypass all unnecessary folders to avoid memory used by pylance？

ya, that would be good for pylance. `pylance` basically scan everything inside of `workspace root` to support `solution wide` features such as `rename`, `find all references`, `workspace symbols`, `pytest` and etc. and perf will be linear to number of files/folders transitively rooted to that root.

**Comment by piwawa** [comment]
> Have you solved this problem? @piwawa

Yes, after I setting` python.analysis.exclude: ['files/**]` as @heejaechang said, highlight code is back!

**Comment by Tsukumizu** [comment]
> > Have you solved this problem? @piwawa
> 
> Yes, after I setting` python.analysis.exclude: ['files/**]` as @heejaechang said, highlight code is back!

Thanks for your feedback. It seems like, there is lots of file in your user directory (where your user name is bingo06), and after exclude those files to be skipped, then pylance work again?
Therefore, I should check my user directory "home/user" like you? Thanks for your reply.

**Comment by piwawa** [comment]
> Thanks for your feedback. It seems like, there is lots of file in your user directory (where your user name is bingo06), and after exclude those files to be skipped, then pylance work again? Therefore, I should check my user directory "home/user" like you? Thanks for your reply.

Yeah, you are absolutely right. Actually I just simply set `python.analysis.include: ['my work dir']`, then pylance works.
