### ISSUE TITLE
Pylance fails to start on VS Code launch

### ISSUE THREAD

**Issue by olegstepanov** [microsoft/pylance-release#5962]
<h3> Environment data </h3>

-   Language Server version: 2024.5.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Logs </h3>

```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object._0x13e5f3.f.<computed> [as require] (/home/ogstepanov/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/server.bundle.js:1:980819)
    at /home/ogstepanov/.vscode-server/extensions/ms-python.vscode-pylance-2024.5.1/dist/server.bundle.js:1:979283
    at Array.reduce (<anonymous>)

2024-06-03 21:47:51.479 [info] [Error - 9:47:51 PM] Server initialization failed.
2024-06-03 21:47:51.479 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-06-03 21:47:51.479 [info] [Error - 9:47:51 PM] Pylance client: couldn't create connection to server.
2024-06-03 21:47:51.479 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-06-03 21:47:51.480 [info] [Error - 9:47:51 PM] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. See the output for more information.
2024-06-03 21:47:51.480 [info] [Error - 9:47:51 PM] Restarting server failed
2024-06-03 21:47:51.480 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-06-03 21:47:51.485 [info] [Error - 9:47:51 PM] Server process exited with code 1.
```

**Comment by StellaHuang95** [comment]
Could be your Pylance package is corrupted. Could you try deleting the local package and reinstalling it? You can find where your extension is installed here: https://code.visualstudio.com/docs/editor/extension-marketplace#_where-are-extensions-installed

**Comment by olegstepanov** [comment]
I reinstalled Pylance, but the error is still there.

**Comment by StellaHuang95** [comment]
Did you delete the local cached version first?

**Comment by olegstepanov** [comment]
Yes, I did

```
cd ~/.vscode-server/extensions/
rm -rf *pylance*
```

on the remote machine.

**Comment by rchiodo** [comment]
You might check if you have `NODE_` related environment variables specified on the remote machine. They could be interferring with execution like this issue:
https://github.com/microsoft/pylance-release/issues/5911

**Comment by rchiodo** [comment]
One of the things to try is to just run our server.bundle.js with node like I outlined here:
https://github.com/microsoft/pylance-release/issues/5911#issuecomment-2128255981

**Comment by olegstepanov** [comment]
I don't have any NODE_* environment variables on the machine. I ran `node server.bundle.js` and the output is:
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object._0x48e40e.f.<computed> [as require] (/home/ogstepanov/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.1/dist/server.bundle.js:1:1125450)
    at /home/ogstepanov/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.1/dist/server.bundle.js:1:1123902
    at Array.reduce (<anonymous>)
```

**Comment by rchiodo** [comment]
What's your version of node on the remote server?

**Comment by olegstepanov** [comment]
v12.22.9

**Comment by rchiodo** [comment]
That may explain it. We need at least version 14 I believe.

**Comment by rchiodo** [comment]
vscode-server should be using its own version though. Unless you have this set:

`python.analysis.nodeExecutable`.

**Comment by olegstepanov** [comment]
It was set indeed, and I don't remember why( Sorry for bothering and thanks a lot for your help!

**Comment by olegstepanov** [comment]
I think this is what happened https://github.com/microsoft/pylance-release/issues/5991. It suggests to switch to local node executable in this case.
