### ISSUE TITLE
pyodbc.Connection class not recognized as type

### ISSUE THREAD

**Issue by iUnknwn** [microsoft/pylance-release#605]
## Environment data

-   Language Server version: Pylance language server 2020.11.1 (pyright 54be42d2)
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3, Conda (Miniconda) 4.8.2

## Expected behaviour
`pyodbc.Connection` is treated as a valid type when listed as a type for an argument:

```python
def GetParentNames(cnxn: pyodbc.Connection, smd_id: int) -> typing.List[str]:
```

## Actual behaviour
`pyodbc.Connection` is marked as Unknown, instead of being an instance of the class.
![image](https://user-images.githubusercontent.com/1129122/98998197-9a9f2400-24ea-11eb-9046-26bc2bf447ee.png)

## Logs
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> pyenv root
> python3.7 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-11-12 13:24:07: Detection of Python Interpreter for Command py and args -2 failed as file  does not exist
Error 2020-11-12 13:24:07: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-11-12 13:24:07: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\GitProjects\pythonAcquaAutomation\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\GitProjects\pythonAcquaAutomation\.vscode\settings.json')
	at _handleError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:838)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\out\client\extension.js:9:152841)
	at async p.doesFileNeedToBeFixed (c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\out\client\extension.js:39:468556)
	at async c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\out\client\extension.js:39:467683
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\out\client\extension.js:39:467629)
	at async p.updateTestSettings (c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\out\client\extension.js:39:467256)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Pylance language server.
Python interpreter path: .\venv\Scripts\python.exe
> conda info --json
> conda env list
> conda info --json
> conda info --json
Error 2020-11-12 13:24:08: Failed to get interpreter information for 'C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\USERNAME\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-12 13:24:08: Failed to get interpreter information for 'C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\USERNAME\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-12 13:24:08: Failed to get interpreter information for 'C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\USERNAME\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-12 13:24:08: Failed to get interpreter information for 'C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\USERNAME\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\USERNAME\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\USERNAME\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
> conda info --json
> conda env list
```

## Code Snippet / Additional information
N/A

**Comment by judej** [comment]
@iUnknwn, Could you please point me to the pyodbc library you are using?

**Comment by iUnknwn** [comment]
@judej - Sure thing. The library is `pyodbc` in pip, and is available on github here: https://github.com/mkleehammer/pyodbc

**Comment by judej** [comment]
Thanks @iUnknwn, There are no type stubs for this library and it is a compiled module. Therefore, Pylance is unable to get type or completions info for `pyodbc`. At some point, we hope that the authors of 'pyodbc' would create type stubs and improve the developer experience as a result.

**Comment by iUnknwn** [comment]
@judej - Thank you for the clarification, I did not realize the library was compiled. 

As a simple stopgap for my own code, would the easiest solution be to just define a typevar for the connection class, and use that in place of the class name? Or is there a more-preferred workflow for cases like this?

**Comment by jakebailey** [comment]
You can make stubs yourself by making a directory `typings` and then adding a stub for the module in say, `pyodbc/__init__.pyi` or similar.

There's some info here: https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md

(And other useful docs)

**Comment by iUnknwn** [comment]
Thank you!
