### ISSUE TITLE
Pylance has crashed. Would you like to try using a Node.js executable to run the language server?

### ISSUE THREAD

**Issue by Tsukumizu** [microsoft/pylance-release#6055]
2024-06-25 17:23:40.043 [info] (Client) Pylance async client (2024.6.1) started with python extension (2024.8.1)
2024-06-25 17:23:40.493 [info] [Info  - 5:23:40 PM] (2471539) Pylance language server 2024.6.1 (pyright version 1.1.364, commit 0618acc5) starting
2024-06-25 17:23:40.495 [info] [Info  - 5:23:40 PM] (2471539) Server root directory: file:///home/yangcehao/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.1/dist
2024-06-25 17:23:40.497 [info] [Info  - 5:23:40 PM] (2471539) Starting service instance "FinAi_Mapping_Knowledge"
2024-06-25 17:23:40.522 [info] Auto-Indent enabled
2024-06-25 17:23:40.554 [info] Auto-Indent enabled
2024-06-25 17:23:40.558 [info] [Info  - 5:23:40 PM] (2471539) Setting pythonPath for service "FinAi_Mapping_Knowledge": "/data/FinAi_Mapping_Knowledge/yangcehao/anaconda3/envs/kgc/bin/python"
2024-06-25 17:23:40.559 [info] [Info  - 5:23:40 PM] (2471539) Setting environmentName for service "FinAi_Mapping_Knowledge": "3.8.8 (kgc conda)"
2024-06-25 17:23:40.599 [info] [Info  - 5:23:40 PM] (2471539) Assuming Python version 3.8.8.final.0
2024-06-25 17:23:40.720 [info] [Info  - 5:23:40 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/anaconda3
2024-06-25 17:23:41.710 [info] [Info  - 5:23:41 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/jiangxuhui/anaconda3
2024-06-25 17:23:42.741 [info] [Info  - 5:23:42 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/menglong/miniconda3
2024-06-25 17:23:42.914 [info] [Info  - 5:23:42 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/msj/test/.venv
2024-06-25 17:23:43.586 [info] [Info  - 5:23:43 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/qiyiyan/miniconda3
2024-06-25 17:23:45.281 [info] [Info  - 5:23:45 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/qiyiyan/qbw/anaconda3
2024-06-25 17:23:52.539 [info] [Error - 5:23:52 PM] (2471539) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
2024-06-25 17:25:52.558 [info] [Info  - 5:25:52 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/qiyiyan/xzz/ChartLLM/Repo/OneChart/OneChart_code
2024-06-25 17:25:53.213 [info] [Info  - 5:25:53 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/quhuaren/anaconda3
2024-06-25 17:25:53.214 [info] [Info  - 5:25:53 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/quhuaren/envs1/chatpdf
2024-06-25 17:25:53.214 [info] [Info  - 5:25:53 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/quhuaren/envs1/tog
2024-06-25 17:25:58.273 [info] [Info  - 5:25:58 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/yangcehao/anaconda3
2024-06-25 17:25:58.294 [info] [Info  - 5:25:58 PM] (2471539) Auto-excluding /data/FinAi_Mapping_Knowledge/zhanghaohan/miniconda3
2024-06-25 17:27:53.543 [info] 
<--- Last few GCs --->

[2471539:0x5e38930]   249785 ms: Mark-Compact 8048.7 (8232.8) -> 8034.5 (8221.8) MB, 1998.33 / 0.00 ms  (average mu = 0.108, current mu = 0.014) allocation failure; GC in old space requested
[2471539:0x5e38930]   251585 ms: Mark-Compact 8034.5 (8221.8) -> 8034.5 (8221.8) MB, 1799.56 / 0.00 ms  (average mu = 0.059, current mu = 0.000) allocation failure; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

2024-06-25 17:27:53.544 [info]  1: 0xca5580 node::Abort() [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]
 2: 0xb781f9  [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.544 [info]  3: 0xeca4d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.545 [info]  4: 0xeca7b7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.545 [info]  5: 0x10dc505  [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.546 [info]  6: 0x10dca94 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.546 [info]  7: 0x10f3984 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.547 [info]  8: 0x10f419c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.548 [info]  9: 0x10f5812 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.548 [info] 10: 0x10cb65f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.549 [info] 11: 0x10a7d56 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.550 [info] 12: 0x10994cc v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.551 [info] 13: 0x1099634 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.551 [info] 14: 0x13c834d v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.552 [info] 15: 0x13c83f3 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]

2024-06-25 17:27:53.553 [info] 16: 0x14f9003 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/node]
17: 0x7f7eb3ed9ef6 

2024-06-25 17:27:54.313 [info] [Error - 5:27:54 PM] Server process exited with signal SIGABRT.
2024-06-25 17:29:40.901 [info] [Error - 5:29:40 PM] Request textDocument/codeAction failed.
2024-06-25 17:29:40.901 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:29:52.623 [info] [Error - 5:29:52 PM] Request textDocument/codeAction failed.
2024-06-25 17:29:52.623 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:29:52.626 [info] [Error - 5:29:52 PM] Request textDocument/inlayHint failed.
2024-06-25 17:29:52.626 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at o (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2475810)
    at ie.provideInlayHints (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:121500)
2024-06-25 17:29:52.826 [info] [Error - 5:29:52 PM] Request textDocument/codeAction failed.
2024-06-25 17:29:52.826 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:29:54.577 [info] [Error - 5:29:54 PM] Request textDocument/semanticTokens/full failed.
2024-06-25 17:29:54.577 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at he.provideDocumentSemanticTokens (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:111328)
2024-06-25 17:30:32.631 [info] [Error - 5:30:32 PM] Request textDocument/foldingRange failed.
2024-06-25 17:30:32.631 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Z.provideFoldingRanges (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:124748)
2024-06-25 17:30:42.942 [info] [Error - 5:30:42 PM] Sending notification workspace/didChangeConfiguration failed
2024-06-25 17:30:42.942 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendNotification (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2332425)
    at _.sendNotification (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2376046)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-25 17:30:44.084 [info] [Error - 5:30:44 PM] Request textDocument/codeAction failed.
2024-06-25 17:30:44.084 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:30:44.084 [info] [Error - 5:30:44 PM] Request textDocument/inlayHint failed.
2024-06-25 17:30:44.084 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at o (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2475810)
    at ie.provideInlayHints (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:121500)
2024-06-25 17:30:44.286 [info] [Error - 5:30:44 PM] Request textDocument/codeAction failed.
2024-06-25 17:30:44.286 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:30:46.060 [info] [Error - 5:30:46 PM] Request textDocument/semanticTokens/full failed.
2024-06-25 17:30:46.060 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at he.provideDocumentSemanticTokens (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:111328)
2024-06-25 17:30:52.727 [info] [Error - 5:30:52 PM] Request textDocument/codeAction failed.
2024-06-25 17:30:52.727 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:31:04.570 [info] [Error - 5:31:04 PM] Request textDocument/documentHighlight failed.
2024-06-25 17:31:04.570 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at N.provideDocumentHighlights (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:102290)
2024-06-25 17:31:04.821 [info] [Error - 5:31:04 PM] Request textDocument/codeAction failed.
2024-06-25 17:31:04.821 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at z.provideCodeActions (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:103731)
2024-06-25 17:31:04.910 [info] [Error - 5:31:04 PM] Request textDocument/hover failed.
2024-06-25 17:31:04.911 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at I.provideHover (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:101307)
2024-06-25 17:31:05.012 [info] [Error - 5:31:05 PM] Request textDocument/definition failed.
2024-06-25 17:31:05.012 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at E.provideDefinition (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:100255)
2024-06-25 17:31:14.853 [info] [Error - 5:31:14 PM] Request textDocument/documentHighlight failed.
2024-06-25 17:31:14.853 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at N.provideDocumentHighlights (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:102290)
2024-06-25 17:31:24.022 [info] [Error - 5:31:24 PM] Request textDocument/foldingRange failed.
2024-06-25 17:31:24.023 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Z.provideFoldingRanges (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:124748)
2024-06-25 17:31:25.627 [info] [Error - 5:31:25 PM] Request textDocument/documentHighlight failed.
2024-06-25 17:31:25.627 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at N.provideDocumentHighlights (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:102290)
2024-06-25 17:31:30.466 [info] [Error - 5:31:30 PM] Request textDocument/inlayHint failed.
2024-06-25 17:31:30.466 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at o (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2475810)
    at ie.provideInlayHints (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:121500)
2024-06-25 17:31:31.113 [info] [Error - 5:31:31 PM] Request textDocument/inlayHint failed.
2024-06-25 17:31:31.113 [info] Error: Connection is disposed.
    at pe (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2331582)
    at Object.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2333886)
    at _.sendRequest (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2374787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at o (/home/yangcehao/.vscode-server/extensions/ms-python.python-2024.8.1/out/client/extension.js:2:2475810)
    at ie.provideInlayHints (/home/yangcehao/.vscode-server/cli/servers/Stable-5437499feb04f7a586f677b155b039bc2b3669eb/server/out/vs/workbench/api/node/extensionHostProcess.js:155:121500)

I have followed #5891 to solve my problem, but I failed. I try to exclude some files, but it doesn't work.

![image](https://github.com/microsoft/pylance-release/assets/143052241/6cf701bb-4dcc-46bf-adc4-8d2909333aa6)

**Comment by heejaechang** [comment]
I think you are including your `.venv` and `anacona3` and `minianacona` folders in your workspace folders. either create your user file folder outside of that folder or make sure to exclude them.

dumping every files in a folder and open that folder won't work well with pylance

**Comment by Tsukumizu** [comment]
After exclude lots of files as much as I can, pylance works again.
![image](https://github.com/microsoft/pylance-release/assets/143052241/9c879f6d-4bfc-4887-98e4-f32fd8e65ad5)

**Comment by heejaechang** [comment]
just FYI. usually, we do `auto-excluding` such as any folder starting with `.` or `conda` or `virtualenv` folder, but it is based on a heuristic, so if a folder doesn't follow common patterns, our `auto-exclude` might fail to pick up some folders to `auto-exclude`.

also, if you put explicit `exclude`, `auto-exclude` will be disabled, and you need to put all folders, `auto-exclude` would have picked up, explicitly now.
