### ISSUE TITLE
Getting error Python Tools crashed when installing in VS Code Insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/pylance-release#615]
## Environment data

-   Language Server version: Latest from marketplace
-   OS and version: Mac
-   Python version (& distribution if applicable, e.g. Anaconda): Latest from marketplace

FYI:
* turned off insiders.

## Expected behaviour

Should work

## Actual behaviour

Crashes with error `The Python tools Server crashed 5 times....`

## Steps
* Install VS Code insiders (latest)
* Install Python extension from marketplace (latest)
* Change language server to `pylance` in settings
* Prompted to install `Pylance`, install it
* Prompted to reload VS Code, reload vs code
* Keep getting the error message

## Logs

```
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module '/Users/donjayamanne/.vscode-insiders/extensions/ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 1:49:08 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module '/Users/donjayamanne/.vscode-insiders/extensions/ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 1:49:08 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module '/Users/donjayamanne/.vscode-insiders/extensions/ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 1:49:08 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module '/Users/donjayamanne/.vscode-insiders/extensions/ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 1:49:08 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module '/Users/donjayamanne/.vscode-insiders/extensions/ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 1:49:09 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by jakebailey** [comment]
Given `ms-python.python-2020.11.358366026/nodeLanguageServer.0.0.346/server.bundle.js`, you must have the really really old dogfooding options set in your config. Make sure you don't have any download channels or blob storage names enabled.
