### ISSUE TITLE
Pylance hints not working in Jupyter Notebook in Remote Tunnel

### ISSUE THREAD

**Issue by this-josh** [microsoft/pylance-release#6330]
## Environment data

-   Pylance version: 2024.8.2
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12

The behaviour in #5071  which was also mentioned here https://github.com/microsoft/vscode/issues/196740 seems to be occurring again.

At the end of the #5071 issue there seems to be at least four people still experiencing this and it was advised to open a new ticket. Given that this is the same issue resurfacing I'm keeping the issue report minimal

When I try to execute a cell I get `NO notebook document for 'file:////` and the cell fails to run.

**Comment by heejaechang** [comment]
looks like dup of https://github.com/microsoft/pylance-release/issues/5034

**Comment by KacieKK** [comment]
Hey @this-josh, thanks for posting this issue. I am trying to reproduce this issue, Can you please provide a small code sample and log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)? 

Or could you confirm that the below steps repro this issue for you? (quoted from #5071)

> Open VS code from WSL
> Create a new notebook
> Create a cell
> Deselect the code
> Hit 'dd'
> Hit 'z'
> Repeat until crash

**Comment by this-josh** [comment]
I'm having difficulty creating a reproducible example as the error occurs randomly around 5 minutes after opening a notebook. 

At the time of failure the Python Language produces this error each time I write a character in the notebook 
`2024-10-22 08:10:03.374 [info] [Error - 08:10:03] (2648257) Received change text document command for closed file file:///path/to/my/notebook.ipynb.py#X16sdnNjb2RlLXJlbW90ZQ%3D%3D`

**Comment by KacieKK** [comment]
Could you share the VS Code version you're using? Might be related to this one: https://github.com/microsoft/pylance-release/issues/5543

**Comment by Sjlver** [comment]
I'm seeing probably the same issue.

Here's what I do; It's not super clear to me how to reproduce this.

- In WSL2, create a new folder, create a new venv (`python3 -m venv .venv; source .venv/bin/activate`)
- Start VSCode in the folder `code .`
- Create a new notebook. Select the python from venv.
- Add a cell; run. VSCode will ask to install Jupyter etc.
- Make some modifications...

Errors in Output: Python Language Server:

`2024-10-29 09:52:23.992 [info] [Error - 9:52:23 AM] (20498) Received change text document command for closed file file:///home/redacted/foo.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D`

Version:

```
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

Some stack traces from developer tools:

```
INFO Started local extension host with pid 4928.
log.ts:419  INFO Invoking resolveAuthority(wsl)...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][662ms] returned WebSocket(127.0.0.1:64358)
log.ts:419  INFO resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:64358)' after 664 ms
log.ts:419  INFO Creating a socket (renderer-Management-577fb71d-b77c-41db-8861-9c8d79a238e3)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-0f35599f-cd97-46bc-b3c5-80a9d1e64c92)...
log.ts:419  INFO Creating a socket (renderer-Management-577fb71d-b77c-41db-8861-9c8d79a238e3) was successful after 122 ms.
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-0f35599f-cd97-46bc-b3c5-80a9d1e64c92) was successful after 285 ms.
console.ts:137 [Extension Host] Checking whether to register object drop extension
console.ts:137 [Extension Host] Registering object drop provider
console.ts:137 [Extension Host] Registered object drop provider
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.sql.
log.ts:419  INFO [perf] Render performance baseline is 59ms
log.ts:439   ERR adding EXISTING notebook file:///home/REDACTED/projects/REDACTED/py/demographics.ipynb : Error: adding EXISTING notebook file:///home/REDACTED/projects/REDACTED/py/demographics.ipynb 
	at nh.$acceptDocumentAndEditorsDelta (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:13379)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
  ...
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
console.ts:137 [Extension Host] info 09:49:19.251: Jupyter Extension: Starting Kernel (Python Path: ~/projects/REDACTED/py/.venv/bin/python, Venv, 3.10.12) for '~/projects/REDACTED/py/demographics.ipynb' (disableUI=true)
console.ts:137 [Extension Host] info 09:49:19.694: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
console.ts:137 [Extension Host] info 09:49:19.698: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -m ipykernel_launcher --f=/home/REDACTED/.local/share/jupyter/runtime/kernel-v31489eb49c8330c747d7d9f6212d52f0262bc1e2b.json
    > cwd: //home/REDACTED/projects/REDACTED/py
console.ts:137 [Extension Host] info 09:49:19.707: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -m pip list
console.ts:137 [Extension Host] info 09:49:20.661: Jupyter Extension: Kernel successfully started
console.ts:137 [Extension Host] info 09:49:20.669: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python /home/REDACTED/.vscode-server/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/pythonFiles/printJupyterDataDir.py
console.ts:137 [Extension Host] info 09:49:40.082: Jupyter Extension: Dispose Kernel '~/projects/REDACTED/py/demographics.ipynb' associated with '~/projects/REDACTED/py/demographics.ipynb'
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
log.ts:439   ERR adding EXISTING notebook file:///home/REDACTED/projects/REDACTED/py/test.ipynb : Error: adding EXISTING notebook file:///home/REDACTED/projects/REDACTED/py/test.ipynb 
	at nh.$acceptDocumentAndEditorsDelta (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:13379)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
	...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
console.ts:137 [Extension Host] info 09:50:03.614: Jupyter Extension: Starting Kernel (Python Path: ~/projects/REDACTED/py/.venv/bin/python, Venv, 3.10.12) for '~/projects/REDACTED/py/test.ipynb' (disableUI=true)
console.ts:137 [Extension Host] info 09:50:03.623: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
console.ts:137 [Extension Host] info 09:50:03.709: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -m ipykernel_launcher --f=/home/REDACTED/.local/share/jupyter/runtime/kernel-v3eddd17e7f77b49836dfc39952a482bcca7778918.json
    > cwd: //home/REDACTED/projects/REDACTED/py
console.ts:137 [Extension Host] info 09:50:04.260: Jupyter Extension: Kernel successfully started
console.ts:137 [Extension Host] info 09:51:34.199: Jupyter Extension: Starting Kernel (Python Path: ~/projects/REDACTED/py/.venv/bin/python, Venv, 3.10.12) for '~/projects/REDACTED/py/demographics.ipynb' (disableUI=true)
console.ts:137 [Extension Host] info 09:51:34.218: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
console.ts:137 [Extension Host] info 09:51:34.275: Jupyter Extension: Process Execution: ~/projects/REDACTED/py/.venv/bin/python -m ipykernel_launcher --f=/home/REDACTED/.local/share/jupyter/runtime/kernel-v3139381d6986310f2e11215649ba510ef7bbaa95a.json
    > cwd: //home/REDACTED/projects/REDACTED/py
console.ts:137 [Extension Host] info 09:51:35.167: Jupyter Extension: Kernel successfully started
console.ts:137 [Extension Host] info 09:52:18.616: Jupyter Extension: Dispose Kernel '~/projects/REDACTED/py/demographics.ipynb' associated with '~/projects/REDACTED/py/demographics.ipynb'
log.ts:439   ERR unknown text editor: 42d6d461-d6cc-4d6b-947b-424d679e7cde. known editors: 6ba23677-263a-4c0e-b55c-6341416559fa : Error: unknown text editor: 42d6d461-d6cc-4d6b-947b-424d679e7cde. known editors: 6ba23677-263a-4c0e-b55c-6341416559fa 
	at nh.getEditorById (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5598)
	at wb.$acceptEditorPropertiesChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16972)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
  ...
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
2log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/projects/REDACTED/py/demographics.ipynb': Error: NO notebook document for 'file:///home/REDACTED/projects/REDACTED/py/demographics.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at DU.$acceptModelChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16411)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
  ...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
console.ts:137 [Extension Host] info 09:52:48.366: Jupyter Extension: Dispose Kernel '~/projects/REDACTED/py/test.ipynb' associated with '~/projects/REDACTED/py/test.ipynb'
log.ts:439   ERR unknown text editor: 42d6d461-d6cc-4d6b-947b-424d679e7cde. known editors:  : Error: unknown text editor: 42d6d461-d6cc-4d6b-947b-424d679e7cde. known editors:  
	at nh.getEditorById (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5598)
	at wb.$acceptEditorPropertiesChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16972)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
  ...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

Extensions:

```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2024.9.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
```

```
Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2024.10.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance
```

```
Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2024.16.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
```

**Comment by Sjlver** [comment]
I'm still struggling to find a simple reproducer; sorry. For some notebooks, the problem happens consistently after a few minutes. It seems that having some import helps.

Here's something I tried now:

- Create a new folder, a venv, start code, create a notebook as described above
- The notebook currently contains the two cells below
- I'm doing a bit of editing, including adding things that would cause errors that pylance can find

This is the current state of the notebook:

```
import pandas as pd
import numpy as np
```

```
df = pd.DataFrame(
    np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    columns=['a', 'b', 'c']
)
df.loc["a"] = foo
with pd.option_context("display.max_rows", 100):
    display(df)
```

The problem first happened when I added the `df.loc["a"] = foo` line.

Python language server output shows `2024-10-29 10:24:14.352 [info] [Error - 10:24:14 AM] (29738) Received change text document command for closed file file:///home/jbw/repro/repro.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D`

Dev tools show:

```
INFO Started local extension host with pid 16768.
log.ts:419  INFO Invoking resolveAuthority(wsl)...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
log.ts:419  INFO [LocalProcess0][resolveAuthority(wsl,1)][673ms] returned WebSocket(127.0.0.1:64537)
log.ts:419  INFO resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:64537)' after 673 ms
log.ts:419  INFO Creating a socket (renderer-Management-1a6e70f9-e3f5-4011-b5d7-cae4c94381d8)...
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-1c2c5d40-e559-48a4-92e2-5efa718cae8d)...
log.ts:419  INFO Creating a socket (renderer-Management-1a6e70f9-e3f5-4011-b5d7-cae4c94381d8) was successful after 92 ms.
log.ts:419  INFO Creating a socket (renderer-ExtensionHost-1c2c5d40-e559-48a4-92e2-5efa718cae8d) was successful after 234 ms.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Users/ltlyg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/REDACTED/.vscode-server/extensions/mtxr.sqltools-0.28.3/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Users/ltlyg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/REDACTED/.vscode-server/extensions/mtxr.sqltools-0.28.3/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:419  INFO [perf] Render performance baseline is 71ms
console.ts:137 [Extension Host] Checking whether to register object drop extension
console.ts:137 [Extension Host] Registering object drop provider
console.ts:137 [Extension Host] Registered object drop provider
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
log.ts:439   ERR adding EXISTING notebook file:///home/REDACTED/repro/repro.ipynb : Error: adding EXISTING notebook file:///home/REDACTED/repro/repro.ipynb 
	at nh.$acceptDocumentAndEditorsDelta (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:13379)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
	at Zb.Q (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155532)
...
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
console.ts:137 [Extension Host] info 10:21:51.536: Jupyter Extension: Starting Kernel (Python Path: ~/repro/.venv/bin/python, Venv, 3.10.12) for '~/repro/repro.ipynb' (disableUI=true)
console.ts:137 [Extension Host] info 10:21:52.122: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python -m pip list
console.ts:137 [Extension Host] info 10:21:52.131: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
console.ts:137 [Extension Host] info 10:21:52.138: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python -m ipykernel_launcher --f=/home/REDACTED/.local/share/jupyter/runtime/kernel-v3c760129574c1c4f791a671aa5abb4f29fba272a9.json
    > cwd: //home/REDACTED/repro
console.ts:137 [Extension Host] info 10:21:53.045: Jupyter Extension: Kernel successfully started
console.ts:137 [Extension Host] info 10:21:53.053: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python /home/REDACTED/.vscode-server/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/pythonFiles/printJupyterDataDir.py
2console.ts:137 [Extension Host] info 10:22:52.327: Jupyter Extension: Disposing request as the cell (1) was deleted ~/repro/repro.ipynb
console.ts:137 [Extension Host] info 10:22:52.328: Jupyter Extension: Dispose Kernel '~/repro/repro.ipynb' associated with '~/repro/repro.ipynb'
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
console.ts:137 [Extension Host] info 10:23:03.746: Jupyter Extension: Starting Kernel (Python Path: ~/repro/.venv/bin/python, Venv, 3.10.12) for '~/repro/repro.ipynb' (disableUI=true)
console.ts:137 [Extension Host] info 10:23:03.760: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
console.ts:137 [Extension Host] info 10:23:03.804: Jupyter Extension: Process Execution: ~/repro/.venv/bin/python -m ipykernel_launcher --f=/home/REDACTED/.local/share/jupyter/runtime/kernel-v3dda9f9854777fe6546710fa3c5bd581b9b534a63.json
    > cwd: //home/REDACTED/repro
console.ts:137 [Extension Host] info 10:23:04.663: Jupyter Extension: Kernel successfully started
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
console.ts:137 [Extension Host] info 10:24:09.854: Jupyter Extension: Dispose Kernel '~/repro/repro.ipynb' associated with '~/repro/repro.ipynb'
log.ts:439   ERR unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  : Error: unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  
	at nh.getEditorById (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5598)
	at wb.$acceptEditorPropertiesChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16972)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
...
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb': Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at DU.$acceptModelChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16411)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
...
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:429  WARN Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at IU.$participateInSave (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:15492)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
	at Zb.Q (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155532)
	at Zb.M (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:154583)
...
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb': Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at DU.$acceptDirtyStateChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16528)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
	at Zb.Q (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155532)
...
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb': Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at DU.$acceptModelSaved (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16612)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  : Error: unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  
	at nh.getEditorById (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5598)
	at wb.$acceptEditorPropertiesChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16972)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb': Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at DU.$acceptModelChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16411)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
log.ts:439   ERR NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb': Error: NO notebook document for 'file:///home/REDACTED/repro/repro.ipynb'
	at nh.getNotebookDocument (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5868)
	at bb.$cellExecutionChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:25626)
...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
4log.ts:439   ERR unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  : Error: unknown text editor: 1ddaceb1-9613-4685-bdb2-ee6adfc8d152. known editors:  
	at nh.getEditorById (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:5598)
	at wb.$acceptEditorPropertiesChanged (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:155:16972)
	at Zb.S (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155752)
	at Zb.Q (file:///home/REDACTED/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:31:155532)
...
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by KacieKK** [comment]
If the issue reproduces without pylance, the problem would not be related. You could log an issue on the Jupyter extension here:
https://github.com/microsoft/vscode-jupyter/issues

**Comment by Sjlver** [comment]
Done: https://github.com/microsoft/vscode-jupyter/issues/16193

**Comment by heejaechang** [comment]
Closing this older Pylance issue.

This turned out not to be Pylance-specific: the notebook hang (`ERR NO notebook document`, `ERR unknown text editor`, etc.) reproduces even with Pylance disabled, and the upstream investigation traced it to the **Continue** extension. See microsoft/vscode-jupyter#16193 and the Continue bug report: https://github.com/continuedev/continue/issues/1463.

Workaround: disable the Continue extension (or upgrade once they ship a fix).
