### ISSUE TITLE
pylance can't restart: Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists

### ISSUE THREAD

**Issue by WarmongeringBeaver** [microsoft/pylance-release#6378]
## Environment data
- Pylance version: `v2024.9.1`
- VScode "About" pannel:
```
Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.6-10-MANJARO
```
- Python version: `3.12.5` from Anaconda.
- I'm running VSCode Remote.

Note that I remember encountering the situation of pylance being unable to restart from quite a while back (multiple vscode / pylance versions), but I can't tell the exact error(s) I've encountered before.

## Repro Steps

1. Hit the "Python: Restart Language Server" command after a pylance slowdown.
2. Observe pylance dying and _not restarting_.

## Expected behavior

Restarted pylance.

## Actual behavior

No pylance anymore.

Restarting VSCode fixes this issue.

## Logs

`"python.analysis.logLevel": "Trace"` is set in my user settings.

<details><summary>Output of the "Python" tab</summary>
<p>

```
2024-09-11 15:48:22.404 [error] [
  'Disposing language server, Class name = h, completed in 0ms, has a falsy return value, , Return Value: undefined',
  Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
      at createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:161:163942)
      at Object.createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:171:38483)
      at _0xbcc266.createStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:275986)
      at _0xbcc266.updateStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:289545)
      at _0xbcc266.activate (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:273499)
      at _0x31c314 (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:321112)
      at _0x2858ed (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:246910)
      at _0xe3bdb8._startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:193154)
      at _0xe3bdb8._createNewRequest (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:192675)
      at _0xe3bdb8._enqueueRequestAndWaitForRun (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191917)
      at _0xe3bdb8.startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191380)
      at h.start (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/out/client/extension.js:2:39659)
]
2024-09-11 15:48:22.405 [error] [
  'Stopping language server, Class name = d, completed in 2ms, has a falsy return value, , Return Value: undefined',
  Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
      at createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:161:163942)
      at Object.createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:171:38483)
      at _0xbcc266.createStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:275986)
      at _0xbcc266.updateStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:289545)
      at _0xbcc266.activate (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:273499)
      at _0x31c314 (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:321112)
      at _0x2858ed (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:246910)
      at _0xe3bdb8._startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:193154)
      at _0xe3bdb8._createNewRequest (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:192675)
      at _0xe3bdb8._enqueueRequestAndWaitForRun (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191917)
      at _0xe3bdb8.startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191380)
      at h.start (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/out/client/extension.js:2:39659)
]
2024-09-11 15:48:22.406 [error] [
  'Restarting language server, Class name = d, completed in 3ms, has a falsy return value, , Return Value: undefined',
  Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
      at createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:161:163942)
      at Object.createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:171:38483)
      at _0xbcc266.createStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:275986)
      at _0xbcc266.updateStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:289545)
      at _0xbcc266.activate (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:273499)
      at _0x31c314 (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:321112)
      at _0x2858ed (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:246910)
      at _0xe3bdb8._startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:193154)
      at _0xe3bdb8._createNewRequest (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:192675)
      at _0xe3bdb8._enqueueRequestAndWaitForRun (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191917)
      at _0xe3bdb8.startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191380)
      at h.start (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/out/client/extension.js:2:39659)
]
2024-09-11 15:48:22.406 [error] [
  'Failed to restart language server, Class name = d, completed in 3ms, has a falsy return value, , Return Value: undefined',
  Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
      at createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:161:163942)
      at Object.createLanguageStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/out/vs/workbench/api/node/extensionHostProcess.js:171:38483)
      at _0xbcc266.createStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:275986)
      at _0xbcc266.updateStatusItem (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:289545)
      at _0xbcc266.activate (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:273499)
      at _0x31c314 (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:321112)
      at _0x2858ed (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:246910)
      at _0xe3bdb8._startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:193154)
      at _0xe3bdb8._createNewRequest (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:192675)
      at _0xe3bdb8._enqueueRequestAndWaitForRun (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191917)
      at _0xe3bdb8.startClient (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.1/dist/extension.bundle.js:1:191380)
      at h.start (/import/bc_users/biocomp/tboyer/.vscode-server/extensions/ms-python.python-2024.14.0-linux-x64/out/client/extension.js:2:39659)
]
```
</p>
</details> 

The "Python Language Server" tab has no output since pylance crashed.

**Comment by rchiodo** [comment]
I can reproduce the issue. Just run "Python Restart Language Server".

An alternative that does work is run "Developer: Restart Extension Host". This accomplishes the same thing as restarting the language server (it restarts the python extension as well).

I believe the root cause must be something in the new LSP language client that we recently updated to. It likely isn't handling shutdown correctly.

**Comment by AlexanderPodorov** [comment]
@rchiodo , this does not work for my case.
I've updated the pylance from `v2024.8.2` to `v2024.9.1` and file analysis is running and never completed.
I've tried to run "Python Restart Language Server" and "Developer: Restart Extension Host", but none of them worked.
Once I downgraded back to `v2024.8.2` it got back to normal.

**Comment by rchiodo** [comment]
@AlexanderPodorov can you open a new issue? I'm guessing we're crashing for some reason. Restarting won't fix the crash as it will just repro over and over again.

**Comment by AlexanderPodorov** [comment]
@rchiodo , done!
https://github.com/microsoft/pylance-release/issues/6386

**Comment by braindevices** [comment]
affect me also

**Comment by man2machine** [comment]
I also have this error

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.9.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249103-2-October-2024-PreRelease)
