### ISSUE TITLE
File analysis runs indefinitely after upgrading to v2024.9.1

### ISSUE THREAD

**Issue by AlexanderPodorov** [microsoft/pylance-release#6386]
## Environment data

-   Pylance version: v2024.9.1
-   OS and version: MacOS 13.0.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.5

## Repro Steps

Upgrade to the specified version and file analysis runs indefinitely.

## Expected behavior

Upgrade to the specified version and file analysis should complete in a reasonable time.

## Actual behavior

Upgrade to the specified version and file analysis runs indefinitely.

## Logs
Repeated lines like that:
```
2024-09-12 13:59:15.147 [error] [
  `Failed to start language server, Class name = h, completed in 0ms, has a falsy return value, Arg 1: <Uri:/Users/..>, Arg 2:

[Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists

2024-09-12 13:59:15.148 [error] [
  'Starting language server, Class name = d, completed in 1ms, has a falsy return value, , Return Value: undefined',
  [Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists

2024-09-12 13:59:15.148 [error] [
  'Restarting language server, Class name = d, completed in 2ms, has a falsy return value, , Return Value: undefined',
  [Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
```

**Comment by phi-friday** [comment]
In my case, the first time I run `vscode`(with pylance), it's fine.
But when I run restart server, the same error occurs.
And when I restart `vscode`(ie. reload), it's fine again.

**Comment by heejaechang** [comment]
I can't repro the exact thing but I can see `LanguageStatusItem` on `typeCheckingMode` start behaving weirdly if I clicks it multiple times + reloading the server.

**Comment by AlexanderPodorov** [comment]
@heejaechang , I guess it might be different from project to project. Like a project might use a particular pylance/pyright "feature" that does not work v2024.9.1 and causes the whole analysis to fail/run indefinitely. Downgrading to previous release version solves the problem.

**Comment by phi-friday** [comment]
> @heejaechang , I guess it might be different from project to project. Like a project might use a particular pylance/pyright "feature" that does not work v2024.9.1 and causes the whole analysis to fail/run indefinitely. Downgrading to previous release version solves the problem.

If, as you say, my setup is causing the error, I hope this config file(`pyrightconfig.json`) will help.
### case 1
```json
{
    "include": [
        "src/app",
        "tests"
    ],
    "extraPaths": [
        "src"
    ],
    "ignore": [
        "src/rpc/output",
        "typings/google/rpc",
    ],
    "typeCheckingMode": "strict",
    "pythonVersion": "3.12",
    "pythonPlatform": "Linux",
    "reportMissingTypeStubs": false,
    "reportInconsistentConstructor": false,
    "reportUnknownArgumentType": false,
    "reportOverlappingOverload": false,
    "reportUnknownVariableType": false,
    "reportUnknownMemberType": false,
    "reportUnnecessaryIsInstance": false,
    "reportUnnecessaryComparison": false,
    "reportDeprecated": false,
    "reportPrivateUsage": false,
    "reportUnnecessaryTypeIgnoreComment": true,
    "reportImplicitOverride": true,
    "executionEnvironments": [
        {
            "root": "src/tests",
            "reportUnknownParameterType": false,
            "reportMissingParameterType": false,
        },
    ],
    "enableExperimentalFeatures": true,
}
```
### case 2
```json
{
    "include": [
        "src/{{ some private package }}",
        "tests"
    ],
    "typeCheckingMode": "strict",
    "pythonVersion": "3.12",
    "pythonPlatform": "Linux",
    "reportMissingTypeStubs": false,
    "reportInconsistentConstructor": false,
    "reportUnknownArgumentType": false,
    "reportOverlappingOverload": false,
    "reportUnknownVariableType": false,
    "reportUnknownMemberType": false,
    "reportUnnecessaryIsInstance": false,
    "reportUnnecessaryComparison": false,
    "reportDeprecated": false,
    "reportPrivateUsage": false,
    "reportUnnecessaryTypeIgnoreComment": true,
    "reportImplicitOverride": true,
    "reportIncompatibleVariableOverride": false,
}
```
### case 3
```json
{
    "include": [
        "src/timeout_executor",
        "src/tests"
    ],
    "typeCheckingMode": "strict",
    "pythonVersion": "3.9",
    "pythonPlatform": "Linux",
    "reportMissingTypeStubs": false,
    "reportInconsistentConstructor": false,
    "reportUnknownArgumentType": false,
    "reportOverlappingOverload": false,
    "reportUnknownVariableType": false,
    "reportUnknownMemberType": false,
    "reportUnnecessaryIsInstance": false,
    "reportUnnecessaryComparison": false,
    "reportDeprecated": false,
    "reportPrivateUsage": false,
    "reportUnnecessaryTypeIgnoreComment": true,
    "reportImplicitOverride": true,
    "executionEnvironments": [
        {
            "root": "src/tests",
            "reportUnknownParameterType": false,
            "reportMissingParameterType": false,
        }
    ]
}
```
This is the config file for the environment I'm currently experiencing the error in, and it works fine when I downgrade to an earlier version(like `2024.8.2`).

**Comment by bschnurr** [comment]
You could also try pre-release versions.

**Comment by phi-friday** [comment]
> You could also try pre-release versions.

I installed the pre-release(`2024.9.101`) as you suggested, but I am getting the same error as below.

```log
2024-09-20 14:14:53.568 [error] [
  'Failed to restart language server, Class name = d, completed in 8ms, has a falsy return value, , Return Value: undefined',
  Error: LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists
      at createLanguageStatusItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:161:163942)
      at Object.createLanguageStatusItem (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:38483)
      at _0x6c0f12.createStatusItem (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:263680)
      at _0x6c0f12.updateStatusItem (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:277277)
      at _0x6c0f12.activate (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:261141)
      at _0x13135a (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:308522)
      at _0x59b22e (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:234115)
      at _0x2a922c._startClient (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:179543)
      at _0x2a922c._createNewRequest (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:179058)
      at _0x2a922c._enqueueRequestAndWaitForRun (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:178273)
      at _0x2a922c.api (/Users/***/.vscode/extensions/ms-python.vscode-pylance-2024.9.101/dist/extension.bundle.js:1:177735)
      at h.start (/Users/***/.vscode/extensions/ms-python.python-2024.14.1-darwin-arm64/src/client/activation/node/languageServerProxy.ts:49:31)
]
```

**Comment by phi-friday** [comment]
I've verified that it works fine on `2024.8.101`. Some of the commits applied to `2024.8.102` or `2024.8.104` seem to be causing the problem.

**Comment by AlexanderPodorov** [comment]
@bschnurr , I've tried two most recent pre-release versions: `2024.9.100` and `2024.9.101`, same issue.

**Comment by kcajf** [comment]
I'm also seeing this in `v2024.9.2`

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.9.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249103-2-October-2024-PreRelease)

**Comment by rchiodo** [comment]
You're still seeing the `LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists`? Can you include your log output?

**Comment by rchiodo** [comment]
I don't think this solved your file analysis running forever problem. That's likely some call chain that is taking too long to analyze. 

For that we'd need example source that causes the issue. I'll reopen this as the bug that was fixed was restarting the language server.

**Comment by AlexanderPodorov** [comment]
@rchiodo, you're right, there's no `LanguageStatusItem with id 'python.analysis.typeCheckingMode' ALREADY exists` anymore. However I'm seeing these two last lines:
```
2024-10-02 20:38:13.964 [info] (Client) The existing extension didn't exit within 10 seconds. New instance will start, but you might encounter issues.
2024-10-02 20:38:13.964 [info] (Client) Pylance async client (2024.9.103) started with python extension (2024.15.2024091301)
```
Looks like pylance partially processed/analysed the repo, but it took more than 10 secs, so it restarted itself and failed to process remaining files.

**Comment by AlexanderPodorov** [comment]
I've tried `v2024.9.103` with a few tiny projects, it works well. But then it hangs on a bigger one.

**Comment by rchiodo** [comment]
Can you share that larger one? There's usually one import path that causes the issue. It has some really deep recursion or something along those lines and adding that one file to the exclude path can speed things up drastically

**Comment by AlexanderPodorov** [comment]
I can't do it, because this is the private repo outside of github.
What would be the best way to investigate it locally?

**Comment by rchiodo** [comment]
Yes, actually we do. 

If you add these to your settings.json:

```jsonc
   "python.analysis.logLevel": "Trace",
  "python.analysis.logTypeEvaluationTime": true,
  "python.analysis.typeEvaluationTimeThreshold": 1000,
```

The log should output any code path that takes longer than a second. This should give you some idea what import paths are taking a long time.

**Comment by rchiodo** [comment]
Here's the PR where Heejae added this support to Pyright. 

https://github.com/microsoft/pyright/pull/7729

It should explain the output a bit. Your output might have mangled names in it though as pyright source in the shipping bits has been minimized. But the method names from your imports should still be there.

Like the example Heejae had:

```
 validateCallArguments ["dict([(('algebraic', True), se <shortened> " (..sympy.core.assumptions_generated) [42:21]] (9006ms)
```

That might not say `validateCallArguments` but it should list the import at the end (in this example it was sympy.core.assumptions_generated)

**Comment by AlexanderPodorov** [comment]
I've added these 3 lines to settings.json. Not sure what I should look at.
Btw, last two lines are displayed as "unknown configuration settings":
![image](https://github.com/user-attachments/assets/3c1497a0-f99a-4159-911e-bf872d1417f8)

**Comment by rchiodo** [comment]
Look at that PR I linked to. It describes the extra logging that should happen. There will be a LOT of logging in the 'Python Language Server' output, but it should show long analysis chains.

**Comment by AlexanderPodorov** [comment]
I did, not sure what I should do, which settings to add or adjust.

**Comment by rchiodo** [comment]
You have to parse the log output and look for long chains that are taking a long time.

Each one should list out the time it takes.

So for the example I linked to (just one function's analysis):

```
 validateCallArguments ["dict([(('algebraic', True), se <shortened> " (..sympy.core.assumptions_generated) [42:21]] (9006ms)
```

You could then tell us about it and we could investigate (if it's a 3rd party library)

or

You'd take just the code in that function and show it to us here and see if we can reproduce the long time with just that code.

Alternatively, you can take just that code and run pyright on it standalone:

**Comment by AlexanderPodorov** [comment]
I don't see any particular chains that take long. The analysis runs a few seconds and just stops, nothing is written to the logs.

**Comment by rchiodo** [comment]
And the UI says something is still being analyzed? Can you check if the CPU is being used by a code.exe process?

**Comment by rchiodo** [comment]
We may need the profiling output instead. This command:

`Pylance: Start Profiling`. That will generate a CPU profile of the pylance bits that you can upload to us.

**Comment by AlexanderPodorov** [comment]
Yeah, Code Helper (Plugin) takes 100% (mostly likely the entire CPU core):
![image](https://github.com/user-attachments/assets/57104368-3578-480c-b7a1-c2af794b5c0f)

**Comment by rchiodo** [comment]
If you run the `Pylance : Start Profiling` after opening the workspace, it should show us what's taking so much CPU. (Run `Pylance: Stop Profiling after a couple of minutes to generate the actual text files we need you to upload).

**Comment by AlexanderPodorov** [comment]
I've generated the profile file. Where should I upload it?

**Comment by AlexanderPodorov** [comment]
Yes, that's what output showed.

**Comment by rchiodo** [comment]
There should be another file for the background thread. Something like `pylance_2024.9.103_bg_id_1.cpuprofile`. Is it not in the same folder as your fg file?

**Comment by rchiodo** [comment]
Maybe the background thread crashed. That should show up in the log output though.

**Comment by AlexanderPodorov** [comment]
> Is it not in the same folder as your fg file?

This folder has just this file.

> Can you get the actual command line for the busy Code (plugin) process?

Not sure what you mean by "command line".

**Comment by rchiodo** [comment]
VS Code runs a number of copies of itself. Each of those has a different command line. For example on windows, we get something like so:

![Image](https://github.com/user-attachments/assets/e44d481f-090f-4d7b-b4e0-a5e97fee1ddf)

That's just one of the processes that VS code runs. The one on your machine that's taking all of the CPU may or may not be the pylance server. We need to see what the actual command line is. 

You'd have to open a terminal and do something like this:

```
ps -eo pid,comm,args,%cpu | grep Code
```

**Comment by AlexanderPodorov** [comment]
Btw, I have a "candidate" file that might cause issues.
It has several long unions and a couple of long `match` statements. For testing purposes I cleared the entire file, re-run Python language server and analysis has been completed, but a second later started again and started hanging as usual.

**Comment by rchiodo** [comment]
You can run just that file with Pyright and see if analysis takes a long time. That's essentially what Pylance is doing under the covers.

**Comment by heejaechang** [comment]
can you set this in `settings.json`

https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-type-evaluation-related-data-in-the-log

and do this command to save logs

https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs-using-commands

and stop once hang is done ?

...

I think the problem of `profile` was we couldn't stop `bg` so `bg` profile couldn't be saved.

**Comment by AlexanderPodorov** [comment]
@rchiodo , this is the output of your command:
```
85685 /Applications/Vi /Applications/Visual Studio Code.app/Contents/MacOS/Electron       0.0
85687 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Electro   0.0
85688 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   4.0
85689 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
86006 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
86008 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.1
93512 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   2.3
93518 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
96634 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
96642 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
96647 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
96649 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He   0.0
97360 /Applications/Vi /Applications/Visual Studio Code.app/Contents/Frameworks/Code He 100.0
97845 grep             grep Code                                                          0.0
```

**Comment by AlexanderPodorov** [comment]
@heejaechang , yes, I did all of these. I can't stop it once hang is done, the analysis seemed to never end.

**Comment by AlexanderPodorov** [comment]
Just ran `pyright` for the candidate file, yes, it's still hanging.

**Comment by bschnurr** [comment]
You could try adding verboseOutput: true to the pyright config file (or add --verbose on the command line). That might give us a few more details.

**Comment by erictraut** [comment]
If you're able to isolate the code that results in the hang and give me repro steps, I'd be happy to take a look at it.

One technique that I use in cases like this is to bisect the file's contents, commenting out half of the functions / classes in the file at a time. This typically allows you to quickly isolate the code that's causing problems for the static analyzer. 

You mentioned that your code includes several large unions and match statements. There are some static analysis operations that are necessarily O(n^2) where n is the size of the union. There are also other operation during type narrowing that are O(n^2), so the combination of the two can get quite expensive in extreme cases.

**Comment by AlexanderPodorov** [comment]
@bschnurr , nothing useful really:
```
Loading pyproject.toml file at ***/pyproject.toml
Pyproject file "***/pyproject.toml" has no "[tool.pyright]" section.
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Execution environment: python
  Extra paths:
    (none)
  Python version: 3.12
  Python platform: Darwin
  Search paths:
    /Users/alexander/.cache/pyright-python/1.1.383/node_modules/pyright/dist/typeshed-fallback/stdlib
    ***
    ***/typings
    /Users/alexander/.cache/pyright-python/1.1.383/node_modules/pyright/dist/typeshed-fallback/stubs/...
    /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
    /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload
    ***/.venv/lib/python3.12/site-packages
Found 1 source file
```

**Comment by AlexanderPodorov** [comment]
@erictraut , yes, I'm trying to do this.
This is really weird, I just cleared the contents of the file, pyright worked and completed, pylance did not.

**Comment by heejaechang** [comment]
it could be some pylance specific features are not reacting to cancellation properly. we would need either log we mentioned above or a live repro code.

**Comment by AlexanderPodorov** [comment]
I've worked the MRE, ran it on `pyright 1.1.383`.
Time explodes once the number of `case`s exceeds 10.
```python
class A1:
    pass


class A2:
    pass


class A3:
    pass


class A4:
    pass


class A5:
    pass


class A6:
    pass


class A7:
    pass


class A8:
    pass


class A9:
    pass


class A10:
    pass


class A11:
    pass


class A12:
    pass


class A13:
    pass


class A14:
    pass


class A15:
    pass


class A16:
    pass


class B1:
    pass


class B2:
    pass


class B3:
    pass


class B4:
    pass


class B5:
    pass


class B6:
    pass


class B7:
    pass


class B8:
    pass


class B9:
    pass


class B10:
    pass


class B11:
    pass


class B12:
    pass


class B13:
    pass


class B14:
    pass


class B15:
    pass


class B16:
    pass


# expect to receive a variaty of "A" objects
type UA = A1 | A2 | A3 | A4 | A5 | A6 | A7 | A8 | A9 | A10 | A11 | A12 | A13 | A14 | A15 | A16

# expect to receive a variaty of "B" objects
type UB = B1 | B2 | B3 | B4 | B5 | B6 | B7 | B8 | B9 | B10 | B11 | B12 | B13 | B14 | B15 | B16


# a function that checks if A and B are "compatible":
# A1 compatible to B1, A2 compatible to B2, etc.
# otherwise throw exception
def test(a: UA, b: UB) -> bool:
    match a, b:
        case A1(), B1():
            return True
        case A2(), B2():
            return True
        case A3(), B3():
            return True
        case A4(), B4():
            return True
        case A5(), B5():
            return True
        case A6(), B6():
            return True
        case A7(), B7():
            return True
        case A8(), B8():
            return True
        case A9(), B9():
            return True
        case A10(), B10():
            return True
        case A11(), B11():
            return True
        case A12(), B12():
            return True
        case A13(), B13():
            return True
        case A14(), B14():
            return True
        case A15(), B15():
            return True
        case A16(), B16():
            return True
        case _:
            raise ValueError

```

**Comment by AlexanderPodorov** [comment]
@erictraut, this code can be rewritten using a bunch of `if`s, but I'm curious is it something pyright should support.
The time growth here does not look like polynomial, but rather some sort of exponential.

**Comment by erictraut** [comment]
Thanks for isolating this. I'll investigate potential speed-ups. As I mentioned, there are some cases that are necessarily O(n^2) in the general case, but there are often ways to optimize the logic inside of pyright to handle these cases more optimally.

Could someone from the pylance team please transfer this to the pyright issue tracker?
