### ISSUE TITLE
pylance crash when notebook is opened while interactive window is opened.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#6502]
## Environment data

-   Pylance version: 2024.9.102

## Repro Steps

1. open https://github.com/microsoft/pylance-release/tree/main/testing/single
2. create interactive window using instructions in `interactive_windows.py` 
3. open `noteboook.ipynb`

## Expected behavior

no crash log

## Actual behavior

```
024-09-30 15:48:51.883 [info] Error: ENOENT: no such file or directory, open ''
    at Object.readFileSync (node:fs:450:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:9900)
    at A.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:778949)
    at makeCallSync.subPath (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:826220)
    at w.makeCallSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:828316)
    at w.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:826188)
    at u.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:786308)
    at S.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:786308)
    at x.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/pyright.bundle.js:1:1215563)
    at l.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/pyright.bundle.js:1:1599379)
    at _0x328e2c.readFileSync (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/server.bundle.js:1:507398)
    at /Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/server.bundle.js:1:933327
    at A.handleMessage (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:12503)
    at /Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/vendor.bundle.js:2:17946
    at Worker.<anonymous> (/Users/heejaechang/.vscode/extensions/ms-python.vscode-pylance-2024.9.102/dist/server.bundle.js:1:896100)
    at Worker.emit (node:events:531:35)
    at MessagePort.<anonymous> (node:internal/worker:262:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: ''
```

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.9.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249103-2-October-2024-PreRelease)
