### ISSUE TITLE
Pylance error message appears in Chinese despite English language settings

### ISSUE THREAD

**Issue by vani-lu** [microsoft/pylance-release#6628]
## Environment data

-   Pylance version: v2024.10.1
-   OS and version: Windows 11 Pro 23H2 Build 22631.4317
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.8 Anaconda

## Code Snippet

My pylance seems to be crashing because some reference error in Copilot chat. Most of the error messages are in English, consistent with my system language and VSC display language. But the "Pylance crashes..." error which is both prompted by a pop-up and shown in the output is in Chinese. 

```bash
2024-11-04 15:11:04.223 [info] Error: Debug Failure. Notebook file should not be passed to getWorkspaceForFile: vscode-chat-code-block:/c%3A/Users/admin/Documents/baba-variants-datastore/manipulation.ipynb?8a7a5bf7-bea8-4ad8-afe8-784da3e70450
    at _0x3ac4ca.getWorkspaceForFile (c:\Users\admin\.vscode\extensions\ms-python.vscode-pylance-2024.10.1\dist\server.bundle.js:1:1008842)
    at c:\Users\admin\.vscode\extensions\ms-python.vscode-pylance-2024.10.1\dist\server.bundle.js:1:1026902
    at Array.map (<anonymous>)
    at _0x3ac4ca._filterResultsToCurrentWorkspace (c:\Users\admin\.vscode\extensions\ms-python.vscode-pylance-2024.10.1\dist\server.bundle.js:1:1026819)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at processTimers (node:internal/timers:519:7)
    at c:\Users\admin\.vscode\extensions\ms-python.vscode-pylance-2024.10.1\dist\server.bundle.js:1:1024304

2024-11-04 15:11:04.234 [info] [Error - 15:11:04] Server process exited with code 1.
2024-11-04 15:11:04.235 [info] [Error - 15:11:04] Pylance 在过去 3 分钟内崩溃了 5 次。Pylance 不会重启。有关更多详细信息，请查看[此链接](https://aka.ms/AApf7ox)。
```

Of course the message itself is clear in its content. But I want to know how does pylance decide the language to output, because it feels quite awkward that the extension seemingly knows where I am.

- My VSCode display language is English. I have not installed a Chinese language pack.
- My Windows display language is also English. But I have "English" and "Chinese" both set as the preferred language, with English ranking first.
- Windows Region is set to China, but Regional Format is "English (en-US)" respecting my display language

**Comment by StellaHuang95** [comment]
Thanks for reaching out, this might be a duplicate of https://github.com/microsoft/vscode/issues/230172. Are your repro steps the same as in that issue? If not, could you please provide your steps and some sample code? Thanks!

**Comment by StellaHuang95** [comment]
Thanks! The debug failure you encountered is what caused Pylance to crash. The text you saw at the end of the logs is likely a dump of the source at the time of the crash; the actual call stack appears right after the Debug Failure message. This is the same issue as the one linked, triggered by the `viewInChat` command. I’ll follow up on that.

**Comment by debonte** [comment]
Duplicate of https://github.com/microsoft/pylance-release/issues/5880?

**Comment by rchiodo** [comment]
Going to assume this isn't happening anymore. Closing for now.
