### ISSUE TITLE
Pylance doesn't turn on on Windows and fallbacks to Jedi

### ISSUE THREAD

**Issue by maciejmatczak** [microsoft/pylance-release#727]
Issue Type: <b>Bug</b>

Hi,

- simple setup: create empty folder, create one python file, open it
- prompt proposing checking out the Pylance pops - I click it
- Pylance tried to setup but fails and fallback to Jedi

I have standard Python installation from python.org, yet from logs it looks like Pylance seems to very hardly look for MS Store installation (even though it finds the first one). Issue applies regarding if I use venv or not.

Extension version: 2020.12.2
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.07GB free)|
|Process Argv|--crash-reporter-id 8182407b-7e01-496b-a663-e7a489c39ae7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30233462
pythonvspyt600cf:30228412

```

</details>

**Comment by maciejmatczak** [comment]
<details>
<summary>Logs</summary>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPLcf'
User belongs to experiment group 'pythonInstallPylintButtonFirstcf'
> conda --version
> pyenv root
> python3.7 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-12-13 18:23:46: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-12-13 18:23:47: Detection of Python Interpreter for Command py and args -2 failed as file Python 2 not found!

 -3.9-64
 -3.7-32 does not exist
Error 2020-12-13 18:23:47: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.9-64
 -3.7-32 does not exist
Error 2020-12-13 18:23:47: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'd:\Projects\python\checkingpylance\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'd:\Projects\python\checkingpylance\.vscode\settings.json')
	at _handleError (c:\Users\ellox\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:745:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:9:152841)
	at async p.doesFileNeedToBeFixed (c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:39:469606)
	at async c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:39:468733
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:39:468679)
	at async p.updateTestSettings (c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:39:468306)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Starting Pylance language server.
Error 2020-12-13 18:23:47: Failed to get interpreter information for 'C:\Users\ellox\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\ellox\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py" "c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\interpreterInfo.py"
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\ellox\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\ellox\\.vscode\\extensions\\ms-python.python-2020.11.371526539\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\ellox\\.vscode\\extensions\\ms-python.python-2020.11.371526539\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-12-13 18:23:47: Failed to get interpreter information for 'C:\Users\ellox\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\ellox\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py" "c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\interpreterInfo.py"
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\ellox\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\ellox\\.vscode\\extensions\\ms-python.python-2020.11.371526539\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\ellox\\.vscode\\extensions\\ms-python.python-2020.11.371526539\\pythonFiles\\interpreterInfo.py"'
}
> conda --version
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py flake8 --max-line-length=120 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s d:\Projects\python\checkingpylance\somefile.py
cwd: d:\Projects\python\checkingpylance
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py flake8 --max-line-length=120 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s d:\Projects\python\checkingpylance\somefile.py
cwd: d:\Projects\python\checkingpylance
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import flake8"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import flake8"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import flake8"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\ellox\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py -c "import flake8"

```

</details>

**Comment by maciejmatczak** [comment]
I am generally guessing, that installing the MS Store Python can fix the issue.

But I couldn't find any Pylance requirements mentioning it, is it expected?

Forgot Python Language Server logs, after yet another reload though (problem remains):
<details>
<summary>Pylance logs</summary>

```
[Info  - 18:59:27] Pylance language server 2020.12.2 (pyright 6feebac9) starting
[Info  - 18:59:27] Server root directory: c:\Users\ellox\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist
[Info  - 18:59:27] No configuration file found.
[Info  - 18:59:27] Setting pythonPath for service "checkingpylance": "C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\python.exe"
Search paths found for configured python interpreter:
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\DLLs
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\lib
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32
  C:\Users\ellox\AppData\Roaming\Python\Python37\site-packages
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\lib\site-packages
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\lib
  C:\Users\ellox\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pythonwin
[Error - 18:59:27] stubPath d:\Projects\python\checkingpylance\typings is not a valid directory.
[Info  - 18:59:28] Assuming Python version 3.7
[Info  - 18:59:28] Assuming Python platform Windows
[Info  - 18:59:28] Searching for source files
[Info  - 18:59:28] Found 1 source file
[Info  - 18:59:28] Background analysis(1) root directory: c:\Users\ellox\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist
[Info  - 18:59:28] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: analyze
[BG(1)] analyzing: d:\Projects\python\checkingpylance\somefile.py ...
[BG(1)]   parsing: d:\Projects\python\checkingpylance\somefile.py (27ms)
[BG(1)]   parsing: c:\Users\ellox\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 3ms] (155ms)
[BG(1)]   binding: c:\Users\ellox\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\typeshed-fallback\stdlib\3\builtins.pyi (42ms)
[BG(1)]   binding: d:\Projects\python\checkingpylance\somefile.py (0ms)
[BG(1)]   checking: d:\Projects\python\checkingpylance\somefile.py (1ms)
[BG(1)] analyzing: d:\Projects\python\checkingpylance\somefile.py (229ms)
Background analysis message: resumeAnalysis
```

</details>

**Comment by maciejmatczak** [comment]
Nailed it, same issue as https://github.com/microsoft/vscode-python/issues/14320

Even though setting for jedi was grayed out:
![obraz](https://user-images.githubusercontent.com/1786383/102020076-38e70980-3d77-11eb-8378-4fcbce17fbde.png)

...it seems to take over the priority as in https://github.com/microsoft/vscode-python/issues/14320#issuecomment-705857235

Now Pylance starts flawlessly.

**Comment by judej** [comment]
Thanks for the update @maciejmatczak, glad to know you have it working. Happy coding!
