### ISSUE TITLE
pylance works in single file, but not in folder with multiple language.

### ISSUE THREAD

**Issue by wuyudi** [microsoft/pylance-release#781]
## Environment data

-   Language Server version: v2020.12.2
-   OS and version: win10 1803
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 32bit 

## Expected behaviour

This is single file.

![image](https://user-images.githubusercontent.com/30024051/103188918-5682aa00-4905-11eb-8d04-812f1bb3db00.png)

## Actual behaviour

when open folder.

![image](https://user-images.githubusercontent.com/30024051/103189417-787d2c00-4907-11eb-9da3-7cbd89d6a9d4.png)

## Logs

```
[Info  - 下午12:21:37] Pylance language server 2020.12.2 (pyright 6feebac9) starting
[Info  - 下午12:21:37] Server root directory: c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist
[Info  - 下午12:21:37] No configuration file found.
[Info  - 下午12:21:37] Setting pythonPath for service "UOJ15": "D:\Program Files\Python3.8.5\python.exe"
Search paths found for configured python interpreter:
  D:\Program Files\Python3.8.5\DLLs
  D:\Program Files\Python3.8.5\lib
  D:\Program Files\Python3.8.5
  C:\Users\wuyudi\AppData\Roaming\Python\Python38\site-packages
  C:\Users\wuyudi\AppData\Roaming\Python\Python38\site-packages\win32
  C:\Users\wuyudi\AppData\Roaming\Python\Python38\site-packages\win32\lib
  C:\Users\wuyudi\AppData\Roaming\Python\Python38\site-packages\Pythonwin
  D:\Program Files\Python3.8.5\lib\site-packages
[Error - 下午12:21:38] stubPath d:\github_program\OJ\UOJ15\typings is not a valid directory.
[Info  - 下午12:21:38] Assuming Python version 3.8
[Info  - 下午12:21:38] Assuming Python platform Windows
[Info  - 下午12:21:38] Searching for source files
[Info  - 下午12:21:38] Background analysis(1) root directory: c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist
[Info  - 下午12:21:38] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Error: Debug Failure. d:\github_program\oj\uoj15\.py is not a source file
    at P._addToSourceFileListAndMap (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\analyzer\program.ts:2075:13)
    at P.addTrackedFile (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\analyzer\program.ts:245:14)
    at forEach (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\analyzer\program.ts:211:18)
    at Array.forEach (<anonymous>)
    at P.addTrackedFiles (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\analyzer\program.ts:210:19)
    at P.setTrackedFiles (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\analyzer\program.ts:195:14)
    at B.onMessage (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\backgroundAnalysisBase.ts:354:50)
    at B.onMessage (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\server.bundle.js:1:32759)
    at MessagePort.<anonymous> (c:\Users\wuyudi\.vscode\extensions\ms-python.vscode-pylance-2020.12.2\dist\pyright-internal\src\backgroundAnalysisBase.ts:273:66)
    at MessagePort.emit (events.js:223:5)
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
@wuyudi, the filenames are missing for the files. Could you give it a valid filename and let me know if you still see a problem?

thanks

**Comment by wuyudi** [comment]
> @wuyudi, the filenames are missing for the files. Could you give it a valid filename and let me know if you still see a problem?
> 
> thanks

Wow , I know what happens...

For convenience，I didn't write the filename..  So pylance doesn't recognize it. Adding filename fix it.
