### ISSUE TITLE
Cannot access member "connect" for type "pyqtSignal"

### ISSUE THREAD

**Issue by zhanghua000** [microsoft/pylance-release#884]
## Environment data

-   Language Server version: 2021.1.2
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1

## Expected behaviour

extension sets correct syntax highlighting

## Actual behaviour

extension can't find pyqtSignal class's connect method

## Logs

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonInstallPylintButtonFirstcf'
> conda --version
> pyenv root
> python3.7 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> D:\Python\python.exe c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Starting Pylance language server.
Python interpreter path: D:\Python\python.exe
Error 2021-01-27 20:24:25: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.9-64 does not exist
Error 2021-01-27 20:24:25: Detection of Python Interpreter for Command py and args -3.7 failed as file Python 3.7 not found!

 -3.9-64 does not exist
Error 2021-01-27 20:24:25: Detection of Python Interpreter for Command py and args -2 failed as file Python 2 not found!

 -3.9-64 does not exist
Error 2021-01-27 20:24:25: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2021-01-27 20:24:25: Failed to get interpreter information for 'C:\Users\16479\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\16479\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py" "c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\interpreterInfo.py"

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\16479\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\16479\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\16479\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\interpreterInfo.py"'
}
Error 2021-01-27 20:24:25: Failed to get interpreter information for 'C:\Users\16479\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\16479\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py" "c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\interpreterInfo.py"

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\16479\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\16479\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\16479\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\interpreterInfo.py"'
}
> conda --version
> D:\Python\python.exe c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir "c:\Users\16479\Documents\Visual Studio Code" -s --cache-clear
cwd: c:\Users\16479\Documents\Visual Studio Code
> D:\Python\python.exe c:\Users\16479\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir "c:\Users\16479\Documents\Visual Studio Code" -s --cache-clear
cwd: c:\Users\16479\Documents\Visual Studio Code
```

## Code Snippet / Additional information

```python
class Work(QObject):
    signal=pyqtSignal(bytes)
    scan_signal=pyqtSignal(bool)
    def __init__(self,func = None,enable_gui:bool = True):
        super().__init__()
        self.func=func
        self.enable_gui=enable_gui
    def start_process(self):
        self.func(enable_gui=self.enable_gui,signal=self.signal,scan_signal=self.scan_signal)
work=Work(func=init_func,enable_gui=True)
work.signal.connect(show_qr)
work.scan_signal.connect(close_qr)
```
If I run the full script, everything is working as expected.

**Comment by judej** [comment]
@zhanghua000, thanks for the report. Would you please send the following info to help us debug the issue:

1. Logs from the Python Language Server selection in the output tab
2. Larger code snippets that shows the imports and where PyQtSignal came from

**Comment by zhanghua000** [comment]
Logs from the Python Language Server selection:
```
[Info  - 上午10:34:40] Pylance language server 2021.1.3 (pyright 61c53da4) starting
[Info  - 上午10:34:40] Server root directory: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist
[Info  - 上午10:34:40] No configuration file found.
[Info  - 上午10:34:40] Setting pythonPath for service "Visual Studio Code": "D:\Python\python.exe"
Search paths found for configured python interpreter:
  D:\Python\DLLs
  D:\Python\lib
  D:\Python
  D:\Python\lib\site-packages
  D:\Python\lib\site-packages\win32
  D:\Python\lib\site-packages\win32\lib
  D:\Python\lib\site-packages\Pythonwin
[Error - 上午10:34:40] stubPath c:\Users\16479\Documents\Visual Studio Code\typings is not a valid directory.
[Info  - 上午10:34:40] Assuming Python version 3.9
[Info  - 上午10:34:40] Assuming Python platform Windows
[Info  - 上午10:34:40] Searching for source files
[Info  - 上午10:34:40] Found 20 source files
[Info  - 上午10:34:40] Background analysis(1) root directory: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist
[Info  - 上午10:34:40] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
IntelliCode model c:\Users\16479\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.10\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19
Loading ONNX runtime...
Loaded ONNX runtime. Creating IntelliCode session...
2021-01-28 10:34:41.1191373 [I:onnxruntime:, inference_session.cc:174 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-01-28 10:34:41.1221242 [I:onnxruntime:, inference_session.cc:840 onnxruntime::InferenceSession::Initialize] Initializing session.
2021-01-28 10:34:41.1221769 [I:onnxruntime:, inference_session.cc:865 onnxruntime::InferenceSession::Initialize] Adding default CPU execution provider.
2021-01-28 10:34:41.1246607 [I:onnxruntime:, reshape_fusion.cc:37 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-01-28 10:34:41.1256848 [I:onnxruntime:, reshape_fusion.cc:37 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-01-28 10:34:41.1289209 [V:onnxruntime:, inference_session.cc:679 onnxruntime::InferenceSession::TransformGraph] Node placements
2021-01-28 10:34:41.1289472 [V:onnxruntime:, inference_session.cc:681 onnxruntime::InferenceSession::TransformGraph] All nodes have been placed on [CPUExecutionProvider].
2021-01-28 10:34:41.1290012 [V:onnxruntime:, session_state.cc:71 onnxruntime::SessionState::CreateGraphInfo] SaveMLValueNameIndexMapping
2021-01-28 10:34:41.1291322 [V:onnxruntime:, session_state.cc:116 onnxruntime::SessionState::CreateGraphInfo] Done saving OrtValue mappings.
2021-01-28 10:34:41.1308516 [I:onnxruntime:, finalize_session_state.cc:173 onnxruntime::SaveInitializedTensors] Saving initialized tensors.
2021-01-28 10:34:41.1433104 [I:onnxruntime:, finalize_session_state.cc:225 onnxruntime::SaveInitializedTensors] Done saving initialized tensors
2021-01-28 10:34:41.1500395 [I:onnxruntime:, inference_session.cc:954 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
Created IntelliCode session.
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens
[BG(1)] parsing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (149ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 2ms] (98ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi (35ms)
[BG(1)] binding: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (6ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\time.pyi [fs read 1ms] (8ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\time.pyi (1ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\logging\__init__.pyi [fs read 0ms] (29ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\logging\__init__.pyi (6ms)
[BG(1)] parsing: D:\Python\lib\site-packages\qtawesome\__init__.py [fs read 2ms] (21ms)
[BG(1)] binding: D:\Python\lib\site-packages\qtawesome\__init__.py (2ms)
[BG(1)] parsing: D:\Python\lib\site-packages\PyQt5\__init__.py [fs read 1ms] (5ms)
[BG(1)] binding: D:\Python\lib\site-packages\PyQt5\__init__.py (1ms)
[BG(1)] parsing: D:\Python\lib\site-packages\PyQt5\QtGui.pyi [fs read 1ms] (286ms)
[Info  - 上午10:34:41] Searching for source files
[Info  - 上午10:34:41] Found 20 source files
[BG(1)] binding: D:\Python\lib\site-packages\PyQt5\QtGui.pyi (148ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi [fs read 0ms] (8ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (19ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\third_party\2and3\typing_extensions.pyi [fs read 0ms] (5ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\third_party\2and3\typing_extensions.pyi (1ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\typing.pyi [fs read 1ms] (10ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\typing.pyi (9ms)
[BG(1)] parsing: D:\Python\lib\site-packages\PyQt5\QtCore.pyi [fs read 1ms] (121ms)
[BG(1)] binding: D:\Python\lib\site-packages\PyQt5\QtCore.pyi (63ms)
[BG(1)] parsing: D:\Python\lib\site-packages\PyQt5\QtWidgets.pyi [fs read 1ms] (110ms)
[BG(1)] binding: D:\Python\lib\site-packages\PyQt5\QtWidgets.pyi (61ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\abc.pyi [fs read 0ms] (1ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\abc.pyi (0ms)
[BG(1)] parsing: D:\Python\lib\site-packages\qtawesome\iconic_font.py [fs read 0ms] (37ms)
[BG(1)] binding: D:\Python\lib\site-packages\qtawesome\iconic_font.py (3ms)
[BG(1)] parsing: D:\Python\lib\site-packages\qtpy\QtCore.py [fs read 0ms] (38ms)
[BG(1)] binding: D:\Python\lib\site-packages\qtpy\QtCore.py (2ms)
[BG(1)] parsing: D:\Python\lib\site-packages\qtpy\QtGui.py [fs read 0ms] (10ms)
[BG(1)] binding: D:\Python\lib\site-packages\qtpy\QtGui.py (3ms)
[BG(1)] parsing: D:\Python\lib\site-packages\qtpy\__init__.py [fs read 1ms] (20ms)
[BG(1)] binding: D:\Python\lib\site-packages\qtpy\__init__.py (2ms)
[BG(1)] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\types.pyi [fs read 1ms] (11ms)
[BG(1)] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\types.pyi (2ms)
Background analysis message: getSemanticTokens
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py ...
[BG(1)]   checking: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (3ms)
[BG(1)] analyzing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (3ms)
Background analysis message: getSemanticTokens
Background analysis message: markFilesDirty
Background analysis message: invalidateAndForceReanalysis
Background analysis message: invalidateAndForceReanalysis
Background analysis message: markFilesDirty
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
Background analysis message: markFilesDirty
Background analysis message: markFilesDirty
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py ...
[BG(1)]   parsing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (66ms)
[BG(1)]   parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 0ms] (48ms)
[BG(1)]   binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi (33ms)
[BG(1)]   binding: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (2ms)
[BG(1)]   checking: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py ...
[BG(1)]     parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\time.pyi [fs read 0ms] (4ms)
[BG(1)]     binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\time.pyi (1ms)
[BG(1)]     parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\logging\__init__.pyi [fs read 1ms] (22ms)
[BG(1)]     binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\2and3\logging\__init__.pyi (4ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\qtawesome\__init__.py [fs read 0ms] (8ms)
[BG(1)]     binding: D:\Python\lib\site-packages\qtawesome\__init__.py (0ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\PyQt5\__init__.py [fs read 0ms] (6ms)
[BG(1)]     binding: D:\Python\lib\site-packages\PyQt5\__init__.py (0ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\PyQt5\QtCore.pyi [fs read 1ms] (181ms)
[BG(1)]     binding: D:\Python\lib\site-packages\PyQt5\QtCore.pyi (102ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\PyQt5\QtGui.pyi [fs read 1ms] (96ms)
[BG(1)]     binding: D:\Python\lib\site-packages\PyQt5\QtGui.pyi (52ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\PyQt5\QtWidgets.pyi [fs read 2ms] (88ms)
[BG(1)]     binding: D:\Python\lib\site-packages\PyQt5\QtWidgets.pyi (51ms)
[BG(1)]     parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\typing.pyi [fs read 1ms] (11ms)
[BG(1)]     binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\typing.pyi (2ms)
[BG(1)]     parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\abc.pyi [fs read 0ms] (1ms)
[BG(1)]     binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\abc.pyi (0ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\qtawesome\iconic_font.py [fs read 1ms] (38ms)
[BG(1)]     binding: D:\Python\lib\site-packages\qtawesome\iconic_font.py (1ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\qtpy\QtCore.py [fs read 1ms] (31ms)
[BG(1)]     binding: D:\Python\lib\site-packages\qtpy\QtCore.py (1ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\qtpy\QtGui.py [fs read 0ms] (7ms)
[BG(1)]     binding: D:\Python\lib\site-packages\qtpy\QtGui.py (1ms)
[BG(1)]     parsing: D:\Python\lib\site-packages\qtpy\__init__.py [fs read 0ms] (17ms)
[BG(1)]     binding: D:\Python\lib\site-packages\qtpy\__init__.py (1ms)
[BG(1)]     parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\types.pyi [fs read 0ms] (6ms)
[BG(1)]     binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\types.pyi (1ms)
[BG(1)]   checking: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (824ms)
[BG(1)] analyzing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (973ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (92ms)
[FG] parsing: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 2ms] (87ms)
[FG] binding: c:\Users\16479\.vscode\extensions\ms-python.vscode-pylance-2021.1.3\dist\typeshed-fallback\stdlib\3\builtins.pyi (30ms)
[FG] binding: c:\Users\16479\Documents\Visual Studio Code\auto_xuexi_selenium\GUI.py (4ms)

```
And here is the import part of my code:
```python
import time
import logging
import qtawesome
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QObject, QThread, Qt, pyqtSignal
from PyQt5.QtWidgets import QHBoxLayout, QWidget, QGridLayout, QVBoxLayout, QPushButton, QLabel, QPlainTextEdit
```

**Comment by jakebailey** [comment]
Thanks. This to me says that this is an issue with the PyQt5 stubs (or `connect` really does not exist), and not a bug in Pylance. See the definition of the class in these stubs:

```python
# Support for new-style signals and slots.
class pyqtSignal:
    def __init__(self, *types, name: str = ...) -> None: ...
```

We respect the stub, and if you're using a type checking mode that isn't `off`, you'll see errors because the class definition does not include a `connect` method. If you're absolutely certain the `connect` method exists, then you can `# type: ignore` the line. You may want to report an issue to the `PyQt5` repo to see if they can add the method you expect to their stubs.

**Comment by zhanghua000** [comment]
Yes, it is pyqt5's problem. After switching to pyqt6, the problem disappeared.
