### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jonathanH1983** [microsoft/pylance-release#963]
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.2.576481509`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
Python is showing as unresponsive.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 161,
		"activateCallTime": 7,
		"activateResolvedTime": 5082,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-python.vscode-pylance",
				"_lower": "ms-python.vscode-pylance"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

From developer tools:
(node:10880) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

From Output > Python
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonInstallPylintButtonFirstcf'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> python3.7 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> c:\Users\Jonathan\Documents\Programming Folder\Scratch\venv\Scripts\python.exe c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: c:\Users\Jonathan\Documents\Programming Folder\Scratch\venv\Scripts\python.exe
Starting Pylance language server.
Error 2021-02-17 21:33:04: getActivatedEnvironmentVariables [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables, Class name = P, completed in 87941ms, has a falsy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv\\Scripts\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]","sysPrefix":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv","fileHash":"486e57eabb87e8cce3c736991bab7877c1a38dddb29154f82b510d6cbf9476b16debda417e4c28874f4121f24cc6e8fce853a674fcb27a1ddd1b0d0045d4d80e","envName":"venv","type":"Venv","displayName":"Python 3.8.5 64-bit ('venv')","__store":true}, Arg 3: true [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables, Class name = P, completed in 87940ms, has a falsy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv\\Scripts\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]","sysPrefix":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv","fileHash":"486e57eabb87e8cce3c736991bab7877c1a38dddb29154f82b510d6cbf9476b16debda417e4c28874f4121f24cc6e8fce853a674fcb27a1ddd1b0d0045d4d80e","envName":"venv","type":"Venv","displayName":"Python 3.8.5 64-bit ('venv')","__store":true}, Arg 3: true [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
Error 2021-02-17 21:33:30: getActivatedEnvironmentVariables, Class name = P, completed in 87947ms, has a falsy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv\\Scripts\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]","sysPrefix":"c:\\Users\\Jonathan\\Documents\\Programming Folder\\Scratch\\venv","fileHash":"486e57eabb87e8cce3c736991bab7877c1a38dddb29154f82b510d6cbf9476b16debda417e4c28874f4121f24cc6e8fce853a674fcb27a1ddd1b0d0045d4d80e","envName":"venv","type":"Venv","displayName":"Python 3.8.5 64-bit ('venv')","__store":true}, Arg 3: true [Error: Command failed: "c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\Jonathan\.vscode\extensions\ms-python.python-2021.2.576481509\pythonFiles\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py

	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: `"c:/Users/Jonathan/Documents/Programming Folder/Scratch/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\\Users\\Jonathan\\.vscode\\extensions\\ms-python.python-2021.2.576481509\\pythonFiles\\pyvsc-run-isolated.py c:/Users/Jonathan/.vscode/extensions/ms-python.python-2021.2.576481509/pythonFiles/printEnvVariables.py`
}
> conda --version
> conda info --json
> conda --version

**Comment by jakebailey** [comment]
@karthiknadig Why was this transferred? I don't think there's anything related to Pylance here; I see errors related to the environment variable provider (which we do depend on), but nothing that Pylance could be affecting.

**Comment by karthiknadig** [comment]
Those errors don't affect extension load. Transferred it here due to `activationTimes`.

**Comment by jakebailey** [comment]
I see, it's the 5s startup.

**Comment by nolaxpat** [comment]
@jakebailey Just to add a note here - the slow loading of the extension also happens to me occasionally. It isn't always reproducible, but it stops entirely if I roll my `pylance` version back to `2021.1.2`. Any version after that one seems to suffer the issue, some more than others.

**Comment by jakebailey** [comment]
When it occurs, does it output any profiles we could use to figure out why it blocks? IIRC VS Code will do this, but perhaps not in all cases.

**Comment by nolaxpat** [comment]
Not that I see. I have some errors in the `extensionHost` output but nothing that seems special. Of course it's behaving itself right now and I can't reproduce it. 🤷 

I should mention: I am using vscode. I did not file the original report so if there is anything particular I can provide to help, let me know and I'm happy to drop it here.

**Comment by jakebailey** [comment]
We'd need a profile when VSC decides the extension is misbehaving, unfortunately. Performance things like these that don't reproduce are not easy to track down.

**Comment by nolaxpat** [comment]
Just got this with a lag. Pylance latest.

```javascript
[2021-02-23 19:55:02.023] [exthost] [error] [ms-python.python] provider FAILED
[2021-02-23 19:55:02.023] [exthost] [error] Canceled: Canceled
	at E.makeCancelError (~/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:9:175214)
	at E.handleFailedRequest (~/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:9:175065)
	at ~/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:9:143092
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)
```

Spammed this 5 or 6 times in `extensionHost`, this was the last one. Helpful?

**Comment by jakebailey** [comment]
Mmm, not really. That all comes from the Python extension itself. I'm not sure what part of their code is doing that, but it implies it's waiting for some request. Pylance (the extension in question for the report) does not actually call back into the Python extension for anything, it's just a dumb wrapper with some insiders code and settings migration.
