### ISSUE TITLE
Pylance unable to detect imported Package

### ISSUE THREAD

**Issue by ianpatrickbuss** [microsoft/pylance-release#978]
## Environment data

-   Language Server version: v2021.2.3
-   OS and version: Ubuntu 20.04.2 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

When I import a package in the IDE that exists on my machine.  It should be able to detect the package w/o errors.

## Actual behaviour

![python](https://user-images.githubusercontent.com/31316609/108773217-03eff380-752c-11eb-9be6-e91ea3c3149c.png)

## Logs

Unable to get logs to output when I run / open / navigate file.

## Other Info

Here is where Faker is installed on my machine
```
$ pip3 install Faker
Requirement already satisfied: Faker in /home/ian/.local/lib/python3.8/site-packages (6.4.1)
Requirement already satisfied: python-dateutil>=2.4 in /usr/lib/python3/dist-packages (from Faker) (2.7.3)
Requirement already satisfied: text-unidecode==1.3 in /home/ian/.local/lib/python3.8/site-packages (from Faker) (1.3)
```

My guess is that Pylance is looking for the package in a different directory.  
Running which on `pip3` & `python3` yields:
```
/bin/pip3
/bin/python3
```

**Comment by judej** [comment]
@ianpatrickbuss, thanks for the report. The instruction for getting the logs are here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue.

Have you tried following the instructions in the above link to get the logs? If so, what happens when you set the trace level and go to the output window?

**Comment by ianpatrickbuss** [comment]
My apologies, I was looking in the wrong output.

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
> pyenv root
Python interpreter path: /usr/local/bin/python3
Starting Pylance language server.
> conda --version
```
Let me know if this is of any assistance

**Comment by ianpatrickbuss** [comment]
```
[Info  - 1:47:23 PM] Pylance language server 2021.2.3 (pyright 44e42fe5) starting
[Info  - 1:47:23 PM] Server root directory: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist
[Info  - 1:47:23 PM] No configuration file found.
[Info  - 1:47:23 PM] Setting pythonPath for service "pitchingfork": "/usr/local/bin/python3"
Search paths found for configured python interpreter:
  /usr/local/lib/python3.9
  /usr/local/lib/python3.9/lib-dynload
  /home/ian/.local/lib/python3.9/site-packages
  /usr/local/lib/python3.9/site-packages
[Error - 1:47:23 PM] stubPath /home/ian/Project/pitchingfork/typings is not a valid directory.
[Info  - 1:47:23 PM] Assuming Python version 3.9
[Info  - 1:47:23 PM] Assuming Python platform Linux
[Info  - 1:47:23 PM] Searching for source files
[Info  - 1:47:23 PM] Found 1 source file
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (44ms)
[FG] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 4ms] (141ms)
[FG] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/builtins.pyi (37ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[Info  - 1:47:23 PM] Background analysis(1) root directory: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist
[Info  - 1:47:23 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (31ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (84ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/builtins.pyi (34ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/__init__.pyi [fs read 0ms] (6ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/__init__.pyi (2ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (7ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/typing.pyi [fs read 3ms] (31ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/typing.pyi (13ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 0ms] (2ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (1ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/encoder.pyi [fs read 0ms] (3ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/encoder.pyi (0ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/random.pyi [fs read 0ms] (4ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/random.pyi (3ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/os/__init__.pyi [fs read 0ms] (25ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/os/__init__.pyi (22ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/io.pyi [fs read 0ms] (8ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/io.pyi (7ms)
[BG(1)] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (16ms)
[BG(1)] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/types.pyi (3ms)
Background analysis message: getSemanticTokens
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (7ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[FG]   parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/__init__.pyi [fs read 0ms] (3ms)
[FG]   binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/json/__init__.pyi (2ms)
[FG]   parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/random.pyi [fs read 0ms] (6ms)
[FG]   binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/random.pyi (4ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 50 items] (34ms)
[FG] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (13ms)
[FG] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[FG] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/typing.pyi [fs read 0ms] (26ms)
[FG] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stdlib/typing.pyi (21ms)
[FG] parsing: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 0ms] (2ms)
[FG] binding: /home/ian/.vscode/extensions/ms-python.vscode-pylance-2021.2.3/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (0ms)
[FG] parsing: /tmp/pyright-81078-ocUXfUMDXP3w/builtins-81078-u3Sh4tVE7aXj-.py [fs read 1ms] (113ms)
[FG] binding: /tmp/pyright-81078-ocUXfUMDXP3w/builtins-81078-u3Sh4tVE7aXj-.py (41ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[BG(1)]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (60ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (63ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:22 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (8ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:22 [found 62 items] (19ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (6ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 108 items] (19ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (0ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (19ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (19ms)
Background analysis message: resumeAnalysis
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 108 items] (9ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (10ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (42ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (42ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (11ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (22ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (9ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (4ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 108 items] (8ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (4ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (13ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (13ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (10ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (4ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 108 items] (11ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (5ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (5ms)
[BG(1)]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (44ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (51ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: resumeAnalysis
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (15ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 ...
[FG]   parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[FG]   binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
[FG] completion at /home/ian/Project/pitchingfork/utils/fakeData.py:13:21 [found 108 items] (5ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (2ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (3ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (4ms)
[FG] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/ian/Project/pitchingfork/utils/fakeData.py (5ms)
[BG(1)] binding: /home/ian/Project/pitchingfork/utils/fakeData.py (1ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py ...
[BG(1)]   checking: /home/ian/Project/pitchingfork/utils/fakeData.py (20ms)
[BG(1)] analyzing: /home/ian/Project/pitchingfork/utils/fakeData.py (20ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

**Comment by jakebailey** [comment]
The logs indicate that this is the interpreter in use:

```
[Info  - 1:47:23 PM] Setting pythonPath for service "pitchingfork": "/usr/local/bin/python3"
Search paths found for configured python interpreter:
  /usr/local/lib/python3.9
  /usr/local/lib/python3.9/lib-dynload
  /home/ian/.local/lib/python3.9/site-packages
  /usr/local/lib/python3.9/site-packages
```

But your issue shows `/home/ian/.local/lib/python3.8/site-packages`, which is for presumably a different interpreter. What happens when you run `python --version`? Are you sure that your pip isn't broken and putting things into the wrong interpreter? If you have another interpreter for 3.8, can you select it at the bottom left instead of 3.9?

**Comment by ianpatrickbuss** [comment]
```
ian@mercury:~$ python --version
Python 2.7.18
ian@mercury:~$ python3 --version
Python 3.8.5
```
I'm relatively new to Python so I appreciate your patience here.  I may have recently jacked up my whole config between pip3 / python3.  When I run `pip debug` I get
```
pip version: pip 20.3.4 from /home/ian/.local/lib/python2.7/site-packages/pip (python 2.7)
sys.version: 2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0]
sys.executable: /usr/bin/python
sys.getdefaultencoding: ascii
sys.getfilesystemencoding: UTF-8
locale.getpreferredencoding: UTF-8
sys.platform: linux2
sys.implementation:
  name: 
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /home/ian/.local/lib/python2.7/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  packaging==20.8
  toml==0.10.2
  pyparsing==2.4.7
  html5lib==1.1
  appdirs==1.4.4
  distlib==0.3.1
  msgpack==1.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.15.0
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
  progress==1.5
  certifi==2020.11.08
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  urllib3==1.26.2
  retrying==1.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.5.4
  colorama==0.4.4
  CacheControl==0.12.6
  ipaddress==1.0.23
  pep517==0.9.1
  contextlib2==0.6.0.post1 (Unable to locate actual module version, using vendor.txt specified version)
  chardet==3.0.4
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  requests==2.25.0
  idna==2.10
Compatible tags: 351
  cp27-cp27mu-manylinux_2_31_x86_64
  cp27-cp27mu-manylinux_2_30_x86_64
  cp27-cp27mu-manylinux_2_29_x86_64
  cp27-cp27mu-manylinux_2_28_x86_64
  cp27-cp27mu-manylinux_2_27_x86_64
  cp27-cp27mu-manylinux_2_26_x86_64
  cp27-cp27mu-manylinux_2_25_x86_64
  cp27-cp27mu-manylinux_2_24_x86_64
  cp27-cp27mu-manylinux_2_23_x86_64
  cp27-cp27mu-manylinux_2_22_x86_64
  ...
  [First 10 tags shown. Pass --verbose to show all.]
```
But when I run `pip3 debug`
```
Traceback (most recent call last):
  File "/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/debug.py", line 11, in <module>
    from pip._vendor.certifi import where
ModuleNotFoundError: No module named 'pip._vendor.certifi'
```
If I interpreted what you said correctly.  It looks like Pylance is looking for packages stored within a python3.9 version but my system is running 3.8.5?

**Comment by jakebailey** [comment]
Can you run `which python`, as well as `/usr/local/bin/python3 --version`?

**Comment by jakebailey** [comment]
The main thing is that you select the right interpreter at the bottom left in VS Code, but I feel like you may have some things broken...

**Comment by ianpatrickbuss** [comment]
```
ian@mercury:~$ which python
/bin/python
ian@mercury:~$ /usr/local/bin/python3 --version
Python 3.9.0
```
Here you go Jake :)

**Comment by jakebailey** [comment]
Yeah, I don't know what is going on here. It's almost like you've installed Python manually and they are conflicting.

You should be able to select `/bin/python` at the bottom left to get that install, but I feel like there are some mixed-version python shenannegins going on, and I don't know which of the two is the "real" one installed by apt.

**Comment by ianpatrickbuss** [comment]
Thanks for the information Jake.  Based off of what you provided I was able to figure out VSCode had my python interpreter set to 3.9 but the packages were installed with 3.8.5.
I simply reset my interpreter to 3.8.5 by opening the command menu and typing python interpreter and selecting 3.8.5.
Thanks again your time and help with this.  I greatly appreciate it :)

**Comment by NSExceptional** [comment]
@jakebailey I'm having the same issue. I have both Python 2 and 3 installed and I'm trying to use Python 2 and modules installed via `pip2` (aka `pip` on my machine) under `/usr/local/lib/python2.7/site-packages`

I have overridden the python interpreter path setting to the path to `python2`. Why is it not looking in `/usr/local/lib/python2.7/site-packages` for packages?

**Comment by jakebailey** [comment]
Pylance does not support Python 2. Any support is best effort, but I think the code that goes and fetches path should at least work with Python 2 (even if we can't parse or handle Python 2 specific behaviors).

You can enable trace logging to see the paths that we're searching to verify whether or not that specific site-packages directory is included.
