### ISSUE TITLE
Type check does not correctly interpret hint comments for keyword-only arguments

### ISSUE THREAD

**Issue by uranusjr** [microsoft/pylance-release#979]
## Environment data

-   Language Server version: 2021.2.3
-   OS and version: Windows 10 19042.804
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.6 from python.org

## Expected behaviour

```python
def this_does_not_work(*, flag):
    # type: (bool) -> bool
    return flag
```

## Actual behaviour

Pylance complains *Parameter annotation count mismatch: expected 2 but received 1*.

## Logs

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Launcher\py.exe c:\Users\uranusjr\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> conda env list
Error 2021-02-23 17:25:12: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> ~\AppData\Local\Programs\pipx\bin\flake8.exe --ignore=E203 --ignore=F999 --ignore=W503 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\Users\uranusjr\Downloads\x.py
cwd: c:\Users\uranusjr\Downloads
> ~\AppData\Local\Programs\pipx\bin\mypy.exe --ignore-missing-imports --follow-imports=silent --show-column-numbers c:\Users\uranusjr\Downloads\x.py
cwd: c:\Users\uranusjr\Downloads
Starting Pylance language server.
Python interpreter path: ~\AppData\Local\Programs\Python\Launcher\py.exe
##########Linting Output - flake8##########
> pyenv root
> conda --version
> pyenv root
##########Linting Output - mypy##########
Success: no issues found in 1 source file
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
```

## Code Snippet / Additional information

```python
def this_does_not_work(*, flag):
    # type: (bool) -> bool
    return flag

def this_works(*, flag: bool) -> bool:
    return flag
```

**Comment by uranusjr** [comment]
The project (pip) has a large amount of type hint comments carried over from when it had to support older versions, and only recently started incorporating features available in 3.6+. I’m trying to refactor some functions to use keyword-only arguments for better runtime safety, but having to also rewrite the function’s type hint at the same time makes code review more difficult, which I would like to avoid.

It’s perfectly fine if you choose to not fix this; I can learn to ignore the errors until eventually someone comes around to rewrite all the type hint comments. But it’d be awesome if type hint comments can be considered as first-class citizen like inline type hints like they are to standard tooling (Mypy).

**Comment by erictraut** [comment]
OK, thanks for the additional details. Makes sense. 

If you're modernizing your code base by adding keyword-only separators, now is a good time to modernize the type annotations as well. :)

Type hint comments are an anachronism at this point. They existed at a point in history when Python didn't have proper syntax support for type annotations. Because of this, we don't currently have plans to expand support for type hint comments. If we get requests from a bunch of users, we might consider this, so we can keep this request open and see if it gets additional upvotes.

**Comment by jakebailey** [comment]
I don't think we're doing to do this at this point; scanning over the pip codebase shows a pretty good usage of type hints (many months later), so I don't know if it's needed in any case.
