### ISSUE TITLE
Corrupted Release

### ISSUE THREAD

**Issue by florian-sattler** [microsoft/pylance-release#987]
When trying to install the current pylance release from the VS Code Marketplace I get the following prompt:

```
Corrupt ZIP: end of central directory record signature not found
```

## Environment data
-   Language Server version:
-   OS and version: Windows 10 20H2 > WSL 2 > Ubuntu 20.04.2 LTS
-   Python version: 3.8.5

## Expected behaviour

Pylance can be install via the VS Code Marketplace

## Actual behaviour

Pylance cannot be install via the VS Code Marketplace

## Logs

```
[2021-02-25 09:16:56.884] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-02-25 09:16:56.907] [remoteagent] [info] Downloaded extension: ms-python.vscode-pylance undefined
[2021-02-25 09:16:56.912] [remoteagent] [error] Failed to install extension: ms-python.vscode-pylance Corrupt ZIP: end of central directory record signature not found
```

**Comment by LP5K** [comment]
![image](https://user-images.githubusercontent.com/32986242/109131979-4d3f7d80-778e-11eb-89a2-8da2ca6a493c.png)

**Comment by LP5K** [comment]
```
[2021-02-25 17:23:01.661] [renderer1] [error] Error while installing 'ms-python.vscode-pylance' extension in the remote server. Corrupt ZIP: end of central directory record signature not found
[2021-02-25 17:23:01.662] [renderer1] [info] Trying to download 'ms-python.vscode-pylance' extension locally and install
[2021-02-25 17:23:12.145] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.","    at /root/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:91185","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
```

**Comment by jakebailey** [comment]
This sometimes happens with the marketplace; try redownloading. I've downloaded and installed successfully from the marketplace, and the file is identical to what I published.

The 2021.2.4 should have a SHA256 hash of 6D01372DD9271A7F4336E18E120B160B1F485010AFDD6BC6ED8547C0D22C7D10.

**Comment by florian-sattler** [comment]
Hey @jakebailey, thanks for the hint! I needed to remove the previously downloaded version in WSL first.
```
rm ~/.vscode-server/data/CachedExtensionVSIXs/ms-python.vscode-pylance-2021.2.4
```
Hitting install again triggered a new download and allowed me to install the extension! Perhaps vs code should retrigger the download itself when the downloaded file is broken?

**Comment by jakebailey** [comment]
Probably, but you'd need to talk to the VS Code team about that. Arguably, they should be checksumming their downloads and verifying them, rather than unpacking them and failing.
