### ISSUE TITLE
Typo in PIL stub

### ISSUE THREAD

**Issue by alvesvaren** [microsoft/pylance-release#994]
## Environment data

-   Language Server version: (Can't see for some reason)
-   OS and version: Arch Linux, 5.10.17-rt32-xanmod1-1-rt kernel
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2

## Expected behaviour

`Image.rotate(number, expand=True)` works without any typing issue

## Actual behaviour

Pylance says that there's no parameter named expand.
Checking the stub file Image.pyi:160 reveals that it's accidentally named `exexpand` in the file.

## Logs

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonTensorboardExperimentcf'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda env list
Error 2021-02-26 15:07:25: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
Error 2021-02-26 15:07:25: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/alve/dev/binimg/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/alve/dev/binimg/.vscode/settings.json')
	at _handleError (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:136165)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (/home/alve/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:9:298390)
	at async p.doesFileNeedToBeFixed (/home/alve/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:59:481374)
	at async /home/alve/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:59:480501
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/alve/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:59:480447)
	at async p.updateTestSettings (/home/alve/.vscode/extensions/ms-python.python-2021.2.582707922/out/client/extension.js:59:480074)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Python interpreter path: /usr/bin/python
> conda --version

```
(this does not look correct but that's not the problem)

## Code Snippet / Additional information

```python
from PIL import Image
from PIL.ImageEnhance import Contrast

im = Image.open("image.jpg")
im = enhancer = Contrast(im).enhance(100)

# im = im.filter(ImageFilter)
im = im.rotate(-90, expand=True)  # Says that this is incorrect
im.show()
for i in im.getdata():
    print(i)
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021

**Comment by lepakas** [comment]
I have a serious problem.Whenever I install a library ex. Pillow or phonenumbers and then try to use them i cannot because in output says module error no module named PIL  how can I solve this problem ???
Also sometimes it says that Pylance have not access in a certain library ex

**Comment by rchiodo** [comment]
> I have a serious problem.Whenever I install a library ex. Pillow or phonenumbers and then try to use them i cannot because in output says module error no module named PIL how can I solve this problem ??? Also sometimes it says that Pylance have not access in a certain library ex

@lepakas can you log a new issue following our guidelines here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
